/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T06:57:32.892Z
 *
 */
/** eslint-disable max-classes */
import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class FindPetsCommand extends commands.FindPetsCommand {
	static responseSchema = schemas.findPetsCommandResponseSchema;
}

export class AddPetCommand extends commands.AddPetCommand {
	static responseSchema = schemas.addPetCommandResponseSchema;
}

export class FindPetByIdCommand extends commands.FindPetByIdCommand {
	static responseSchema = schemas.findPetByIdCommandResponseSchema;
}

export class FindPetWrappedCommand extends commands.FindPetWrappedCommand {
	static responseSchema = schemas.findPetWrappedCommandResponseSchema;
}

export { DeletePetCommand } from "./commands.js";
