/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class FindPetsCommand extends commands.FindPetsCommand {
	public override readonly responseSchema =
		schemas.findPetsCommandResponseSchema;
}

export class AddPetCommand extends commands.AddPetCommand {
	public override readonly responseSchema = schemas.addPetCommandResponseSchema;
}

export class FindPetByIdCommand extends commands.FindPetByIdCommand {
	public override readonly responseSchema =
		schemas.findPetByIdCommandResponseSchema;
}

export class FindPetWrappedCommand extends commands.FindPetWrappedCommand {
	public override readonly responseSchema =
		schemas.findPetWrappedCommandResponseSchema;
}

export { DeletePetCommand } from "./commands.js";
