/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-04-23T13:57:47.210Z
 *
 */
/** eslint-disable max-classes */
import { Command, jsonStringify, stripUndefined } from "@block65/rest-client";
import type {
	AddPetCommandInput,
	DeletePetCommandInput,
	FindPetByIdCommandInput,
	FindPetsCommandInput,
	FindPetsCommandQuery,
	Pet,
} from "./types.js";

/**
 * Tagged template literal that applies encodeURIComponent to all interpolated
 * values, protecting path integrity from characters like `/` and `#`.
 * @example encodePath`/users/${userId}` // "/users/foo%2Fbar"
 */
function encodePath(
	strings: TemplateStringsArray,
	...values: string[]
): string {
	return String.raw({ raw: strings }, ...values.map(encodeURIComponent));
}

/**
 * Returns all pets from the system that the user has access to
 * Nam sed condimentum est. Maecenas tempor sagittis sapien, nec rhoncus sem
 * sagittis sit amet. Aenean at gravida augue, ac iaculis sem. Curabitur odio
 * lorem, ornare eget elementum nec, cursus id lectus. Duis mi turpis,
 * pulvinar ac eros ac, tincidunt varius justo. In hac habitasse platea
 * dictumst. Integer at adipiscing ante, a sagittis ligula. Aenean pharetra
 * tempor ante molestie imperdiet. Vivamus id aliquam diam. Cras quis velit
 * non tortor eleifend sagittis. Praesent at enim pharetra urna volutpat
 * venenatis eget eget mauris. In eleifend fermentum facilisis. Praesent enim
 * enim, gravida ac sodales sed, placerat id erat. Suspendisse lacus dolor,
 * consectetur non augue vel, vehicula interdum libero. Morbi euismod sagittis
 * libero sed lacinia.
 *
 * Sed tempus felis lobortis leo pulvinar rutrum. Nam mattis velit nisl, eu
 * condimentum ligula luctus nec. Phasellus semper velit eget aliquet
 * faucibus. In a mattis elit. Phasellus vel urna viverra, condimentum lorem
 * id, rhoncus nibh. Ut pellentesque posuere elementum. Sed a varius odio.
 * Morbi rhoncus ligula libero, vel eleifend nunc tristique vitae. Fusce et
 * sem dui. Aenean nec scelerisque tortor. Fusce malesuada accumsan magna vel
 * tempus. Quisque mollis felis eu dolor tristique, sit amet auctor felis
 * gravida. Sed libero lorem, molestie sed nisl in, accumsan tempor nisi.
 * Fusce sollicitudin massa ut lacinia mattis. Sed vel eleifend lorem.
 * Pellentesque vitae felis pretium, pulvinar elit eu, euismod sapien.
 *
 */
export class FindPetsCommand extends Command<
	FindPetsCommandInput,
	Pet[],
	FindPetsCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: FindPetsCommandInput) {
		const { tags, limit } = input ?? {};
		super("/pets", undefined, stripUndefined({ tags, limit }));
	}
}

/**
 * Creates a new pet in the store. Duplicates are allowed
 *
 */
export class AddPetCommand extends Command<AddPetCommandInput, Pet> {
	public override method = "post" as const;

	constructor(input: AddPetCommandInput) {
		const body = input;
		super("/pets", jsonStringify(body));
	}
}

/**
 * Returns a user based on a single ID, if the user does not have access to
 * the pet
 *
 */
export class FindPetByIdCommand extends Command<FindPetByIdCommandInput, Pet> {
	public override method = "get" as const;

	constructor(input: FindPetByIdCommandInput) {
		const { id } = input;
		super(encodePath`/pets/${id}`);
	}
}

/**
 * deletes a single pet based on the ID supplied
 *
 */
export class DeletePetCommand extends Command<
	DeletePetCommandInput,
	undefined
> {
	public override method = "delete" as const;

	constructor(input: DeletePetCommandInput) {
		const { id } = input;
		super(encodePath`/pets/${id}`);
	}
}
