/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-04-23T14:04:54.067Z
 *
 */

import { PublicValibotHonoError } from "@block65/rest-client";
import { validator } from "hono/validator";
import * as v from "valibot";
import {
	addPetCommandBodySchema,
	deletePetCommandParamsSchema,
	findPetByIdCommandParamsSchema,
	findPetsCommandQuerySchema,
} from "./valibot.js";

function toPublicValibotHonoError(err: unknown): never {
	if (err instanceof v.ValiError) {
		throw PublicValibotHonoError.from(err);
	}
	throw err;
}

export const findPets = [
	validator("query", (value) => {
		return v
			.parseAsync(findPetsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const addPet = [
	validator("json", (value) => {
		return v
			.parseAsync(addPetCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const findpetbyid = [
	validator("param", (value) => {
		return v
			.parseAsync(findPetByIdCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deletePet = [
	validator("param", (value) => {
		return v
			.parseAsync(deletePetCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
