import {
	PublicValidationError,
	parseQuery,
	type QueryParamSpec,
} from "@block65/rest-client";
import type { StandardSchemaV1 } from "@standard-schema/spec";
/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */
import { validator } from "hono/validator";
import {
	addPetCommandBodySchema,
	deletePetCommandParamsSchema,
	findPetByIdCommandParamsSchema,
	findPetWrappedCommandParamsSchema,
	findPetsCommandQuerySchema,
} from "./valibot.js";

async function standardParse<TSchema extends StandardSchemaV1>(
	schema: TSchema,
	value: unknown,
) {
	const result = await schema["~standard"].validate(value);
	if (result.issues) {
		throw PublicValidationError.fromIssues(result.issues);
	}
	return result.value;
}

const findPetsQueryParams = [
	{ name: "tags", type: "array", style: "form", explode: true },
] as const satisfies readonly QueryParamSpec[];
export const findPets = [
	validator("query", (value) =>
		standardParse(
			findPetsCommandQuerySchema,
			parseQuery(value, findPetsQueryParams),
		),
	),
] as const;
export const addPet = [
	validator("json", (value) => standardParse(addPetCommandBodySchema, value)),
] as const;
export const findpetbyid = [
	validator("param", (value) =>
		standardParse(findPetByIdCommandParamsSchema, value),
	),
] as const;
export const deletePet = [
	validator("param", (value) =>
		standardParse(deletePetCommandParamsSchema, value),
	),
] as const;
export const findPetWrapped = [
	validator("param", (value) =>
		standardParse(findPetWrappedCommandParamsSchema, value),
	),
] as const;
