/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-01-09T08:04:36.476Z
 *
 */
import { validator } from "hono/validator";
import * as v from "valibot";
import {
	addPetCommandBodySchema,
	deletePetCommandParamsSchema,
	findPetByIdCommandParamsSchema,
	findPetsCommandQuerySchema,
} from "./valibot.js";

export const findPets = [
	validator("query", (value) => {
		return v.parse(findPetsCommandQuerySchema, value);
	}),
] as const;
export const addPet = [
	validator("json", (value) => {
		return v.parse(addPetCommandBodySchema, value);
	}),
] as const;
export const findpetbyid = [
	validator("param", (value) => {
		return v.parse(findPetByIdCommandParamsSchema, value);
	}),
] as const;
export const deletePet = [
	validator("param", (value) => {
		return v.parse(deletePetCommandParamsSchema, value);
	}),
] as const;
