/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */
import {
	RestServiceClient,
	type RestServiceClientConfig,
} from "@block65/rest-client";
import type { UndefinedOnPartialDeep } from "type-fest";
import type {
	AddPetCommandInput,
	DeletePetCommandInput,
	FindPetByIdCommandInput,
	FindPetWrappedCommandInput,
	FindPetWrappedCommandOutput,
	FindPetsCommandInput,
	Pet,
} from "./types.js";

export { ResponseValidationError } from "@block65/rest-client";

type AllInputs =
	| UndefinedOnPartialDeep<AddPetCommandInput>
	| UndefinedOnPartialDeep<DeletePetCommandInput>
	| UndefinedOnPartialDeep<FindPetByIdCommandInput>
	| UndefinedOnPartialDeep<FindPetsCommandInput>
	| UndefinedOnPartialDeep<FindPetWrappedCommandInput>;
type AllOutputs = FindPetWrappedCommandOutput | Pet | Pet[] | undefined;

export class SwaggerPetstoreRestClient extends RestServiceClient<
	AllInputs,
	AllOutputs
> {
	constructor(
		baseUrl: string | URL = new URL("http://petstore.swagger.io/api/"),
		config?: RestServiceClientConfig,
	) {
		super(baseUrl, config);
	}
}
