/**
 * This file is auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2023-04-28T11:02:47.794Z
 *
 */
import {
  type FindPetsCommandInput,
  type AddPetCommandInput,
  type FindPetByIdCommandInput,
  type DeletePetCommandInput,
  type Pet,
} from './types.js';
import {
  RestServiceClient,
  createIsomorphicFetcher,
  type RestServiceClientConfig,
} from '@block65/rest-client';

type AllInputs =
  | FindPetsCommandInput
  | AddPetCommandInput
  | FindPetByIdCommandInput
  | DeletePetCommandInput;
type AllOutputs = Pet | Pet | Pet;

export class SwaggerPetstoreRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    fetcher = createIsomorphicFetcher(),
    config?: RestServiceClientConfig,
  ) {
    super(new URL('http://petstore.swagger.io/api/'), fetcher, config);
  }
}
