/**
 * This file is auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2023-12-14T06:34:23.021Z
 *
 */
import {
  RestServiceClient,
  createIsomorphicNativeFetcher,
  type RestServiceClientConfig,
} from '@block65/rest-client';
import {
  type FindPetsCommandInput,
  type AddPetCommandInput,
  type FindPetByIdCommandInput,
  type DeletePetCommandInput,
  type Pet,
} from './types.js';

type AllInputs =
  | FindPetsCommandInput
  | AddPetCommandInput
  | FindPetByIdCommandInput
  | DeletePetCommandInput;
type AllOutputs = Pet;

export class SwaggerPetstoreRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    baseUrl = new URL('http://petstore.swagger.io/api/'),
    fetcher = createIsomorphicNativeFetcher(),
    config?: RestServiceClientConfig,
  ) {
    super(baseUrl, fetcher, config);
  }
}
