/**
 * This file is auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2023-04-28T12:24:51.108Z
 *
 */
export type NewPet = {
  name: string;
  tag?: string | undefined;
};
export type Error = {
  code: number;
  message: string;
};
export type Pet = NewPet & {
  id: number;
};
export type FindPetsCommandQuery = {
  tags: string[];
  limit: `${number}`;
};
export type FindPetsCommandInput = FindPetsCommandQuery;
export type FindPetsCommandBody = void;
export type AddPetCommandInput = NewPet;
export type AddPetCommandBody = NewPet;
export type FindPetByIdCommandParams = {
  id: string;
};
export type FindPetByIdCommandInput = FindPetByIdCommandParams;
export type FindPetByIdCommandBody = void;
export type DeletePetCommandParams = {
  id: string;
};
export type DeletePetCommandInput = DeletePetCommandParams;
export type DeletePetCommandBody = void;
