/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import type { UndefinedOnPartialDeep } from "type-fest";

export type Error = {
	code: number;
	message: string;
};
export type NewPet = {
	name: string;
	tag?: string;
};
export type Pet = NewPet & {
	id: bigint;
};
export type FindPetsCommandQuery = {
	tags?: readonly string[];
	limit?: `${number}`;
};
export type FindPetsCommandInput = FindPetsCommandQuery;
export type InputFindPetsCommandResponse = UndefinedOnPartialDeep<Pet[]>;
export type AddPetCommandBody = NewPet;
export type AddPetCommandInput = NewPet;
export type InputAddPetCommandResponse = UndefinedOnPartialDeep<Pet>;
export type FindPetByIdCommandParams = {
	id: `${bigint}`;
};
export type FindPetByIdCommandInput = FindPetByIdCommandParams;
export type InputFindPetByIdCommandResponse = UndefinedOnPartialDeep<Pet>;
export type DeletePetCommandParams = {
	id: `${bigint}`;
};
export type DeletePetCommandInput = DeletePetCommandParams;
export type FindPetWrappedCommandParams = {
	id: `${bigint}`;
};
export type FindPetWrappedCommandInput = FindPetWrappedCommandParams;
export type FindPetWrappedCommandOutput = {
	pet: Pet;
};
export type InputFindPetWrappedCommandResponse =
	UndefinedOnPartialDeep<FindPetWrappedCommandOutput>;
