/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-04-23T13:57:47.210Z
 *
 */
import * as v from "valibot";

export const errorSchema = v.strictObject({
	code: v.pipe(v.number(), v.integer()),
	message: v.string(),
});
export const newPetSchema = v.strictObject({
	name: v.string(),
	tag: v.exactOptional(v.string()),
});
export const petSchema = v.intersect([
	newPetSchema,
	v.strictObject({
		id: v.pipe(v.number(), v.integer()),
	}),
]);
export const findPetsCommandQuerySchema = v.strictObject({
	tags: v.exactOptional(v.array(v.string())),
	limit: v.exactOptional(
		v.pipe(
			v.string(),
			v.digits(),
			v.transform((n) => Number.parseInt(n, 10)),
			v.number(),
			v.integer(),
		),
	),
});
export const addPetCommandBodySchema = newPetSchema;
export const findPetByIdCommandParamsSchema = v.strictObject({
	id: v.pipe(v.number(), v.integer()),
});
export const deletePetCommandParamsSchema = v.strictObject({
	id: v.pipe(v.number(), v.integer()),
});
