/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T04:59:34.108Z
 *
 */
import * as v from "valibot";

export const exactErrorSchema = v.strictObject({
	code: v.pipe(v.number(), v.integer()),
	message: v.string(),
});
export const errorSchema = v.strictObject({
	code: v.pipe(v.number(), v.integer()),
	message: v.pipe(v.string(), v.trim()),
});
export const exactNewPetSchema = v.strictObject({
	name: v.string(),
	tag: v.exactOptional(v.string()),
});
export const newPetSchema = v.strictObject({
	name: v.pipe(v.string(), v.trim()),
	tag: v.optional(v.pipe(v.string(), v.trim())),
});
export const exactPetSchema = v.intersect([
	exactNewPetSchema,
	v.strictObject({
		id: v.bigint(),
	}),
]);
export const petSchema = v.intersect([
	newPetSchema,
	v.strictObject({
		id: v.union([
			v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
			v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
			v.bigint(),
		]),
	}),
]);
export const exactFindPetsCommandResponseSchema = v.array(exactPetSchema);
export const findPetsCommandResponseSchema = v.array(petSchema);
export const exactFindPetsCommandQuerySchema = v.strictObject({
	tags: v.exactOptional(v.array(v.string())),
	limit: v.exactOptional(v.pipe(v.number(), v.integer())),
});
export const findPetsCommandQuerySchema = v.strictObject({
	tags: v.optional(v.array(v.pipe(v.string(), v.trim()))),
	limit: v.optional(
		v.union([
			v.pipe(
				v.string(),
				v.decimal(),
				v.toNumber(),
				v.pipe(v.number(), v.integer()),
			),
			v.pipe(v.number(), v.integer()),
		]),
	),
});
export const exactAddPetCommandBodySchema = exactNewPetSchema;
export const addPetCommandBodySchema = newPetSchema;
export const exactAddPetCommandResponseSchema = exactPetSchema;
export const addPetCommandResponseSchema = petSchema;
export const exactFindPetByIdCommandResponseSchema = exactPetSchema;
export const findPetByIdCommandResponseSchema = petSchema;
export const exactFindPetByIdCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const findPetByIdCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
export const exactDeletePetCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const deletePetCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
export const exactFindPetWrappedCommandResponseSchema = v.strictObject({
	pet: exactPetSchema,
});
export const findPetWrappedCommandResponseSchema = v.strictObject({
	pet: petSchema,
});
export const exactFindPetWrappedCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const findPetWrappedCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
