/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T06:57:32.892Z
 *
 */
import * as v from "valibot";

export const inputErrorSchema = v.strictObject({
	code: v.pipe(v.number(), v.integer()),
	message: v.string(),
});
export const errorSchema = v.strictObject({
	code: v.pipe(v.number(), v.integer()),
	message: v.pipe(v.string(), v.trim()),
});
export const inputNewPetSchema = v.strictObject({
	name: v.string(),
	tag: v.optional(v.string()),
});
export const newPetSchema = v.strictObject({
	name: v.pipe(v.string(), v.trim()),
	tag: v.exactOptional(v.pipe(v.string(), v.trim())),
});
export const inputPetSchema = v.intersect([
	inputNewPetSchema,
	v.strictObject({
		id: v.bigint(),
	}),
]);
export const petSchema = v.intersect([
	newPetSchema,
	v.strictObject({
		id: v.union([
			v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
			v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
			v.bigint(),
		]),
	}),
]);
export const inputFindPetsCommandResponseSchema = v.array(inputPetSchema);
export const findPetsCommandResponseSchema = v.array(petSchema);
export const inputFindPetsCommandQuerySchema = v.strictObject({
	tags: v.optional(v.array(v.string())),
	limit: v.optional(v.pipe(v.number(), v.integer())),
});
export const findPetsCommandQuerySchema = v.strictObject({
	tags: v.exactOptional(v.array(v.pipe(v.string(), v.trim()))),
	limit: v.exactOptional(
		v.union([
			v.pipe(
				v.string(),
				v.decimal(),
				v.toNumber(),
				v.pipe(v.number(), v.integer()),
			),
			v.pipe(v.number(), v.integer()),
		]),
	),
});
export const inputAddPetCommandBodySchema = inputNewPetSchema;
export const addPetCommandBodySchema = newPetSchema;
export const inputAddPetCommandResponseSchema = inputPetSchema;
export const addPetCommandResponseSchema = petSchema;
export const inputFindPetByIdCommandResponseSchema = inputPetSchema;
export const findPetByIdCommandResponseSchema = petSchema;
export const inputFindPetByIdCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const findPetByIdCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
export const inputDeletePetCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const deletePetCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
export const inputFindPetWrappedCommandResponseSchema = v.strictObject({
	pet: inputPetSchema,
});
export const findPetWrappedCommandResponseSchema = v.strictObject({
	pet: petSchema,
});
export const inputFindPetWrappedCommandParamsSchema = v.strictObject({
	id: v.bigint(),
});
export const findPetWrappedCommandParamsSchema = v.strictObject({
	id: v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
});
