/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class CreateChatCompletionCommand
	extends commands.CreateChatCompletionCommand
{
	public override readonly responseSchema =
		schemas.createChatCompletionCommandResponseSchema;
}

export class CreateCompletionCommand extends commands.CreateCompletionCommand {
	public override readonly responseSchema =
		schemas.createCompletionCommandResponseSchema;
}

export class CreateImageCommand extends commands.CreateImageCommand {
	public override readonly responseSchema =
		schemas.createImageCommandResponseSchema;
}

export class CreateImageEditCommand extends commands.CreateImageEditCommand {
	public override readonly responseSchema =
		schemas.createImageEditCommandResponseSchema;
}

export class CreateImageVariationCommand
	extends commands.CreateImageVariationCommand
{
	public override readonly responseSchema =
		schemas.createImageVariationCommandResponseSchema;
}

export class CreateEmbeddingCommand extends commands.CreateEmbeddingCommand {
	public override readonly responseSchema =
		schemas.createEmbeddingCommandResponseSchema;
}

export class CreateTranscriptionCommand
	extends commands.CreateTranscriptionCommand
{
	public override readonly responseSchema =
		schemas.createTranscriptionCommandResponseSchema;
}

export class CreateTranslationCommand
	extends commands.CreateTranslationCommand
{
	public override readonly responseSchema =
		schemas.createTranslationCommandResponseSchema;
}

export class ListFilesCommand extends commands.ListFilesCommand {
	public override readonly responseSchema =
		schemas.listFilesCommandResponseSchema;
}

export class CreateFileCommand extends commands.CreateFileCommand {
	public override readonly responseSchema =
		schemas.createFileCommandResponseSchema;
}

export class DeleteFileCommand extends commands.DeleteFileCommand {
	public override readonly responseSchema =
		schemas.deleteFileCommandResponseSchema;
}

export class RetrieveFileCommand extends commands.RetrieveFileCommand {
	public override readonly responseSchema =
		schemas.retrieveFileCommandResponseSchema;
}

export class DownloadFileCommand extends commands.DownloadFileCommand {
	public override readonly responseSchema =
		schemas.downloadFileCommandResponseSchema;
}

export class CreateUploadCommand extends commands.CreateUploadCommand {
	public override readonly responseSchema =
		schemas.createUploadCommandResponseSchema;
}

export class AddUploadPartCommand extends commands.AddUploadPartCommand {
	public override readonly responseSchema =
		schemas.addUploadPartCommandResponseSchema;
}

export class CompleteUploadCommand extends commands.CompleteUploadCommand {
	public override readonly responseSchema =
		schemas.completeUploadCommandResponseSchema;
}

export class CancelUploadCommand extends commands.CancelUploadCommand {
	public override readonly responseSchema =
		schemas.cancelUploadCommandResponseSchema;
}

export class CreateFineTuningJobCommand
	extends commands.CreateFineTuningJobCommand
{
	public override readonly responseSchema =
		schemas.createFineTuningJobCommandResponseSchema;
}

export class ListPaginatedFineTuningJobsCommand
	extends commands.ListPaginatedFineTuningJobsCommand
{
	public override readonly responseSchema =
		schemas.listPaginatedFineTuningJobsCommandResponseSchema;
}

export class RetrieveFineTuningJobCommand
	extends commands.RetrieveFineTuningJobCommand
{
	public override readonly responseSchema =
		schemas.retrieveFineTuningJobCommandResponseSchema;
}

export class ListFineTuningEventsCommand
	extends commands.ListFineTuningEventsCommand
{
	public override readonly responseSchema =
		schemas.listFineTuningEventsCommandResponseSchema;
}

export class CancelFineTuningJobCommand
	extends commands.CancelFineTuningJobCommand
{
	public override readonly responseSchema =
		schemas.cancelFineTuningJobCommandResponseSchema;
}

export class ListFineTuningJobCheckpointsCommand
	extends commands.ListFineTuningJobCheckpointsCommand
{
	public override readonly responseSchema =
		schemas.listFineTuningJobCheckpointsCommandResponseSchema;
}

export class ListModelsCommand extends commands.ListModelsCommand {
	public override readonly responseSchema =
		schemas.listModelsCommandResponseSchema;
}

export class RetrieveModelCommand extends commands.RetrieveModelCommand {
	public override readonly responseSchema =
		schemas.retrieveModelCommandResponseSchema;
}

export class DeleteModelCommand extends commands.DeleteModelCommand {
	public override readonly responseSchema =
		schemas.deleteModelCommandResponseSchema;
}

export class CreateModerationCommand extends commands.CreateModerationCommand {
	public override readonly responseSchema =
		schemas.createModerationCommandResponseSchema;
}

export class ListAssistantsCommand extends commands.ListAssistantsCommand {
	public override readonly responseSchema =
		schemas.listAssistantsCommandResponseSchema;
}

export class CreateAssistantCommand extends commands.CreateAssistantCommand {
	public override readonly responseSchema =
		schemas.createAssistantCommandResponseSchema;
}

export class GetAssistantCommand extends commands.GetAssistantCommand {
	public override readonly responseSchema =
		schemas.getAssistantCommandResponseSchema;
}

export class ModifyAssistantCommand extends commands.ModifyAssistantCommand {
	public override readonly responseSchema =
		schemas.modifyAssistantCommandResponseSchema;
}

export class DeleteAssistantCommand extends commands.DeleteAssistantCommand {
	public override readonly responseSchema =
		schemas.deleteAssistantCommandResponseSchema;
}

export class CreateThreadCommand extends commands.CreateThreadCommand {
	public override readonly responseSchema =
		schemas.createThreadCommandResponseSchema;
}

export class GetThreadCommand extends commands.GetThreadCommand {
	public override readonly responseSchema =
		schemas.getThreadCommandResponseSchema;
}

export class ModifyThreadCommand extends commands.ModifyThreadCommand {
	public override readonly responseSchema =
		schemas.modifyThreadCommandResponseSchema;
}

export class DeleteThreadCommand extends commands.DeleteThreadCommand {
	public override readonly responseSchema =
		schemas.deleteThreadCommandResponseSchema;
}

export class ListMessagesCommand extends commands.ListMessagesCommand {
	public override readonly responseSchema =
		schemas.listMessagesCommandResponseSchema;
}

export class CreateMessageCommand extends commands.CreateMessageCommand {
	public override readonly responseSchema =
		schemas.createMessageCommandResponseSchema;
}

export class GetMessageCommand extends commands.GetMessageCommand {
	public override readonly responseSchema =
		schemas.getMessageCommandResponseSchema;
}

export class ModifyMessageCommand extends commands.ModifyMessageCommand {
	public override readonly responseSchema =
		schemas.modifyMessageCommandResponseSchema;
}

export class DeleteMessageCommand extends commands.DeleteMessageCommand {
	public override readonly responseSchema =
		schemas.deleteMessageCommandResponseSchema;
}

export class CreateThreadAndRunCommand
	extends commands.CreateThreadAndRunCommand
{
	public override readonly responseSchema =
		schemas.createThreadAndRunCommandResponseSchema;
}

export class ListRunsCommand extends commands.ListRunsCommand {
	public override readonly responseSchema =
		schemas.listRunsCommandResponseSchema;
}

export class CreateRunCommand extends commands.CreateRunCommand {
	public override readonly responseSchema =
		schemas.createRunCommandResponseSchema;
}

export class GetRunCommand extends commands.GetRunCommand {
	public override readonly responseSchema = schemas.getRunCommandResponseSchema;
}

export class ModifyRunCommand extends commands.ModifyRunCommand {
	public override readonly responseSchema =
		schemas.modifyRunCommandResponseSchema;
}

export class SubmitToolOuputsToRunCommand
	extends commands.SubmitToolOuputsToRunCommand
{
	public override readonly responseSchema =
		schemas.submitToolOuputsToRunCommandResponseSchema;
}

export class CancelRunCommand extends commands.CancelRunCommand {
	public override readonly responseSchema =
		schemas.cancelRunCommandResponseSchema;
}

export class ListRunStepsCommand extends commands.ListRunStepsCommand {
	public override readonly responseSchema =
		schemas.listRunStepsCommandResponseSchema;
}

export class GetRunStepCommand extends commands.GetRunStepCommand {
	public override readonly responseSchema =
		schemas.getRunStepCommandResponseSchema;
}

export class ListVectorStoresCommand extends commands.ListVectorStoresCommand {
	public override readonly responseSchema =
		schemas.listVectorStoresCommandResponseSchema;
}

export class CreateVectorStoreCommand
	extends commands.CreateVectorStoreCommand
{
	public override readonly responseSchema =
		schemas.createVectorStoreCommandResponseSchema;
}

export class GetVectorStoreCommand extends commands.GetVectorStoreCommand {
	public override readonly responseSchema =
		schemas.getVectorStoreCommandResponseSchema;
}

export class ModifyVectorStoreCommand
	extends commands.ModifyVectorStoreCommand
{
	public override readonly responseSchema =
		schemas.modifyVectorStoreCommandResponseSchema;
}

export class DeleteVectorStoreCommand
	extends commands.DeleteVectorStoreCommand
{
	public override readonly responseSchema =
		schemas.deleteVectorStoreCommandResponseSchema;
}

export class ListVectorStoreFilesCommand
	extends commands.ListVectorStoreFilesCommand
{
	public override readonly responseSchema =
		schemas.listVectorStoreFilesCommandResponseSchema;
}

export class CreateVectorStoreFileCommand
	extends commands.CreateVectorStoreFileCommand
{
	public override readonly responseSchema =
		schemas.createVectorStoreFileCommandResponseSchema;
}

export class GetVectorStoreFileCommand
	extends commands.GetVectorStoreFileCommand
{
	public override readonly responseSchema =
		schemas.getVectorStoreFileCommandResponseSchema;
}

export class DeleteVectorStoreFileCommand
	extends commands.DeleteVectorStoreFileCommand
{
	public override readonly responseSchema =
		schemas.deleteVectorStoreFileCommandResponseSchema;
}

export class CreateVectorStoreFileBatchCommand
	extends commands.CreateVectorStoreFileBatchCommand
{
	public override readonly responseSchema =
		schemas.createVectorStoreFileBatchCommandResponseSchema;
}

export class GetVectorStoreFileBatchCommand
	extends commands.GetVectorStoreFileBatchCommand
{
	public override readonly responseSchema =
		schemas.getVectorStoreFileBatchCommandResponseSchema;
}

export class CancelVectorStoreFileBatchCommand
	extends commands.CancelVectorStoreFileBatchCommand
{
	public override readonly responseSchema =
		schemas.cancelVectorStoreFileBatchCommandResponseSchema;
}

export class ListFilesInVectorStoreBatchCommand
	extends commands.ListFilesInVectorStoreBatchCommand
{
	public override readonly responseSchema =
		schemas.listFilesInVectorStoreBatchCommandResponseSchema;
}

export class CreateBatchCommand extends commands.CreateBatchCommand {
	public override readonly responseSchema =
		schemas.createBatchCommandResponseSchema;
}

export class ListBatchesCommand extends commands.ListBatchesCommand {
	public override readonly responseSchema =
		schemas.listBatchesCommandResponseSchema;
}

export class RetrieveBatchCommand extends commands.RetrieveBatchCommand {
	public override readonly responseSchema =
		schemas.retrieveBatchCommandResponseSchema;
}

export class CancelBatchCommand extends commands.CancelBatchCommand {
	public override readonly responseSchema =
		schemas.cancelBatchCommandResponseSchema;
}

export class ListAuditLogsCommand extends commands.ListAuditLogsCommand {
	public override readonly responseSchema =
		schemas.listAuditLogsCommandResponseSchema;
}

export class ListInvitesCommand extends commands.ListInvitesCommand {
	public override readonly responseSchema =
		schemas.listInvitesCommandResponseSchema;
}

export class InviteUserCommand extends commands.InviteUserCommand {
	public override readonly responseSchema =
		schemas.inviteUserCommandResponseSchema;
}

export class RetrieveInviteCommand extends commands.RetrieveInviteCommand {
	public override readonly responseSchema =
		schemas.retrieveInviteCommandResponseSchema;
}

export class DeleteInviteCommand extends commands.DeleteInviteCommand {
	public override readonly responseSchema =
		schemas.deleteInviteCommandResponseSchema;
}

export class ListUsersCommand extends commands.ListUsersCommand {
	public override readonly responseSchema =
		schemas.listUsersCommandResponseSchema;
}

export class RetrieveUserCommand extends commands.RetrieveUserCommand {
	public override readonly responseSchema =
		schemas.retrieveUserCommandResponseSchema;
}

export class ModifyUserCommand extends commands.ModifyUserCommand {
	public override readonly responseSchema =
		schemas.modifyUserCommandResponseSchema;
}

export class DeleteUserCommand extends commands.DeleteUserCommand {
	public override readonly responseSchema =
		schemas.deleteUserCommandResponseSchema;
}

export class ListProjectsCommand extends commands.ListProjectsCommand {
	public override readonly responseSchema =
		schemas.listProjectsCommandResponseSchema;
}

export class CreateProjectCommand extends commands.CreateProjectCommand {
	public override readonly responseSchema =
		schemas.createProjectCommandResponseSchema;
}

export class RetrieveProjectCommand extends commands.RetrieveProjectCommand {
	public override readonly responseSchema =
		schemas.retrieveProjectCommandResponseSchema;
}

export class ModifyProjectCommand extends commands.ModifyProjectCommand {
	public override readonly responseSchema =
		schemas.modifyProjectCommandResponseSchema;
}

export class ArchiveProjectCommand extends commands.ArchiveProjectCommand {
	public override readonly responseSchema =
		schemas.archiveProjectCommandResponseSchema;
}

export class ListProjectUsersCommand extends commands.ListProjectUsersCommand {
	public override readonly responseSchema =
		schemas.listProjectUsersCommandResponseSchema;
}

export class CreateProjectUserCommand
	extends commands.CreateProjectUserCommand
{
	public override readonly responseSchema =
		schemas.createProjectUserCommandResponseSchema;
}

export class RetrieveProjectUserCommand
	extends commands.RetrieveProjectUserCommand
{
	public override readonly responseSchema =
		schemas.retrieveProjectUserCommandResponseSchema;
}

export class ModifyProjectUserCommand
	extends commands.ModifyProjectUserCommand
{
	public override readonly responseSchema =
		schemas.modifyProjectUserCommandResponseSchema;
}

export class DeleteProjectUserCommand
	extends commands.DeleteProjectUserCommand
{
	public override readonly responseSchema =
		schemas.deleteProjectUserCommandResponseSchema;
}

export class ListProjectServiceAccountsCommand
	extends commands.ListProjectServiceAccountsCommand
{
	public override readonly responseSchema =
		schemas.listProjectServiceAccountsCommandResponseSchema;
}

export class CreateProjectServiceAccountCommand
	extends commands.CreateProjectServiceAccountCommand
{
	public override readonly responseSchema =
		schemas.createProjectServiceAccountCommandResponseSchema;
}

export class RetrieveProjectServiceAccountCommand
	extends commands.RetrieveProjectServiceAccountCommand
{
	public override readonly responseSchema =
		schemas.retrieveProjectServiceAccountCommandResponseSchema;
}

export class DeleteProjectServiceAccountCommand
	extends commands.DeleteProjectServiceAccountCommand
{
	public override readonly responseSchema =
		schemas.deleteProjectServiceAccountCommandResponseSchema;
}

export class ListProjectApiKeysCommand
	extends commands.ListProjectApiKeysCommand
{
	public override readonly responseSchema =
		schemas.listProjectApiKeysCommandResponseSchema;
}

export class RetrieveProjectApiKeyCommand
	extends commands.RetrieveProjectApiKeyCommand
{
	public override readonly responseSchema =
		schemas.retrieveProjectApiKeyCommandResponseSchema;
}

export class DeleteProjectApiKeyCommand
	extends commands.DeleteProjectApiKeyCommand
{
	public override readonly responseSchema =
		schemas.deleteProjectApiKeyCommandResponseSchema;
}

export { CreateSpeechCommand } from "./commands.js";
