/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T06:12:45.230Z
 *
 */
/** eslint-disable max-classes */
import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class CreateChatCompletionCommand
	extends commands.CreateChatCompletionCommand
{
	static responseSchema = schemas.createChatCompletionCommandResponseSchema;
}

export class CreateCompletionCommand extends commands.CreateCompletionCommand {
	static responseSchema = schemas.createCompletionCommandResponseSchema;
}

export class CreateImageCommand extends commands.CreateImageCommand {
	static responseSchema = schemas.createImageCommandResponseSchema;
}

export class CreateImageEditCommand extends commands.CreateImageEditCommand {
	static responseSchema = schemas.createImageEditCommandResponseSchema;
}

export class CreateImageVariationCommand
	extends commands.CreateImageVariationCommand
{
	static responseSchema = schemas.createImageVariationCommandResponseSchema;
}

export class CreateEmbeddingCommand extends commands.CreateEmbeddingCommand {
	static responseSchema = schemas.createEmbeddingCommandResponseSchema;
}

export class CreateTranscriptionCommand
	extends commands.CreateTranscriptionCommand
{
	static responseSchema = schemas.createTranscriptionCommandResponseSchema;
}

export class CreateTranslationCommand
	extends commands.CreateTranslationCommand
{
	static responseSchema = schemas.createTranslationCommandResponseSchema;
}

export class ListFilesCommand extends commands.ListFilesCommand {
	static responseSchema = schemas.listFilesCommandResponseSchema;
}

export class CreateFileCommand extends commands.CreateFileCommand {
	static responseSchema = schemas.createFileCommandResponseSchema;
}

export class DeleteFileCommand extends commands.DeleteFileCommand {
	static responseSchema = schemas.deleteFileCommandResponseSchema;
}

export class RetrieveFileCommand extends commands.RetrieveFileCommand {
	static responseSchema = schemas.retrieveFileCommandResponseSchema;
}

export class DownloadFileCommand extends commands.DownloadFileCommand {
	static responseSchema = schemas.downloadFileCommandResponseSchema;
}

export class CreateUploadCommand extends commands.CreateUploadCommand {
	static responseSchema = schemas.createUploadCommandResponseSchema;
}

export class AddUploadPartCommand extends commands.AddUploadPartCommand {
	static responseSchema = schemas.addUploadPartCommandResponseSchema;
}

export class CompleteUploadCommand extends commands.CompleteUploadCommand {
	static responseSchema = schemas.completeUploadCommandResponseSchema;
}

export class CancelUploadCommand extends commands.CancelUploadCommand {
	static responseSchema = schemas.cancelUploadCommandResponseSchema;
}

export class CreateFineTuningJobCommand
	extends commands.CreateFineTuningJobCommand
{
	static responseSchema = schemas.createFineTuningJobCommandResponseSchema;
}

export class ListPaginatedFineTuningJobsCommand
	extends commands.ListPaginatedFineTuningJobsCommand
{
	static responseSchema =
		schemas.listPaginatedFineTuningJobsCommandResponseSchema;
}

export class RetrieveFineTuningJobCommand
	extends commands.RetrieveFineTuningJobCommand
{
	static responseSchema = schemas.retrieveFineTuningJobCommandResponseSchema;
}

export class ListFineTuningEventsCommand
	extends commands.ListFineTuningEventsCommand
{
	static responseSchema = schemas.listFineTuningEventsCommandResponseSchema;
}

export class CancelFineTuningJobCommand
	extends commands.CancelFineTuningJobCommand
{
	static responseSchema = schemas.cancelFineTuningJobCommandResponseSchema;
}

export class ListFineTuningJobCheckpointsCommand
	extends commands.ListFineTuningJobCheckpointsCommand
{
	static responseSchema =
		schemas.listFineTuningJobCheckpointsCommandResponseSchema;
}

export class ListModelsCommand extends commands.ListModelsCommand {
	static responseSchema = schemas.listModelsCommandResponseSchema;
}

export class RetrieveModelCommand extends commands.RetrieveModelCommand {
	static responseSchema = schemas.retrieveModelCommandResponseSchema;
}

export class DeleteModelCommand extends commands.DeleteModelCommand {
	static responseSchema = schemas.deleteModelCommandResponseSchema;
}

export class CreateModerationCommand extends commands.CreateModerationCommand {
	static responseSchema = schemas.createModerationCommandResponseSchema;
}

export class ListAssistantsCommand extends commands.ListAssistantsCommand {
	static responseSchema = schemas.listAssistantsCommandResponseSchema;
}

export class CreateAssistantCommand extends commands.CreateAssistantCommand {
	static responseSchema = schemas.createAssistantCommandResponseSchema;
}

export class GetAssistantCommand extends commands.GetAssistantCommand {
	static responseSchema = schemas.getAssistantCommandResponseSchema;
}

export class ModifyAssistantCommand extends commands.ModifyAssistantCommand {
	static responseSchema = schemas.modifyAssistantCommandResponseSchema;
}

export class DeleteAssistantCommand extends commands.DeleteAssistantCommand {
	static responseSchema = schemas.deleteAssistantCommandResponseSchema;
}

export class CreateThreadCommand extends commands.CreateThreadCommand {
	static responseSchema = schemas.createThreadCommandResponseSchema;
}

export class GetThreadCommand extends commands.GetThreadCommand {
	static responseSchema = schemas.getThreadCommandResponseSchema;
}

export class ModifyThreadCommand extends commands.ModifyThreadCommand {
	static responseSchema = schemas.modifyThreadCommandResponseSchema;
}

export class DeleteThreadCommand extends commands.DeleteThreadCommand {
	static responseSchema = schemas.deleteThreadCommandResponseSchema;
}

export class ListMessagesCommand extends commands.ListMessagesCommand {
	static responseSchema = schemas.listMessagesCommandResponseSchema;
}

export class CreateMessageCommand extends commands.CreateMessageCommand {
	static responseSchema = schemas.createMessageCommandResponseSchema;
}

export class GetMessageCommand extends commands.GetMessageCommand {
	static responseSchema = schemas.getMessageCommandResponseSchema;
}

export class ModifyMessageCommand extends commands.ModifyMessageCommand {
	static responseSchema = schemas.modifyMessageCommandResponseSchema;
}

export class DeleteMessageCommand extends commands.DeleteMessageCommand {
	static responseSchema = schemas.deleteMessageCommandResponseSchema;
}

export class CreateThreadAndRunCommand
	extends commands.CreateThreadAndRunCommand
{
	static responseSchema = schemas.createThreadAndRunCommandResponseSchema;
}

export class ListRunsCommand extends commands.ListRunsCommand {
	static responseSchema = schemas.listRunsCommandResponseSchema;
}

export class CreateRunCommand extends commands.CreateRunCommand {
	static responseSchema = schemas.createRunCommandResponseSchema;
}

export class GetRunCommand extends commands.GetRunCommand {
	static responseSchema = schemas.getRunCommandResponseSchema;
}

export class ModifyRunCommand extends commands.ModifyRunCommand {
	static responseSchema = schemas.modifyRunCommandResponseSchema;
}

export class SubmitToolOuputsToRunCommand
	extends commands.SubmitToolOuputsToRunCommand
{
	static responseSchema = schemas.submitToolOuputsToRunCommandResponseSchema;
}

export class CancelRunCommand extends commands.CancelRunCommand {
	static responseSchema = schemas.cancelRunCommandResponseSchema;
}

export class ListRunStepsCommand extends commands.ListRunStepsCommand {
	static responseSchema = schemas.listRunStepsCommandResponseSchema;
}

export class GetRunStepCommand extends commands.GetRunStepCommand {
	static responseSchema = schemas.getRunStepCommandResponseSchema;
}

export class ListVectorStoresCommand extends commands.ListVectorStoresCommand {
	static responseSchema = schemas.listVectorStoresCommandResponseSchema;
}

export class CreateVectorStoreCommand
	extends commands.CreateVectorStoreCommand
{
	static responseSchema = schemas.createVectorStoreCommandResponseSchema;
}

export class GetVectorStoreCommand extends commands.GetVectorStoreCommand {
	static responseSchema = schemas.getVectorStoreCommandResponseSchema;
}

export class ModifyVectorStoreCommand
	extends commands.ModifyVectorStoreCommand
{
	static responseSchema = schemas.modifyVectorStoreCommandResponseSchema;
}

export class DeleteVectorStoreCommand
	extends commands.DeleteVectorStoreCommand
{
	static responseSchema = schemas.deleteVectorStoreCommandResponseSchema;
}

export class ListVectorStoreFilesCommand
	extends commands.ListVectorStoreFilesCommand
{
	static responseSchema = schemas.listVectorStoreFilesCommandResponseSchema;
}

export class CreateVectorStoreFileCommand
	extends commands.CreateVectorStoreFileCommand
{
	static responseSchema = schemas.createVectorStoreFileCommandResponseSchema;
}

export class GetVectorStoreFileCommand
	extends commands.GetVectorStoreFileCommand
{
	static responseSchema = schemas.getVectorStoreFileCommandResponseSchema;
}

export class DeleteVectorStoreFileCommand
	extends commands.DeleteVectorStoreFileCommand
{
	static responseSchema = schemas.deleteVectorStoreFileCommandResponseSchema;
}

export class CreateVectorStoreFileBatchCommand
	extends commands.CreateVectorStoreFileBatchCommand
{
	static responseSchema =
		schemas.createVectorStoreFileBatchCommandResponseSchema;
}

export class GetVectorStoreFileBatchCommand
	extends commands.GetVectorStoreFileBatchCommand
{
	static responseSchema = schemas.getVectorStoreFileBatchCommandResponseSchema;
}

export class CancelVectorStoreFileBatchCommand
	extends commands.CancelVectorStoreFileBatchCommand
{
	static responseSchema =
		schemas.cancelVectorStoreFileBatchCommandResponseSchema;
}

export class ListFilesInVectorStoreBatchCommand
	extends commands.ListFilesInVectorStoreBatchCommand
{
	static responseSchema =
		schemas.listFilesInVectorStoreBatchCommandResponseSchema;
}

export class CreateBatchCommand extends commands.CreateBatchCommand {
	static responseSchema = schemas.createBatchCommandResponseSchema;
}

export class ListBatchesCommand extends commands.ListBatchesCommand {
	static responseSchema = schemas.listBatchesCommandResponseSchema;
}

export class RetrieveBatchCommand extends commands.RetrieveBatchCommand {
	static responseSchema = schemas.retrieveBatchCommandResponseSchema;
}

export class CancelBatchCommand extends commands.CancelBatchCommand {
	static responseSchema = schemas.cancelBatchCommandResponseSchema;
}

export class ListAuditLogsCommand extends commands.ListAuditLogsCommand {
	static responseSchema = schemas.listAuditLogsCommandResponseSchema;
}

export class ListInvitesCommand extends commands.ListInvitesCommand {
	static responseSchema = schemas.listInvitesCommandResponseSchema;
}

export class InviteUserCommand extends commands.InviteUserCommand {
	static responseSchema = schemas.inviteUserCommandResponseSchema;
}

export class RetrieveInviteCommand extends commands.RetrieveInviteCommand {
	static responseSchema = schemas.retrieveInviteCommandResponseSchema;
}

export class DeleteInviteCommand extends commands.DeleteInviteCommand {
	static responseSchema = schemas.deleteInviteCommandResponseSchema;
}

export class ListUsersCommand extends commands.ListUsersCommand {
	static responseSchema = schemas.listUsersCommandResponseSchema;
}

export class RetrieveUserCommand extends commands.RetrieveUserCommand {
	static responseSchema = schemas.retrieveUserCommandResponseSchema;
}

export class ModifyUserCommand extends commands.ModifyUserCommand {
	static responseSchema = schemas.modifyUserCommandResponseSchema;
}

export class DeleteUserCommand extends commands.DeleteUserCommand {
	static responseSchema = schemas.deleteUserCommandResponseSchema;
}

export class ListProjectsCommand extends commands.ListProjectsCommand {
	static responseSchema = schemas.listProjectsCommandResponseSchema;
}

export class CreateProjectCommand extends commands.CreateProjectCommand {
	static responseSchema = schemas.createProjectCommandResponseSchema;
}

export class RetrieveProjectCommand extends commands.RetrieveProjectCommand {
	static responseSchema = schemas.retrieveProjectCommandResponseSchema;
}

export class ModifyProjectCommand extends commands.ModifyProjectCommand {
	static responseSchema = schemas.modifyProjectCommandResponseSchema;
}

export class ArchiveProjectCommand extends commands.ArchiveProjectCommand {
	static responseSchema = schemas.archiveProjectCommandResponseSchema;
}

export class ListProjectUsersCommand extends commands.ListProjectUsersCommand {
	static responseSchema = schemas.listProjectUsersCommandResponseSchema;
}

export class CreateProjectUserCommand
	extends commands.CreateProjectUserCommand
{
	static responseSchema = schemas.createProjectUserCommandResponseSchema;
}

export class RetrieveProjectUserCommand
	extends commands.RetrieveProjectUserCommand
{
	static responseSchema = schemas.retrieveProjectUserCommandResponseSchema;
}

export class ModifyProjectUserCommand
	extends commands.ModifyProjectUserCommand
{
	static responseSchema = schemas.modifyProjectUserCommandResponseSchema;
}

export class DeleteProjectUserCommand
	extends commands.DeleteProjectUserCommand
{
	static responseSchema = schemas.deleteProjectUserCommandResponseSchema;
}

export class ListProjectServiceAccountsCommand
	extends commands.ListProjectServiceAccountsCommand
{
	static responseSchema =
		schemas.listProjectServiceAccountsCommandResponseSchema;
}

export class CreateProjectServiceAccountCommand
	extends commands.CreateProjectServiceAccountCommand
{
	static responseSchema =
		schemas.createProjectServiceAccountCommandResponseSchema;
}

export class RetrieveProjectServiceAccountCommand
	extends commands.RetrieveProjectServiceAccountCommand
{
	static responseSchema =
		schemas.retrieveProjectServiceAccountCommandResponseSchema;
}

export class DeleteProjectServiceAccountCommand
	extends commands.DeleteProjectServiceAccountCommand
{
	static responseSchema =
		schemas.deleteProjectServiceAccountCommandResponseSchema;
}

export class ListProjectApiKeysCommand
	extends commands.ListProjectApiKeysCommand
{
	static responseSchema = schemas.listProjectApiKeysCommandResponseSchema;
}

export class RetrieveProjectApiKeyCommand
	extends commands.RetrieveProjectApiKeyCommand
{
	static responseSchema = schemas.retrieveProjectApiKeyCommandResponseSchema;
}

export class DeleteProjectApiKeyCommand
	extends commands.DeleteProjectApiKeyCommand
{
	static responseSchema = schemas.deleteProjectApiKeyCommandResponseSchema;
}

export { CreateSpeechCommand } from "./commands.js";
