/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T06:12:45.230Z
 *
 */
/** eslint-disable max-classes */
import { Command, stripUndefined, jsonStringify } from "@block65/rest-client";
import type {
	CreateChatCompletionCommandInput,
	CreateChatCompletionResponse,
	CreateCompletionCommandInput,
	CreateCompletionResponse,
	CreateImageCommandInput,
	ImagesResponse,
	CreateImageEditCommandInput,
	CreateImageVariationCommandInput,
	CreateEmbeddingCommandInput,
	CreateEmbeddingResponse,
	CreateSpeechCommandInput,
	CreateTranscriptionCommandInput,
	CreateTranscriptionCommandOutput,
	CreateTranslationCommandInput,
	CreateTranslationCommandOutput,
	ListFilesCommandQuery,
	ListFilesCommandInput,
	ListFilesResponse,
	CreateFileCommandInput,
	OpenAiFile,
	DeleteFileCommandInput,
	DeleteFileResponse,
	RetrieveFileCommandInput,
	DownloadFileCommandInput,
	DownloadFileCommandOutput,
	CreateUploadCommandInput,
	Upload,
	AddUploadPartCommandInput,
	UploadPart,
	CompleteUploadCommandInput,
	CancelUploadCommandInput,
	CreateFineTuningJobCommandInput,
	FineTuningJob,
	ListPaginatedFineTuningJobsCommandQuery,
	ListPaginatedFineTuningJobsCommandInput,
	ListPaginatedFineTuningJobsResponse,
	RetrieveFineTuningJobCommandInput,
	ListFineTuningEventsCommandQuery,
	ListFineTuningEventsCommandInput,
	ListFineTuningJobEventsResponse,
	CancelFineTuningJobCommandInput,
	ListFineTuningJobCheckpointsCommandQuery,
	ListFineTuningJobCheckpointsCommandInput,
	ListFineTuningJobCheckpointsResponse,
	ListModelsCommandInput,
	ListModelsResponse,
	RetrieveModelCommandInput,
	Model,
	DeleteModelCommandInput,
	DeleteModelResponse,
	CreateModerationCommandInput,
	CreateModerationResponse,
	ListAssistantsCommandQuery,
	ListAssistantsCommandInput,
	ListAssistantsResponse,
	CreateAssistantCommandInput,
	AssistantObject,
	GetAssistantCommandInput,
	ModifyAssistantCommandInput,
	DeleteAssistantCommandInput,
	DeleteAssistantResponse,
	CreateThreadCommandInput,
	ThreadObject,
	GetThreadCommandInput,
	ModifyThreadCommandInput,
	DeleteThreadCommandInput,
	DeleteThreadResponse,
	ListMessagesCommandQuery,
	ListMessagesCommandInput,
	ListMessagesResponse,
	CreateMessageCommandInput,
	MessageObject,
	GetMessageCommandInput,
	ModifyMessageCommandInput,
	DeleteMessageCommandInput,
	DeleteMessageResponse,
	CreateThreadAndRunCommandInput,
	RunObject,
	ListRunsCommandQuery,
	ListRunsCommandInput,
	ListRunsResponse,
	CreateRunCommandQuery,
	CreateRunCommandInput,
	GetRunCommandInput,
	ModifyRunCommandInput,
	SubmitToolOuputsToRunCommandInput,
	CancelRunCommandInput,
	ListRunStepsCommandQuery,
	ListRunStepsCommandInput,
	ListRunStepsResponse,
	GetRunStepCommandQuery,
	GetRunStepCommandInput,
	RunStepObject,
	ListVectorStoresCommandQuery,
	ListVectorStoresCommandInput,
	ListVectorStoresResponse,
	CreateVectorStoreCommandInput,
	VectorStoreObject,
	GetVectorStoreCommandInput,
	ModifyVectorStoreCommandInput,
	DeleteVectorStoreCommandInput,
	DeleteVectorStoreResponse,
	ListVectorStoreFilesCommandQuery,
	ListVectorStoreFilesCommandInput,
	ListVectorStoreFilesResponse,
	CreateVectorStoreFileCommandInput,
	VectorStoreFileObject,
	GetVectorStoreFileCommandInput,
	DeleteVectorStoreFileCommandInput,
	DeleteVectorStoreFileResponse,
	CreateVectorStoreFileBatchCommandInput,
	VectorStoreFileBatchObject,
	GetVectorStoreFileBatchCommandInput,
	CancelVectorStoreFileBatchCommandInput,
	ListFilesInVectorStoreBatchCommandQuery,
	ListFilesInVectorStoreBatchCommandInput,
	CreateBatchCommandInput,
	Batch,
	ListBatchesCommandQuery,
	ListBatchesCommandInput,
	ListBatchesResponse,
	RetrieveBatchCommandInput,
	CancelBatchCommandInput,
	ListAuditLogsCommandQuery,
	ListAuditLogsCommandInput,
	ListAuditLogsResponse,
	ListInvitesCommandQuery,
	ListInvitesCommandInput,
	InviteListResponse,
	InviteUserCommandInput,
	Invite,
	RetrieveInviteCommandInput,
	DeleteInviteCommandInput,
	InviteDeleteResponse,
	ListUsersCommandQuery,
	ListUsersCommandInput,
	UserListResponse,
	RetrieveUserCommandInput,
	User,
	ModifyUserCommandInput,
	DeleteUserCommandInput,
	UserDeleteResponse,
	ListProjectsCommandQuery,
	ListProjectsCommandInput,
	ProjectListResponse,
	CreateProjectCommandInput,
	Project,
	RetrieveProjectCommandInput,
	ModifyProjectCommandInput,
	ArchiveProjectCommandInput,
	ListProjectUsersCommandQuery,
	ListProjectUsersCommandInput,
	ProjectUserListResponse,
	CreateProjectUserCommandInput,
	ProjectUser,
	RetrieveProjectUserCommandInput,
	ModifyProjectUserCommandInput,
	DeleteProjectUserCommandInput,
	ProjectUserDeleteResponse,
	ListProjectServiceAccountsCommandQuery,
	ListProjectServiceAccountsCommandInput,
	ProjectServiceAccountListResponse,
	CreateProjectServiceAccountCommandInput,
	ProjectServiceAccountCreateResponse,
	RetrieveProjectServiceAccountCommandInput,
	ProjectServiceAccount,
	DeleteProjectServiceAccountCommandInput,
	ProjectServiceAccountDeleteResponse,
	ListProjectApiKeysCommandQuery,
	ListProjectApiKeysCommandInput,
	ProjectApiKeyListResponse,
	RetrieveProjectApiKeyCommandInput,
	ProjectApiKey,
	DeleteProjectApiKeyCommandInput,
	ProjectApiKeyDeleteResponse,
} from "./types.js";

/**
 * Tagged template literal that applies encodeURIComponent to all interpolated
 * values, protecting path integrity from characters like `/` and `#`.
 * @example encodePath`/users/${userId}` // "/users/foo%2Fbar"
 */
function encodePath(
	strings: TemplateStringsArray,
	...values: string[]
): string {
	return String.raw({ raw: strings }, ...values.map(encodeURIComponent));
}

/**
 * CreateChatCompletionCommand
 *
 * @summary Creates a model response for the given chat conversation.
 */
export class CreateChatCompletionCommand extends Command<
	CreateChatCompletionCommandInput,
	CreateChatCompletionResponse
> {
	public override method = "post" as const;

	constructor(input: CreateChatCompletionCommandInput) {
		const body = input;
		super("/chat/completions", jsonStringify(body));
	}
}

/**
 * CreateCompletionCommand
 *
 * @summary Creates a completion for the provided prompt and parameters.
 */
export class CreateCompletionCommand extends Command<
	CreateCompletionCommandInput,
	CreateCompletionResponse
> {
	public override method = "post" as const;

	constructor(input: CreateCompletionCommandInput) {
		const body = input;
		super("/completions", jsonStringify(body));
	}
}

/**
 * CreateImageCommand
 *
 * @summary Creates an image given a prompt.
 */
export class CreateImageCommand extends Command<
	CreateImageCommandInput,
	ImagesResponse
> {
	public override method = "post" as const;

	constructor(input: CreateImageCommandInput) {
		const body = input;
		super("/images/generations", jsonStringify(body));
	}
}

/**
 * CreateImageEditCommand
 *
 * @summary Creates an edited or extended image given an original image and a prompt.
 */
export class CreateImageEditCommand extends Command<
	CreateImageEditCommandInput,
	ImagesResponse
> {
	public override method = "post" as const;

	constructor(input: CreateImageEditCommandInput) {
		const { body } = input;
		super("/images/edits", body);
	}
}

/**
 * CreateImageVariationCommand
 *
 * @summary Creates a variation of a given image.
 */
export class CreateImageVariationCommand extends Command<
	CreateImageVariationCommandInput,
	ImagesResponse
> {
	public override method = "post" as const;

	constructor(input: CreateImageVariationCommandInput) {
		const { body } = input;
		super("/images/variations", body);
	}
}

/**
 * CreateEmbeddingCommand
 *
 * @summary Creates an embedding vector representing the input text.
 */
export class CreateEmbeddingCommand extends Command<
	CreateEmbeddingCommandInput,
	CreateEmbeddingResponse
> {
	public override method = "post" as const;

	constructor(input: CreateEmbeddingCommandInput) {
		const body = input;
		super("/embeddings", jsonStringify(body));
	}
}

/**
 * CreateSpeechCommand
 *
 * @summary Generates audio from the input text.
 */
export class CreateSpeechCommand extends Command<
	CreateSpeechCommandInput,
	unknown
> {
	public override method = "post" as const;

	constructor(input: CreateSpeechCommandInput) {
		const body = input;
		super("/audio/speech", jsonStringify(body));
	}
}

/**
 * CreateTranscriptionCommand
 *
 * @summary Transcribes audio into the input language.
 */
export class CreateTranscriptionCommand extends Command<
	CreateTranscriptionCommandInput,
	CreateTranscriptionCommandOutput
> {
	public override method = "post" as const;

	constructor(input: CreateTranscriptionCommandInput) {
		const { body } = input;
		super("/audio/transcriptions", body);
	}
}

/**
 * CreateTranslationCommand
 *
 * @summary Translates audio into English.
 */
export class CreateTranslationCommand extends Command<
	CreateTranslationCommandInput,
	CreateTranslationCommandOutput
> {
	public override method = "post" as const;

	constructor(input: CreateTranslationCommandInput) {
		const { body } = input;
		super("/audio/translations", body);
	}
}

/**
 * ListFilesCommand
 *
 * @summary Returns a list of files that belong to the user's organization.
 */
export class ListFilesCommand extends Command<
	ListFilesCommandInput,
	ListFilesResponse,
	ListFilesCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListFilesCommandInput) {
		const { purpose } = input ?? {};
		super("/files", undefined, stripUndefined({ purpose }));
	}
}

/**
 * CreateFileCommand
 *
 * @summary Upload a file that can be used across various endpoints. Individual files
 * can be up to 512 MB, and the size of all files uploaded by one organization
 * can be up to 100 GB.
 *
 * The Assistants API supports files up to 2 million tokens and of specific
 * file types. See the [Assistants Tools guide](/docs/assistants/tools) for
 * details.
 *
 * The Fine-tuning API only supports `.jsonl` files. The input also has
 * certain required formats for fine-tuning
 * [chat](/docs/api-reference/fine-tuning/chat-input) or
 * [completions](/docs/api-reference/fine-tuning/completions-input) models.
 *
 * The Batch API only supports `.jsonl` files up to 100 MB in size. The input
 * also has a specific required
 * [format](/docs/api-reference/batch/request-input).
 *
 * Please [contact us](https://help.openai.com/) if you need to increase these
 * storage limits.
 */
export class CreateFileCommand extends Command<
	CreateFileCommandInput,
	OpenAiFile
> {
	public override method = "post" as const;

	constructor(input: CreateFileCommandInput) {
		const { body } = input;
		super("/files", body);
	}
}

/**
 * DeleteFileCommand
 *
 * @summary Delete a file.
 */
export class DeleteFileCommand extends Command<
	DeleteFileCommandInput,
	DeleteFileResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteFileCommandInput) {
		const { file_id } = input;
		super(encodePath`/files/${file_id}`);
	}
}

/**
 * RetrieveFileCommand
 *
 * @summary Returns information about a specific file.
 */
export class RetrieveFileCommand extends Command<
	RetrieveFileCommandInput,
	OpenAiFile
> {
	public override method = "get" as const;

	constructor(input: RetrieveFileCommandInput) {
		const { file_id } = input;
		super(encodePath`/files/${file_id}`);
	}
}

/**
 * DownloadFileCommand
 *
 * @summary Returns the contents of the specified file.
 */
export class DownloadFileCommand extends Command<
	DownloadFileCommandInput,
	DownloadFileCommandOutput
> {
	public override method = "get" as const;

	constructor(input: DownloadFileCommandInput) {
		const { file_id } = input;
		super(encodePath`/files/${file_id}/content`);
	}
}

/**
 * CreateUploadCommand
 *
 * @summary Creates an intermediate [Upload](/docs/api-reference/uploads/object) object
 * that you can add [Parts](/docs/api-reference/uploads/part-object) to.
 * Currently, an Upload can accept at most 8 GB in total and expires after an
 * hour after you create it.
 *
 * Once you complete the Upload, we will create a
 * [File](/docs/api-reference/files/object) object that contains all the parts
 * you uploaded. This File is usable in the rest of our platform as a regular
 * File object.
 *
 * For certain `purpose`s, the correct `mime_type` must be specified. Please
 * refer to documentation for the supported MIME types for your use case:
 * - [Assistants](/docs/assistants/tools/file-search/supported-files)
 *
 * For guidance on the proper filename extensions for each purpose, please
 * follow the documentation on [creating a
 * File](/docs/api-reference/files/create).
 */
export class CreateUploadCommand extends Command<
	CreateUploadCommandInput,
	Upload
> {
	public override method = "post" as const;

	constructor(input: CreateUploadCommandInput) {
		const body = input;
		super("/uploads", jsonStringify(body));
	}
}

/**
 * AddUploadPartCommand
 *
 * @summary Adds a [Part](/docs/api-reference/uploads/part-object) to an
 * [Upload](/docs/api-reference/uploads/object) object. A Part represents a
 * chunk of bytes from the file you are trying to upload.
 *
 * Each Part can be at most 64 MB, and you can add Parts until you hit the
 * Upload maximum of 8 GB.
 *
 * It is possible to add multiple Parts in parallel. You can decide the
 * intended order of the Parts when you [complete the
 * Upload](/docs/api-reference/uploads/complete).
 */
export class AddUploadPartCommand extends Command<
	AddUploadPartCommandInput,
	UploadPart
> {
	public override method = "post" as const;

	constructor(input: AddUploadPartCommandInput) {
		const { upload_id, body } = input;
		super(encodePath`/uploads/${upload_id}/parts`, body);
	}
}

/**
 * CompleteUploadCommand
 *
 * @summary Completes the [Upload](/docs/api-reference/uploads/object).
 *
 * Within the returned Upload object, there is a nested
 * [File](/docs/api-reference/files/object) object that is ready to use in the
 * rest of the platform.
 *
 * You can specify the order of the Parts by passing in an ordered list of the
 * Part IDs.
 *
 * The number of bytes uploaded upon completion must match the number of bytes
 * initially specified when creating the Upload object. No Parts may be added
 * after an Upload is completed.
 */
export class CompleteUploadCommand extends Command<
	CompleteUploadCommandInput,
	Upload
> {
	public override method = "post" as const;

	constructor(input: CompleteUploadCommandInput) {
		const { upload_id, ...body } = input;
		super(encodePath`/uploads/${upload_id}/complete`, jsonStringify(body));
	}
}

/**
 * CancelUploadCommand
 *
 * @summary Cancels the Upload. No Parts may be added after an Upload is cancelled.
 */
export class CancelUploadCommand extends Command<
	CancelUploadCommandInput,
	Upload
> {
	public override method = "post" as const;

	constructor(input: CancelUploadCommandInput) {
		const { upload_id } = input;
		super(encodePath`/uploads/${upload_id}/cancel`);
	}
}

/**
 * CreateFineTuningJobCommand
 *
 * @summary Creates a fine-tuning job which begins the process of creating a new model
 * from a given dataset.
 *
 * Response includes details of the enqueued job including job status and the
 * name of the fine-tuned models once complete.
 *
 * [Learn more about fine-tuning](/docs/guides/fine-tuning)
 */
export class CreateFineTuningJobCommand extends Command<
	CreateFineTuningJobCommandInput,
	FineTuningJob
> {
	public override method = "post" as const;

	constructor(input: CreateFineTuningJobCommandInput) {
		const body = input;
		super("/fine_tuning/jobs", jsonStringify(body));
	}
}

/**
 * ListPaginatedFineTuningJobsCommand
 *
 * @summary List your organization's fine-tuning jobs
 */
export class ListPaginatedFineTuningJobsCommand extends Command<
	ListPaginatedFineTuningJobsCommandInput,
	ListPaginatedFineTuningJobsResponse,
	ListPaginatedFineTuningJobsCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListPaginatedFineTuningJobsCommandInput) {
		const { after, limit } = input ?? {};
		super("/fine_tuning/jobs", undefined, stripUndefined({ after, limit }));
	}
}

/**
 * RetrieveFineTuningJobCommand
 *
 * @summary Get info about a fine-tuning job.
 *
 * [Learn more about fine-tuning](/docs/guides/fine-tuning)
 */
export class RetrieveFineTuningJobCommand extends Command<
	RetrieveFineTuningJobCommandInput,
	FineTuningJob
> {
	public override method = "get" as const;

	constructor(input: RetrieveFineTuningJobCommandInput) {
		const { fine_tuning_job_id } = input;
		super(encodePath`/fine_tuning/jobs/${fine_tuning_job_id}`);
	}
}

/**
 * ListFineTuningEventsCommand
 *
 * @summary Get status updates for a fine-tuning job.
 */
export class ListFineTuningEventsCommand extends Command<
	ListFineTuningEventsCommandInput,
	ListFineTuningJobEventsResponse,
	ListFineTuningEventsCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListFineTuningEventsCommandInput) {
		const { fine_tuning_job_id, after, limit } = input;
		super(
			encodePath`/fine_tuning/jobs/${fine_tuning_job_id}/events`,
			undefined,
			stripUndefined({ after, limit }),
		);
	}
}

/**
 * CancelFineTuningJobCommand
 *
 * @summary Immediately cancel a fine-tune job.
 */
export class CancelFineTuningJobCommand extends Command<
	CancelFineTuningJobCommandInput,
	FineTuningJob
> {
	public override method = "post" as const;

	constructor(input: CancelFineTuningJobCommandInput) {
		const { fine_tuning_job_id } = input;
		super(encodePath`/fine_tuning/jobs/${fine_tuning_job_id}/cancel`);
	}
}

/**
 * ListFineTuningJobCheckpointsCommand
 *
 * @summary List checkpoints for a fine-tuning job.
 */
export class ListFineTuningJobCheckpointsCommand extends Command<
	ListFineTuningJobCheckpointsCommandInput,
	ListFineTuningJobCheckpointsResponse,
	ListFineTuningJobCheckpointsCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListFineTuningJobCheckpointsCommandInput) {
		const { fine_tuning_job_id, after, limit } = input;
		super(
			encodePath`/fine_tuning/jobs/${fine_tuning_job_id}/checkpoints`,
			undefined,
			stripUndefined({ after, limit }),
		);
	}
}

/**
 * ListModelsCommand
 *
 * @summary Lists the currently available models, and provides basic information about
 * each one such as the owner and availability.
 */
export class ListModelsCommand extends Command<
	ListModelsCommandInput,
	ListModelsResponse
> {
	public override method = "get" as const;

	constructor() {
		super("/models");
	}
}

/**
 * RetrieveModelCommand
 *
 * @summary Retrieves a model instance, providing basic information about the model
 * such as the owner and permissioning.
 */
export class RetrieveModelCommand extends Command<
	RetrieveModelCommandInput,
	Model
> {
	public override method = "get" as const;

	constructor(input: RetrieveModelCommandInput) {
		const { model } = input;
		super(encodePath`/models/${model}`);
	}
}

/**
 * DeleteModelCommand
 *
 * @summary Delete a fine-tuned model. You must have the Owner role in your
 * organization to delete a model.
 */
export class DeleteModelCommand extends Command<
	DeleteModelCommandInput,
	DeleteModelResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteModelCommandInput) {
		const { model } = input;
		super(encodePath`/models/${model}`);
	}
}

/**
 * CreateModerationCommand
 *
 * @summary Classifies if text and/or image inputs are potentially harmful. Learn
 * more in the [moderation guide](/docs/guides/moderation).
 */
export class CreateModerationCommand extends Command<
	CreateModerationCommandInput,
	CreateModerationResponse
> {
	public override method = "post" as const;

	constructor(input: CreateModerationCommandInput) {
		const body = input;
		super("/moderations", jsonStringify(body));
	}
}

/**
 * ListAssistantsCommand
 *
 * @summary Returns a list of assistants.
 */
export class ListAssistantsCommand extends Command<
	ListAssistantsCommandInput,
	ListAssistantsResponse,
	ListAssistantsCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListAssistantsCommandInput) {
		const { limit, order, after, before } = input ?? {};
		super(
			"/assistants",
			undefined,
			stripUndefined({ limit, order, after, before }),
		);
	}
}

/**
 * CreateAssistantCommand
 *
 * @summary Create an assistant with a model and instructions.
 */
export class CreateAssistantCommand extends Command<
	CreateAssistantCommandInput,
	AssistantObject
> {
	public override method = "post" as const;

	constructor(input: CreateAssistantCommandInput) {
		const body = input;
		super("/assistants", jsonStringify(body));
	}
}

/**
 * GetAssistantCommand
 *
 * @summary Retrieves an assistant.
 */
export class GetAssistantCommand extends Command<
	GetAssistantCommandInput,
	AssistantObject
> {
	public override method = "get" as const;

	constructor(input: GetAssistantCommandInput) {
		const { assistant_id } = input;
		super(encodePath`/assistants/${assistant_id}`);
	}
}

/**
 * ModifyAssistantCommand
 *
 * @summary Modifies an assistant.
 */
export class ModifyAssistantCommand extends Command<
	ModifyAssistantCommandInput,
	AssistantObject
> {
	public override method = "post" as const;

	constructor(input: ModifyAssistantCommandInput) {
		const { assistant_id, ...body } = input;
		super(encodePath`/assistants/${assistant_id}`, jsonStringify(body));
	}
}

/**
 * DeleteAssistantCommand
 *
 * @summary Delete an assistant.
 */
export class DeleteAssistantCommand extends Command<
	DeleteAssistantCommandInput,
	DeleteAssistantResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteAssistantCommandInput) {
		const { assistant_id } = input;
		super(encodePath`/assistants/${assistant_id}`);
	}
}

/**
 * CreateThreadCommand
 *
 * @summary Create a thread.
 */
export class CreateThreadCommand extends Command<
	CreateThreadCommandInput,
	ThreadObject
> {
	public override method = "post" as const;

	constructor(input: CreateThreadCommandInput) {
		const body = input;
		super("/threads", jsonStringify(body));
	}
}

/**
 * GetThreadCommand
 *
 * @summary Retrieves a thread.
 */
export class GetThreadCommand extends Command<
	GetThreadCommandInput,
	ThreadObject
> {
	public override method = "get" as const;

	constructor(input: GetThreadCommandInput) {
		const { thread_id } = input;
		super(encodePath`/threads/${thread_id}`);
	}
}

/**
 * ModifyThreadCommand
 *
 * @summary Modifies a thread.
 */
export class ModifyThreadCommand extends Command<
	ModifyThreadCommandInput,
	ThreadObject
> {
	public override method = "post" as const;

	constructor(input: ModifyThreadCommandInput) {
		const { thread_id, ...body } = input;
		super(encodePath`/threads/${thread_id}`, jsonStringify(body));
	}
}

/**
 * DeleteThreadCommand
 *
 * @summary Delete a thread.
 */
export class DeleteThreadCommand extends Command<
	DeleteThreadCommandInput,
	DeleteThreadResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteThreadCommandInput) {
		const { thread_id } = input;
		super(encodePath`/threads/${thread_id}`);
	}
}

/**
 * ListMessagesCommand
 *
 * @summary Returns a list of messages for a given thread.
 */
export class ListMessagesCommand extends Command<
	ListMessagesCommandInput,
	ListMessagesResponse,
	ListMessagesCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListMessagesCommandInput) {
		const { thread_id, limit, order, after, before, run_id } = input;
		super(
			encodePath`/threads/${thread_id}/messages`,
			undefined,
			stripUndefined({ limit, order, after, before, run_id }),
		);
	}
}

/**
 * CreateMessageCommand
 *
 * @summary Create a message.
 */
export class CreateMessageCommand extends Command<
	CreateMessageCommandInput,
	MessageObject
> {
	public override method = "post" as const;

	constructor(input: CreateMessageCommandInput) {
		const { thread_id, ...body } = input;
		super(encodePath`/threads/${thread_id}/messages`, jsonStringify(body));
	}
}

/**
 * GetMessageCommand
 *
 * @summary Retrieve a message.
 */
export class GetMessageCommand extends Command<
	GetMessageCommandInput,
	MessageObject
> {
	public override method = "get" as const;

	constructor(input: GetMessageCommandInput) {
		const { thread_id, message_id } = input;
		super(encodePath`/threads/${thread_id}/messages/${message_id}`);
	}
}

/**
 * ModifyMessageCommand
 *
 * @summary Modifies a message.
 */
export class ModifyMessageCommand extends Command<
	ModifyMessageCommandInput,
	MessageObject
> {
	public override method = "post" as const;

	constructor(input: ModifyMessageCommandInput) {
		const { thread_id, message_id, ...body } = input;
		super(
			encodePath`/threads/${thread_id}/messages/${message_id}`,
			jsonStringify(body),
		);
	}
}

/**
 * DeleteMessageCommand
 *
 * @summary Deletes a message.
 */
export class DeleteMessageCommand extends Command<
	DeleteMessageCommandInput,
	DeleteMessageResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteMessageCommandInput) {
		const { thread_id, message_id } = input;
		super(encodePath`/threads/${thread_id}/messages/${message_id}`);
	}
}

/**
 * CreateThreadAndRunCommand
 *
 * @summary Create a thread and run it in one request.
 */
export class CreateThreadAndRunCommand extends Command<
	CreateThreadAndRunCommandInput,
	RunObject
> {
	public override method = "post" as const;

	constructor(input: CreateThreadAndRunCommandInput) {
		const body = input;
		super("/threads/runs", jsonStringify(body));
	}
}

/**
 * ListRunsCommand
 *
 * @summary Returns a list of runs belonging to a thread.
 */
export class ListRunsCommand extends Command<
	ListRunsCommandInput,
	ListRunsResponse,
	ListRunsCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListRunsCommandInput) {
		const { thread_id, limit, order, after, before } = input;
		super(
			encodePath`/threads/${thread_id}/runs`,
			undefined,
			stripUndefined({ limit, order, after, before }),
		);
	}
}

/**
 * CreateRunCommand
 *
 * @summary Create a run.
 */
export class CreateRunCommand extends Command<
	CreateRunCommandInput,
	RunObject,
	CreateRunCommandQuery
> {
	public override method = "post" as const;

	constructor(input: CreateRunCommandInput) {
		const { thread_id, include, ...body } = input;
		super(
			encodePath`/threads/${thread_id}/runs`,
			jsonStringify(body),
			stripUndefined({ include }),
		);
	}
}

/**
 * GetRunCommand
 *
 * @summary Retrieves a run.
 */
export class GetRunCommand extends Command<GetRunCommandInput, RunObject> {
	public override method = "get" as const;

	constructor(input: GetRunCommandInput) {
		const { thread_id, run_id } = input;
		super(encodePath`/threads/${thread_id}/runs/${run_id}`);
	}
}

/**
 * ModifyRunCommand
 *
 * @summary Modifies a run.
 */
export class ModifyRunCommand extends Command<
	ModifyRunCommandInput,
	RunObject
> {
	public override method = "post" as const;

	constructor(input: ModifyRunCommandInput) {
		const { thread_id, run_id, ...body } = input;
		super(
			encodePath`/threads/${thread_id}/runs/${run_id}`,
			jsonStringify(body),
		);
	}
}

/**
 * SubmitToolOuputsToRunCommand
 *
 * @summary When a run has the `status: "requires_action"` and `required_action.type`
 * is `submit_tool_outputs`, this endpoint can be used to submit the outputs
 * from the tool calls once they're all completed. All outputs must be
 * submitted in a single request.
 */
export class SubmitToolOuputsToRunCommand extends Command<
	SubmitToolOuputsToRunCommandInput,
	RunObject
> {
	public override method = "post" as const;

	constructor(input: SubmitToolOuputsToRunCommandInput) {
		const { thread_id, run_id, ...body } = input;
		super(
			encodePath`/threads/${thread_id}/runs/${run_id}/submit_tool_outputs`,
			jsonStringify(body),
		);
	}
}

/**
 * CancelRunCommand
 *
 * @summary Cancels a run that is `in_progress`.
 */
export class CancelRunCommand extends Command<
	CancelRunCommandInput,
	RunObject
> {
	public override method = "post" as const;

	constructor(input: CancelRunCommandInput) {
		const { thread_id, run_id } = input;
		super(encodePath`/threads/${thread_id}/runs/${run_id}/cancel`);
	}
}

/**
 * ListRunStepsCommand
 *
 * @summary Returns a list of run steps belonging to a run.
 */
export class ListRunStepsCommand extends Command<
	ListRunStepsCommandInput,
	ListRunStepsResponse,
	ListRunStepsCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListRunStepsCommandInput) {
		const { thread_id, run_id, limit, order, after, before, include } = input;
		super(
			encodePath`/threads/${thread_id}/runs/${run_id}/steps`,
			undefined,
			stripUndefined({ limit, order, after, before, include }),
		);
	}
}

/**
 * GetRunStepCommand
 *
 * @summary Retrieves a run step.
 */
export class GetRunStepCommand extends Command<
	GetRunStepCommandInput,
	RunStepObject,
	GetRunStepCommandQuery
> {
	public override method = "get" as const;

	constructor(input: GetRunStepCommandInput) {
		const { thread_id, run_id, step_id, include } = input;
		super(
			encodePath`/threads/${thread_id}/runs/${run_id}/steps/${step_id}`,
			undefined,
			stripUndefined({ include }),
		);
	}
}

/**
 * ListVectorStoresCommand
 *
 * @summary Returns a list of vector stores.
 */
export class ListVectorStoresCommand extends Command<
	ListVectorStoresCommandInput,
	ListVectorStoresResponse,
	ListVectorStoresCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListVectorStoresCommandInput) {
		const { limit, order, after, before } = input ?? {};
		super(
			"/vector_stores",
			undefined,
			stripUndefined({ limit, order, after, before }),
		);
	}
}

/**
 * CreateVectorStoreCommand
 *
 * @summary Create a vector store.
 */
export class CreateVectorStoreCommand extends Command<
	CreateVectorStoreCommandInput,
	VectorStoreObject
> {
	public override method = "post" as const;

	constructor(input: CreateVectorStoreCommandInput) {
		const body = input;
		super("/vector_stores", jsonStringify(body));
	}
}

/**
 * GetVectorStoreCommand
 *
 * @summary Retrieves a vector store.
 */
export class GetVectorStoreCommand extends Command<
	GetVectorStoreCommandInput,
	VectorStoreObject
> {
	public override method = "get" as const;

	constructor(input: GetVectorStoreCommandInput) {
		const { vector_store_id } = input;
		super(encodePath`/vector_stores/${vector_store_id}`);
	}
}

/**
 * ModifyVectorStoreCommand
 *
 * @summary Modifies a vector store.
 */
export class ModifyVectorStoreCommand extends Command<
	ModifyVectorStoreCommandInput,
	VectorStoreObject
> {
	public override method = "post" as const;

	constructor(input: ModifyVectorStoreCommandInput) {
		const { vector_store_id, ...body } = input;
		super(encodePath`/vector_stores/${vector_store_id}`, jsonStringify(body));
	}
}

/**
 * DeleteVectorStoreCommand
 *
 * @summary Delete a vector store.
 */
export class DeleteVectorStoreCommand extends Command<
	DeleteVectorStoreCommandInput,
	DeleteVectorStoreResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteVectorStoreCommandInput) {
		const { vector_store_id } = input;
		super(encodePath`/vector_stores/${vector_store_id}`);
	}
}

/**
 * ListVectorStoreFilesCommand
 *
 * @summary Returns a list of vector store files.
 */
export class ListVectorStoreFilesCommand extends Command<
	ListVectorStoreFilesCommandInput,
	ListVectorStoreFilesResponse,
	ListVectorStoreFilesCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListVectorStoreFilesCommandInput) {
		const { vector_store_id, limit, order, after, before, filter } = input;
		super(
			encodePath`/vector_stores/${vector_store_id}/files`,
			undefined,
			stripUndefined({ limit, order, after, before, filter }),
		);
	}
}

/**
 * CreateVectorStoreFileCommand
 *
 * @summary Create a vector store file by attaching a [File](/docs/api-reference/files)
 * to a [vector store](/docs/api-reference/vector-stores/object).
 */
export class CreateVectorStoreFileCommand extends Command<
	CreateVectorStoreFileCommandInput,
	VectorStoreFileObject
> {
	public override method = "post" as const;

	constructor(input: CreateVectorStoreFileCommandInput) {
		const { vector_store_id, ...body } = input;
		super(
			encodePath`/vector_stores/${vector_store_id}/files`,
			jsonStringify(body),
		);
	}
}

/**
 * GetVectorStoreFileCommand
 *
 * @summary Retrieves a vector store file.
 */
export class GetVectorStoreFileCommand extends Command<
	GetVectorStoreFileCommandInput,
	VectorStoreFileObject
> {
	public override method = "get" as const;

	constructor(input: GetVectorStoreFileCommandInput) {
		const { vector_store_id, file_id } = input;
		super(encodePath`/vector_stores/${vector_store_id}/files/${file_id}`);
	}
}

/**
 * DeleteVectorStoreFileCommand
 *
 * @summary Delete a vector store file. This will remove the file from the vector store
 * but the file itself will not be deleted. To delete the file, use the
 * [delete file](/docs/api-reference/files/delete) endpoint.
 */
export class DeleteVectorStoreFileCommand extends Command<
	DeleteVectorStoreFileCommandInput,
	DeleteVectorStoreFileResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteVectorStoreFileCommandInput) {
		const { vector_store_id, file_id } = input;
		super(encodePath`/vector_stores/${vector_store_id}/files/${file_id}`);
	}
}

/**
 * CreateVectorStoreFileBatchCommand
 *
 * @summary Create a vector store file batch.
 */
export class CreateVectorStoreFileBatchCommand extends Command<
	CreateVectorStoreFileBatchCommandInput,
	VectorStoreFileBatchObject
> {
	public override method = "post" as const;

	constructor(input: CreateVectorStoreFileBatchCommandInput) {
		const { vector_store_id, ...body } = input;
		super(
			encodePath`/vector_stores/${vector_store_id}/file_batches`,
			jsonStringify(body),
		);
	}
}

/**
 * GetVectorStoreFileBatchCommand
 *
 * @summary Retrieves a vector store file batch.
 */
export class GetVectorStoreFileBatchCommand extends Command<
	GetVectorStoreFileBatchCommandInput,
	VectorStoreFileBatchObject
> {
	public override method = "get" as const;

	constructor(input: GetVectorStoreFileBatchCommandInput) {
		const { vector_store_id, batch_id } = input;
		super(
			encodePath`/vector_stores/${vector_store_id}/file_batches/${batch_id}`,
		);
	}
}

/**
 * CancelVectorStoreFileBatchCommand
 *
 * @summary Cancel a vector store file batch. This attempts to cancel the processing of
 * files in this batch as soon as possible.
 */
export class CancelVectorStoreFileBatchCommand extends Command<
	CancelVectorStoreFileBatchCommandInput,
	VectorStoreFileBatchObject
> {
	public override method = "post" as const;

	constructor(input: CancelVectorStoreFileBatchCommandInput) {
		const { vector_store_id, batch_id } = input;
		super(
			encodePath`/vector_stores/${vector_store_id}/file_batches/${batch_id}/cancel`,
		);
	}
}

/**
 * ListFilesInVectorStoreBatchCommand
 *
 * @summary Returns a list of vector store files in a batch.
 */
export class ListFilesInVectorStoreBatchCommand extends Command<
	ListFilesInVectorStoreBatchCommandInput,
	ListVectorStoreFilesResponse,
	ListFilesInVectorStoreBatchCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListFilesInVectorStoreBatchCommandInput) {
		const { vector_store_id, batch_id, limit, order, after, before, filter } =
			input;
		super(
			encodePath`/vector_stores/${vector_store_id}/file_batches/${batch_id}/files`,
			undefined,
			stripUndefined({ limit, order, after, before, filter }),
		);
	}
}

/**
 * CreateBatchCommand
 *
 * @summary Creates and executes a batch from an uploaded file of requests
 */
export class CreateBatchCommand extends Command<
	CreateBatchCommandInput,
	Batch
> {
	public override method = "post" as const;

	constructor(input: CreateBatchCommandInput) {
		const body = input;
		super("/batches", jsonStringify(body));
	}
}

/**
 * ListBatchesCommand
 *
 * @summary List your organization's batches.
 */
export class ListBatchesCommand extends Command<
	ListBatchesCommandInput,
	ListBatchesResponse,
	ListBatchesCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListBatchesCommandInput) {
		const { after, limit } = input ?? {};
		super("/batches", undefined, stripUndefined({ after, limit }));
	}
}

/**
 * RetrieveBatchCommand
 *
 * @summary Retrieves a batch.
 */
export class RetrieveBatchCommand extends Command<
	RetrieveBatchCommandInput,
	Batch
> {
	public override method = "get" as const;

	constructor(input: RetrieveBatchCommandInput) {
		const { batch_id } = input;
		super(encodePath`/batches/${batch_id}`);
	}
}

/**
 * CancelBatchCommand
 *
 * @summary Cancels an in-progress batch. The batch will be in status `cancelling` for
 * up to 10 minutes, before changing to `cancelled`, where it will have
 * partial results (if any) available in the output file.
 */
export class CancelBatchCommand extends Command<
	CancelBatchCommandInput,
	Batch
> {
	public override method = "post" as const;

	constructor(input: CancelBatchCommandInput) {
		const { batch_id } = input;
		super(encodePath`/batches/${batch_id}/cancel`);
	}
}

/**
 * ListAuditLogsCommand
 *
 * @summary List user actions and configuration changes within this organization.
 */
export class ListAuditLogsCommand extends Command<
	ListAuditLogsCommandInput,
	ListAuditLogsResponse,
	ListAuditLogsCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListAuditLogsCommandInput) {
		const {
			effective_at,
			project_ids,
			event_types,
			actor_ids,
			actor_emails,
			resource_ids,
			limit,
			after,
			before,
		} = input ?? {};
		super(
			"/organization/audit_logs",
			undefined,
			stripUndefined({
				effective_at,
				project_ids,
				event_types,
				actor_ids,
				actor_emails,
				resource_ids,
				limit,
				after,
				before,
			}),
		);
	}
}

/**
 * ListInvitesCommand
 *
 * @summary Returns a list of invites in the organization.
 */
export class ListInvitesCommand extends Command<
	ListInvitesCommandInput,
	InviteListResponse,
	ListInvitesCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListInvitesCommandInput) {
		const { limit, after } = input ?? {};
		super("/organization/invites", undefined, stripUndefined({ limit, after }));
	}
}

/**
 * InviteUserCommand
 *
 * @summary Create an invite for a user to the organization. The invite must be
 * accepted by the user before they have access to the organization.
 */
export class InviteUserCommand extends Command<InviteUserCommandInput, Invite> {
	public override method = "post" as const;

	constructor(input: InviteUserCommandInput) {
		const body = input;
		super("/organization/invites", jsonStringify(body));
	}
}

/**
 * RetrieveInviteCommand
 *
 * @summary Retrieves an invite.
 */
export class RetrieveInviteCommand extends Command<
	RetrieveInviteCommandInput,
	Invite
> {
	public override method = "get" as const;

	constructor(input: RetrieveInviteCommandInput) {
		const { invite_id } = input;
		super(encodePath`/organization/invites/${invite_id}`);
	}
}

/**
 * DeleteInviteCommand
 *
 * @summary Delete an invite. If the invite has already been accepted, it cannot be
 * deleted.
 */
export class DeleteInviteCommand extends Command<
	DeleteInviteCommandInput,
	InviteDeleteResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteInviteCommandInput) {
		const { invite_id } = input;
		super(encodePath`/organization/invites/${invite_id}`);
	}
}

/**
 * ListUsersCommand
 *
 * @summary Lists all of the users in the organization.
 */
export class ListUsersCommand extends Command<
	ListUsersCommandInput,
	UserListResponse,
	ListUsersCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListUsersCommandInput) {
		const { limit, after } = input ?? {};
		super("/organization/users", undefined, stripUndefined({ limit, after }));
	}
}

/**
 * RetrieveUserCommand
 *
 * @summary Retrieves a user by their identifier.
 */
export class RetrieveUserCommand extends Command<
	RetrieveUserCommandInput,
	User
> {
	public override method = "get" as const;

	constructor(input: RetrieveUserCommandInput) {
		const { user_id } = input;
		super(encodePath`/organization/users/${user_id}`);
	}
}

/**
 * ModifyUserCommand
 *
 * @summary Modifies a user's role in the organization.
 */
export class ModifyUserCommand extends Command<ModifyUserCommandInput, User> {
	public override method = "post" as const;

	constructor(input: ModifyUserCommandInput) {
		const { user_id, ...body } = input;
		super(encodePath`/organization/users/${user_id}`, jsonStringify(body));
	}
}

/**
 * DeleteUserCommand
 *
 * @summary Deletes a user from the organization.
 */
export class DeleteUserCommand extends Command<
	DeleteUserCommandInput,
	UserDeleteResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteUserCommandInput) {
		const { user_id } = input;
		super(encodePath`/organization/users/${user_id}`);
	}
}

/**
 * ListProjectsCommand
 *
 * @summary Returns a list of projects.
 */
export class ListProjectsCommand extends Command<
	ListProjectsCommandInput,
	ProjectListResponse,
	ListProjectsCommandQuery
> {
	public override method = "get" as const;

	constructor(input?: ListProjectsCommandInput) {
		const { limit, after, include_archived } = input ?? {};
		super(
			"/organization/projects",
			undefined,
			stripUndefined({ limit, after, include_archived }),
		);
	}
}

/**
 * CreateProjectCommand
 *
 * @summary Create a new project in the organization. Projects can be created and
 * archived, but cannot be deleted.
 */
export class CreateProjectCommand extends Command<
	CreateProjectCommandInput,
	Project
> {
	public override method = "post" as const;

	constructor(input: CreateProjectCommandInput) {
		const body = input;
		super("/organization/projects", jsonStringify(body));
	}
}

/**
 * RetrieveProjectCommand
 *
 * @summary Retrieves a project.
 */
export class RetrieveProjectCommand extends Command<
	RetrieveProjectCommandInput,
	Project
> {
	public override method = "get" as const;

	constructor(input: RetrieveProjectCommandInput) {
		const { project_id } = input;
		super(encodePath`/organization/projects/${project_id}`);
	}
}

/**
 * ModifyProjectCommand
 *
 * @summary Modifies a project in the organization.
 */
export class ModifyProjectCommand extends Command<
	ModifyProjectCommandInput,
	Project
> {
	public override method = "post" as const;

	constructor(input: ModifyProjectCommandInput) {
		const { project_id, ...body } = input;
		super(
			encodePath`/organization/projects/${project_id}`,
			jsonStringify(body),
		);
	}
}

/**
 * ArchiveProjectCommand
 *
 * @summary Archives a project in the organization. Archived projects cannot be used or
 * updated.
 */
export class ArchiveProjectCommand extends Command<
	ArchiveProjectCommandInput,
	Project
> {
	public override method = "post" as const;

	constructor(input: ArchiveProjectCommandInput) {
		const { project_id } = input;
		super(encodePath`/organization/projects/${project_id}/archive`);
	}
}

/**
 * ListProjectUsersCommand
 *
 * @summary Returns a list of users in the project.
 */
export class ListProjectUsersCommand extends Command<
	ListProjectUsersCommandInput,
	ProjectUserListResponse,
	ListProjectUsersCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListProjectUsersCommandInput) {
		const { project_id, limit, after } = input;
		super(
			encodePath`/organization/projects/${project_id}/users`,
			undefined,
			stripUndefined({ limit, after }),
		);
	}
}

/**
 * CreateProjectUserCommand
 *
 * @summary Adds a user to the project. Users must already be members of the
 * organization to be added to a project.
 */
export class CreateProjectUserCommand extends Command<
	CreateProjectUserCommandInput,
	ProjectUser
> {
	public override method = "post" as const;

	constructor(input: CreateProjectUserCommandInput) {
		const { project_id, ...body } = input;
		super(
			encodePath`/organization/projects/${project_id}/users`,
			jsonStringify(body),
		);
	}
}

/**
 * RetrieveProjectUserCommand
 *
 * @summary Retrieves a user in the project.
 */
export class RetrieveProjectUserCommand extends Command<
	RetrieveProjectUserCommandInput,
	ProjectUser
> {
	public override method = "get" as const;

	constructor(input: RetrieveProjectUserCommandInput) {
		const { project_id, user_id } = input;
		super(encodePath`/organization/projects/${project_id}/users/${user_id}`);
	}
}

/**
 * ModifyProjectUserCommand
 *
 * @summary Modifies a user's role in the project.
 */
export class ModifyProjectUserCommand extends Command<
	ModifyProjectUserCommandInput,
	ProjectUser
> {
	public override method = "post" as const;

	constructor(input: ModifyProjectUserCommandInput) {
		const { project_id, user_id, ...body } = input;
		super(
			encodePath`/organization/projects/${project_id}/users/${user_id}`,
			jsonStringify(body),
		);
	}
}

/**
 * DeleteProjectUserCommand
 *
 * @summary Deletes a user from the project.
 */
export class DeleteProjectUserCommand extends Command<
	DeleteProjectUserCommandInput,
	ProjectUserDeleteResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteProjectUserCommandInput) {
		const { project_id, user_id } = input;
		super(encodePath`/organization/projects/${project_id}/users/${user_id}`);
	}
}

/**
 * ListProjectServiceAccountsCommand
 *
 * @summary Returns a list of service accounts in the project.
 */
export class ListProjectServiceAccountsCommand extends Command<
	ListProjectServiceAccountsCommandInput,
	ProjectServiceAccountListResponse,
	ListProjectServiceAccountsCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListProjectServiceAccountsCommandInput) {
		const { project_id, limit, after } = input;
		super(
			encodePath`/organization/projects/${project_id}/service_accounts`,
			undefined,
			stripUndefined({ limit, after }),
		);
	}
}

/**
 * CreateProjectServiceAccountCommand
 *
 * @summary Creates a new service account in the project. This also returns an
 * unredacted API key for the service account.
 */
export class CreateProjectServiceAccountCommand extends Command<
	CreateProjectServiceAccountCommandInput,
	ProjectServiceAccountCreateResponse
> {
	public override method = "post" as const;

	constructor(input: CreateProjectServiceAccountCommandInput) {
		const { project_id, ...body } = input;
		super(
			encodePath`/organization/projects/${project_id}/service_accounts`,
			jsonStringify(body),
		);
	}
}

/**
 * RetrieveProjectServiceAccountCommand
 *
 * @summary Retrieves a service account in the project.
 */
export class RetrieveProjectServiceAccountCommand extends Command<
	RetrieveProjectServiceAccountCommandInput,
	ProjectServiceAccount
> {
	public override method = "get" as const;

	constructor(input: RetrieveProjectServiceAccountCommandInput) {
		const { project_id, service_account_id } = input;
		super(
			encodePath`/organization/projects/${project_id}/service_accounts/${service_account_id}`,
		);
	}
}

/**
 * DeleteProjectServiceAccountCommand
 *
 * @summary Deletes a service account from the project.
 */
export class DeleteProjectServiceAccountCommand extends Command<
	DeleteProjectServiceAccountCommandInput,
	ProjectServiceAccountDeleteResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteProjectServiceAccountCommandInput) {
		const { project_id, service_account_id } = input;
		super(
			encodePath`/organization/projects/${project_id}/service_accounts/${service_account_id}`,
		);
	}
}

/**
 * ListProjectApiKeysCommand
 *
 * @summary Returns a list of API keys in the project.
 */
export class ListProjectApiKeysCommand extends Command<
	ListProjectApiKeysCommandInput,
	ProjectApiKeyListResponse,
	ListProjectApiKeysCommandQuery
> {
	public override method = "get" as const;

	constructor(input: ListProjectApiKeysCommandInput) {
		const { project_id, limit, after } = input;
		super(
			encodePath`/organization/projects/${project_id}/api_keys`,
			undefined,
			stripUndefined({ limit, after }),
		);
	}
}

/**
 * RetrieveProjectApiKeyCommand
 *
 * @summary Retrieves an API key in the project.
 */
export class RetrieveProjectApiKeyCommand extends Command<
	RetrieveProjectApiKeyCommandInput,
	ProjectApiKey
> {
	public override method = "get" as const;

	constructor(input: RetrieveProjectApiKeyCommandInput) {
		const { project_id, key_id } = input;
		super(encodePath`/organization/projects/${project_id}/api_keys/${key_id}`);
	}
}

/**
 * DeleteProjectApiKeyCommand
 *
 * @summary Deletes an API key from the project.
 */
export class DeleteProjectApiKeyCommand extends Command<
	DeleteProjectApiKeyCommandInput,
	ProjectApiKeyDeleteResponse
> {
	public override method = "delete" as const;

	constructor(input: DeleteProjectApiKeyCommandInput) {
		const { project_id, key_id } = input;
		super(encodePath`/organization/projects/${project_id}/api_keys/${key_id}`);
	}
}
