/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-11T06:12:45.230Z
 *
 */
/** The role of the author of a message */
export const chatCompletionRole = [
	"system",
	"user",
	"assistant",
	"tool",
	"function",
] as const;
/** The event type. */
export const auditLogEventType = [
	"api_key.created",
	"api_key.updated",
	"api_key.deleted",
	"invite.sent",
	"invite.accepted",
	"invite.deleted",
	"login.succeeded",
	"login.failed",
	"logout.succeeded",
	"logout.failed",
	"organization.updated",
	"project.created",
	"project.updated",
	"project.archived",
	"service_account.created",
	"service_account.updated",
	"service_account.deleted",
	"user.added",
	"user.updated",
	"user.deleted",
] as const;
/**
 * The format of the output, in one of these options: `json`, `text`, `srt`,
 * `verbose_json`, or `vtt`.
 */
export const audioResponseFormat = [
	"json",
	"text",
	"srt",
	"verbose_json",
	"vtt",
] as const;
