import { PublicValibotHonoError } from "@block65/rest-client";
/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-02T06:44:56.439Z
 *
 */
import { validator } from "hono/validator";
import * as v from "valibot";
import {
	exactAddUploadPartCommandParamsSchema,
	exactArchiveProjectCommandParamsSchema,
	exactCancelBatchCommandParamsSchema,
	exactCancelFineTuningJobCommandParamsSchema,
	exactCancelRunCommandParamsSchema,
	exactCancelUploadCommandParamsSchema,
	exactCancelVectorStoreFileBatchCommandParamsSchema,
	exactCompleteUploadCommandBodySchema,
	exactCompleteUploadCommandParamsSchema,
	exactCreateAssistantCommandBodySchema,
	exactCreateBatchCommandBodySchema,
	exactCreateChatCompletionCommandBodySchema,
	exactCreateCompletionCommandBodySchema,
	exactCreateEmbeddingCommandBodySchema,
	exactCreateFineTuningJobCommandBodySchema,
	exactCreateImageCommandBodySchema,
	exactCreateMessageCommandBodySchema,
	exactCreateMessageCommandParamsSchema,
	exactCreateModerationCommandBodySchema,
	exactCreateProjectCommandBodySchema,
	exactCreateProjectServiceAccountCommandBodySchema,
	exactCreateProjectServiceAccountCommandParamsSchema,
	exactCreateProjectUserCommandBodySchema,
	exactCreateProjectUserCommandParamsSchema,
	exactCreateRunCommandBodySchema,
	exactCreateRunCommandParamsSchema,
	exactCreateRunCommandQuerySchema,
	exactCreateSpeechCommandBodySchema,
	exactCreateThreadAndRunCommandBodySchema,
	exactCreateThreadCommandBodySchema,
	exactCreateUploadCommandBodySchema,
	exactCreateVectorStoreCommandBodySchema,
	exactCreateVectorStoreFileBatchCommandBodySchema,
	exactCreateVectorStoreFileBatchCommandParamsSchema,
	exactCreateVectorStoreFileCommandBodySchema,
	exactCreateVectorStoreFileCommandParamsSchema,
	exactDeleteAssistantCommandParamsSchema,
	exactDeleteFileCommandParamsSchema,
	exactDeleteInviteCommandParamsSchema,
	exactDeleteMessageCommandParamsSchema,
	exactDeleteModelCommandParamsSchema,
	exactDeleteProjectApiKeyCommandParamsSchema,
	exactDeleteProjectServiceAccountCommandParamsSchema,
	exactDeleteProjectUserCommandParamsSchema,
	exactDeleteThreadCommandParamsSchema,
	exactDeleteUserCommandParamsSchema,
	exactDeleteVectorStoreCommandParamsSchema,
	exactDeleteVectorStoreFileCommandParamsSchema,
	exactDownloadFileCommandParamsSchema,
	exactGetAssistantCommandParamsSchema,
	exactGetMessageCommandParamsSchema,
	exactGetRunCommandParamsSchema,
	exactGetRunStepCommandParamsSchema,
	exactGetRunStepCommandQuerySchema,
	exactGetThreadCommandParamsSchema,
	exactGetVectorStoreCommandParamsSchema,
	exactGetVectorStoreFileBatchCommandParamsSchema,
	exactGetVectorStoreFileCommandParamsSchema,
	exactInviteUserCommandBodySchema,
	exactListAssistantsCommandQuerySchema,
	exactListAuditLogsCommandQuerySchema,
	exactListBatchesCommandQuerySchema,
	exactListFilesCommandQuerySchema,
	exactListFilesInVectorStoreBatchCommandParamsSchema,
	exactListFilesInVectorStoreBatchCommandQuerySchema,
	exactListFineTuningEventsCommandParamsSchema,
	exactListFineTuningEventsCommandQuerySchema,
	exactListFineTuningJobCheckpointsCommandParamsSchema,
	exactListFineTuningJobCheckpointsCommandQuerySchema,
	exactListInvitesCommandQuerySchema,
	exactListMessagesCommandParamsSchema,
	exactListMessagesCommandQuerySchema,
	exactListPaginatedFineTuningJobsCommandQuerySchema,
	exactListProjectApiKeysCommandParamsSchema,
	exactListProjectApiKeysCommandQuerySchema,
	exactListProjectServiceAccountsCommandParamsSchema,
	exactListProjectServiceAccountsCommandQuerySchema,
	exactListProjectUsersCommandParamsSchema,
	exactListProjectUsersCommandQuerySchema,
	exactListProjectsCommandQuerySchema,
	exactListRunStepsCommandParamsSchema,
	exactListRunStepsCommandQuerySchema,
	exactListRunsCommandParamsSchema,
	exactListRunsCommandQuerySchema,
	exactListUsersCommandQuerySchema,
	exactListVectorStoreFilesCommandParamsSchema,
	exactListVectorStoreFilesCommandQuerySchema,
	exactListVectorStoresCommandQuerySchema,
	exactModifyAssistantCommandBodySchema,
	exactModifyAssistantCommandParamsSchema,
	exactModifyMessageCommandBodySchema,
	exactModifyMessageCommandParamsSchema,
	exactModifyProjectCommandBodySchema,
	exactModifyProjectCommandParamsSchema,
	exactModifyProjectUserCommandBodySchema,
	exactModifyProjectUserCommandParamsSchema,
	exactModifyRunCommandBodySchema,
	exactModifyRunCommandParamsSchema,
	exactModifyThreadCommandBodySchema,
	exactModifyThreadCommandParamsSchema,
	exactModifyUserCommandBodySchema,
	exactModifyUserCommandParamsSchema,
	exactModifyVectorStoreCommandBodySchema,
	exactModifyVectorStoreCommandParamsSchema,
	exactRetrieveBatchCommandParamsSchema,
	exactRetrieveFileCommandParamsSchema,
	exactRetrieveFineTuningJobCommandParamsSchema,
	exactRetrieveInviteCommandParamsSchema,
	exactRetrieveModelCommandParamsSchema,
	exactRetrieveProjectApiKeyCommandParamsSchema,
	exactRetrieveProjectCommandParamsSchema,
	exactRetrieveProjectServiceAccountCommandParamsSchema,
	exactRetrieveProjectUserCommandParamsSchema,
	exactRetrieveUserCommandParamsSchema,
	exactSubmitToolOuputsToRunCommandBodySchema,
	exactSubmitToolOuputsToRunCommandParamsSchema,
} from "./valibot.js";

function toPublicValibotHonoError(err: unknown): never {
	if (err instanceof v.ValiError) {
		throw PublicValibotHonoError.from(err);
	}
	throw err;
}

export const createChatCompletion = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateChatCompletionCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createCompletion = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateCompletionCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createImage = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateImageCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createImageEdit = [] as const;
export const createImageVariation = [] as const;
export const createEmbedding = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateEmbeddingCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createSpeech = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateSpeechCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createTranscription = [] as const;
export const createTranslation = [] as const;
export const listFiles = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListFilesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createFile = [] as const;
export const deleteFile = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveFile = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const downloadFile = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDownloadFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createUpload = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateUploadCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const addUploadPart = [
	validator("param", (value) => {
		return v
			.parseAsync(exactAddUploadPartCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const completeUpload = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCompleteUploadCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCompleteUploadCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const cancelUpload = [
	validator("param", (value) => {
		return v
			.parseAsync(exactCancelUploadCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createFineTuningJob = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateFineTuningJobCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listPaginatedFineTuningJobs = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListPaginatedFineTuningJobsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveFineTuningJob = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveFineTuningJobCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listFineTuningEvents = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListFineTuningEventsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListFineTuningEventsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const cancelFineTuningJob = [
	validator("param", (value) => {
		return v
			.parseAsync(exactCancelFineTuningJobCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listFineTuningJobCheckpoints = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListFineTuningJobCheckpointsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListFineTuningJobCheckpointsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listModels = [] as const;
export const retrieveModel = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveModelCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteModel = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteModelCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createModeration = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateModerationCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listAssistants = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListAssistantsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createAssistant = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateAssistantCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getAssistant = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetAssistantCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyAssistant = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyAssistantCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyAssistantCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteAssistant = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteAssistantCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createThread = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateThreadCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getThread = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetThreadCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyThread = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyThreadCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyThreadCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteThread = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteThreadCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listMessages = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListMessagesCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListMessagesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createMessage = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateMessageCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateMessageCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getMessage = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetMessageCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyMessage = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyMessageCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyMessageCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteMessage = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteMessageCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createThreadAndRun = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateThreadAndRunCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listRuns = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListRunsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListRunsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createRun = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateRunCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateRunCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactCreateRunCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getRun = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetRunCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyRun = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyRunCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyRunCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const submitToolOuputsToRun = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSubmitToolOuputsToRunCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactSubmitToolOuputsToRunCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const cancelRun = [
	validator("param", (value) => {
		return v
			.parseAsync(exactCancelRunCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listRunSteps = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListRunStepsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListRunStepsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getRunStep = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetRunStepCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactGetRunStepCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listVectorStores = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListVectorStoresCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createVectorStore = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateVectorStoreCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getVectorStore = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetVectorStoreCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyVectorStore = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyVectorStoreCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyVectorStoreCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteVectorStore = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteVectorStoreCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listVectorStoreFiles = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListVectorStoreFilesCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListVectorStoreFilesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createVectorStoreFile = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateVectorStoreFileCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateVectorStoreFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getVectorStoreFile = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetVectorStoreFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteVectorStoreFile = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteVectorStoreFileCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createVectorStoreFileBatch = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateVectorStoreFileBatchCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateVectorStoreFileBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getVectorStoreFileBatch = [
	validator("param", (value) => {
		return v
			.parseAsync(exactGetVectorStoreFileBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const cancelVectorStoreFileBatch = [
	validator("param", (value) => {
		return v
			.parseAsync(exactCancelVectorStoreFileBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listFilesInVectorStoreBatch = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListFilesInVectorStoreBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListFilesInVectorStoreBatchCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createBatch = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateBatchCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listBatches = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListBatchesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveBatch = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const cancelBatch = [
	validator("param", (value) => {
		return v
			.parseAsync(exactCancelBatchCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listauditlogs = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListAuditLogsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listinvites = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListInvitesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const inviteUser = [
	validator("json", (value) => {
		return v
			.parseAsync(exactInviteUserCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveinvite = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveInviteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteinvite = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteInviteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listusers = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListUsersCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveuser = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyuser = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyUserCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteuser = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listprojects = [
	validator("query", (value) => {
		return v
			.parseAsync(exactListProjectsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createproject = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateProjectCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveproject = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveProjectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyproject = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyProjectCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyProjectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const archiveproject = [
	validator("param", (value) => {
		return v
			.parseAsync(exactArchiveProjectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listprojectusers = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListProjectUsersCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListProjectUsersCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createprojectuser = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateProjectUserCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateProjectUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveprojectuser = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveProjectUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const modifyprojectuser = [
	validator("json", (value) => {
		return v
			.parseAsync(exactModifyProjectUserCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactModifyProjectUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteprojectuser = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteProjectUserCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listprojectserviceaccounts = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListProjectServiceAccountsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListProjectServiceAccountsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const createprojectserviceaccount = [
	validator("json", (value) => {
		return v
			.parseAsync(exactCreateProjectServiceAccountCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactCreateProjectServiceAccountCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveprojectserviceaccount = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveProjectServiceAccountCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteprojectserviceaccount = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteProjectServiceAccountCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const listprojectapikeys = [
	validator("param", (value) => {
		return v
			.parseAsync(exactListProjectApiKeysCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactListProjectApiKeysCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const retrieveprojectapikey = [
	validator("param", (value) => {
		return v
			.parseAsync(exactRetrieveProjectApiKeyCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const deleteprojectapikey = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDeleteProjectApiKeyCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
