/**
 * This file is auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2023-05-11T04:29:04.091Z
 *
 */
import {
  RestServiceClient,
  createIsomorphicFetcher,
  type RestServiceClientConfig,
} from '@block65/rest-client';
import {
  type ListEnginesCommandInput,
  type RetrieveEngineCommandInput,
  type CreateCompletionCommandInput,
  type CreateChatCompletionCommandInput,
  type CreateEditCommandInput,
  type CreateImageCommandInput,
  type CreateImageEditCommandInput,
  type CreateImageVariationCommandInput,
  type CreateEmbeddingCommandInput,
  type CreateTranscriptionCommandInput,
  type CreateTranslationCommandInput,
  type CreateSearchCommandInput,
  type ListFilesCommandInput,
  type CreateFileCommandInput,
  type DeleteFileCommandInput,
  type RetrieveFileCommandInput,
  type DownloadFileCommandInput,
  type CreateAnswerCommandInput,
  type CreateClassificationCommandInput,
  type CreateFineTuneCommandInput,
  type ListFineTunesCommandInput,
  type RetrieveFineTuneCommandInput,
  type CancelFineTuneCommandInput,
  type ListFineTuneEventsCommandInput,
  type ListModelsCommandInput,
  type RetrieveModelCommandInput,
  type DeleteModelCommandInput,
  type CreateModerationCommandInput,
  type ListEnginesResponse,
  type Engine,
  type CreateCompletionResponse,
  type CreateChatCompletionResponse,
  type CreateEditResponse,
  type ImagesResponse,
  type CreateEmbeddingResponse,
  type CreateTranscriptionResponse,
  type CreateTranslationResponse,
  type CreateSearchResponse,
  type ListFilesResponse,
  type OpenAiFile,
  type DeleteFileResponse,
  type CreateAnswerResponse,
  type CreateClassificationResponse,
  type FineTune,
  type ListFineTunesResponse,
  type ListFineTuneEventsResponse,
  type ListModelsResponse,
  type Model,
  type DeleteModelResponse,
  type CreateModerationResponse,
} from './types.js';

type AllInputs =
  | ListEnginesCommandInput
  | RetrieveEngineCommandInput
  | CreateCompletionCommandInput
  | CreateChatCompletionCommandInput
  | CreateEditCommandInput
  | CreateImageCommandInput
  | CreateImageEditCommandInput
  | CreateImageVariationCommandInput
  | CreateEmbeddingCommandInput
  | CreateTranscriptionCommandInput
  | CreateTranslationCommandInput
  | CreateSearchCommandInput
  | ListFilesCommandInput
  | CreateFileCommandInput
  | DeleteFileCommandInput
  | RetrieveFileCommandInput
  | DownloadFileCommandInput
  | CreateAnswerCommandInput
  | CreateClassificationCommandInput
  | CreateFineTuneCommandInput
  | ListFineTunesCommandInput
  | RetrieveFineTuneCommandInput
  | CancelFineTuneCommandInput
  | ListFineTuneEventsCommandInput
  | ListModelsCommandInput
  | RetrieveModelCommandInput
  | DeleteModelCommandInput
  | CreateModerationCommandInput;
type AllOutputs =
  | ListEnginesResponse
  | Engine
  | CreateCompletionResponse
  | CreateChatCompletionResponse
  | CreateEditResponse
  | ImagesResponse
  | CreateEmbeddingResponse
  | CreateTranscriptionResponse
  | CreateTranslationResponse
  | CreateSearchResponse
  | ListFilesResponse
  | OpenAiFile
  | DeleteFileResponse
  | CreateAnswerResponse
  | CreateClassificationResponse
  | FineTune
  | ListFineTunesResponse
  | ListFineTuneEventsResponse
  | ListModelsResponse
  | Model
  | DeleteModelResponse
  | CreateModerationResponse;

export class OpenAiApiRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    baseUrl = new URL('https://api.openai.com/v1/'),
    fetcher = createIsomorphicFetcher(),
    config?: RestServiceClientConfig,
  ) {
    super(baseUrl, fetcher, config);
  }
}
