/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2024-05-27T10:54:46.817Z
 *
 */
import {
  RestServiceClient,
  createIsomorphicNativeFetcher,
  type RestServiceClientConfig,
} from '@block65/rest-client';
import {
  type CreateChatCompletionCommandInput,
  type CreateCompletionCommandInput,
  type CreateEditCommandInput,
  type CreateImageCommandInput,
  type CreateImageEditCommandInput,
  type CreateImageVariationCommandInput,
  type CreateEmbeddingCommandInput,
  type CreateSpeechCommandInput,
  type CreateTranscriptionCommandInput,
  type CreateTranslationCommandInput,
  type ListFilesCommandInput,
  type CreateFileCommandInput,
  type DeleteFileCommandInput,
  type RetrieveFileCommandInput,
  type DownloadFileCommandInput,
  type CreateFineTuningJobCommandInput,
  type ListPaginatedFineTuningJobsCommandInput,
  type RetrieveFineTuningJobCommandInput,
  type ListFineTuningEventsCommandInput,
  type CancelFineTuningJobCommandInput,
  type CreateFineTuneCommandInput,
  type ListFineTunesCommandInput,
  type RetrieveFineTuneCommandInput,
  type CancelFineTuneCommandInput,
  type ListFineTuneEventsCommandInput,
  type ListModelsCommandInput,
  type RetrieveModelCommandInput,
  type DeleteModelCommandInput,
  type CreateModerationCommandInput,
  type ListAssistantsCommandInput,
  type CreateAssistantCommandInput,
  type GetAssistantCommandInput,
  type ModifyAssistantCommandInput,
  type DeleteAssistantCommandInput,
  type CreateThreadCommandInput,
  type GetThreadCommandInput,
  type ModifyThreadCommandInput,
  type DeleteThreadCommandInput,
  type ListMessagesCommandInput,
  type CreateMessageCommandInput,
  type GetMessageCommandInput,
  type ModifyMessageCommandInput,
  type CreateThreadAndRunCommandInput,
  type ListRunsCommandInput,
  type CreateRunCommandInput,
  type GetRunCommandInput,
  type ModifyRunCommandInput,
  type SubmitToolOuputsToRunCommandInput,
  type CancelRunCommandInput,
  type ListRunStepsCommandInput,
  type GetRunStepCommandInput,
  type ListAssistantFilesCommandInput,
  type CreateAssistantFileCommandInput,
  type GetAssistantFileCommandInput,
  type DeleteAssistantFileCommandInput,
  type ListMessageFilesCommandInput,
  type GetMessageFileCommandInput,
  type CreateChatCompletionResponse,
  type CreateCompletionResponse,
  type CreateEditResponse,
  type ImagesResponse,
  type CreateEmbeddingResponse,
  type CreateTranscriptionResponse,
  type CreateTranslationResponse,
  type ListFilesResponse,
  type OpenAiFile,
  type DeleteFileResponse,
  type FineTuningJob,
  type ListPaginatedFineTuningJobsResponse,
  type ListFineTuningJobEventsResponse,
  type FineTune,
  type ListFineTunesResponse,
  type ListFineTuneEventsResponse,
  type ListModelsResponse,
  type Model,
  type DeleteModelResponse,
  type CreateModerationResponse,
  type ListAssistantsResponse,
  type AssistantObject,
  type DeleteAssistantResponse,
  type ThreadObject,
  type DeleteThreadResponse,
  type ListMessagesResponse,
  type MessageObject,
  type RunObject,
  type ListRunsResponse,
  type ListRunStepsResponse,
  type RunStepObject,
  type ListAssistantFilesResponse,
  type AssistantFileObject,
  type DeleteAssistantFileResponse,
  type ListMessageFilesResponse,
  type MessageFileObject,
} from './types.js';

type AllInputs =
  | CreateChatCompletionCommandInput
  | CreateCompletionCommandInput
  | CreateEditCommandInput
  | CreateImageCommandInput
  | CreateImageEditCommandInput
  | CreateImageVariationCommandInput
  | CreateEmbeddingCommandInput
  | CreateSpeechCommandInput
  | CreateTranscriptionCommandInput
  | CreateTranslationCommandInput
  | ListFilesCommandInput
  | CreateFileCommandInput
  | DeleteFileCommandInput
  | RetrieveFileCommandInput
  | DownloadFileCommandInput
  | CreateFineTuningJobCommandInput
  | ListPaginatedFineTuningJobsCommandInput
  | RetrieveFineTuningJobCommandInput
  | ListFineTuningEventsCommandInput
  | CancelFineTuningJobCommandInput
  | CreateFineTuneCommandInput
  | ListFineTunesCommandInput
  | RetrieveFineTuneCommandInput
  | CancelFineTuneCommandInput
  | ListFineTuneEventsCommandInput
  | ListModelsCommandInput
  | RetrieveModelCommandInput
  | DeleteModelCommandInput
  | CreateModerationCommandInput
  | ListAssistantsCommandInput
  | CreateAssistantCommandInput
  | GetAssistantCommandInput
  | ModifyAssistantCommandInput
  | DeleteAssistantCommandInput
  | CreateThreadCommandInput
  | GetThreadCommandInput
  | ModifyThreadCommandInput
  | DeleteThreadCommandInput
  | ListMessagesCommandInput
  | CreateMessageCommandInput
  | GetMessageCommandInput
  | ModifyMessageCommandInput
  | CreateThreadAndRunCommandInput
  | ListRunsCommandInput
  | CreateRunCommandInput
  | GetRunCommandInput
  | ModifyRunCommandInput
  | SubmitToolOuputsToRunCommandInput
  | CancelRunCommandInput
  | ListRunStepsCommandInput
  | GetRunStepCommandInput
  | ListAssistantFilesCommandInput
  | CreateAssistantFileCommandInput
  | GetAssistantFileCommandInput
  | DeleteAssistantFileCommandInput
  | ListMessageFilesCommandInput
  | GetMessageFileCommandInput;
type AllOutputs =
  | CreateChatCompletionResponse
  | CreateCompletionResponse
  | CreateEditResponse
  | ImagesResponse
  | CreateEmbeddingResponse
  | void
  | CreateTranscriptionResponse
  | CreateTranslationResponse
  | ListFilesResponse
  | OpenAiFile
  | DeleteFileResponse
  | FineTuningJob
  | ListPaginatedFineTuningJobsResponse
  | ListFineTuningJobEventsResponse
  | FineTune
  | ListFineTunesResponse
  | ListFineTuneEventsResponse
  | ListModelsResponse
  | Model
  | DeleteModelResponse
  | CreateModerationResponse
  | ListAssistantsResponse
  | AssistantObject
  | DeleteAssistantResponse
  | ThreadObject
  | DeleteThreadResponse
  | ListMessagesResponse
  | MessageObject
  | RunObject
  | ListRunsResponse
  | ListRunStepsResponse
  | RunStepObject
  | ListAssistantFilesResponse
  | AssistantFileObject
  | DeleteAssistantFileResponse
  | ListMessageFilesResponse
  | MessageFileObject;

export class OpenAiApiRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    baseUrl = new URL('https://api.openai.com/v1/'),
    fetcher = createIsomorphicNativeFetcher(),
    config?: RestServiceClientConfig,
  ) {
    super(baseUrl, fetcher, config);
  }
}
