/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-18T09:27:31.161Z
 *
 */
import {
	RestServiceClient,
	type RestServiceClientConfig,
} from "@block65/rest-client";
import type { Except, UndefinedOnPartialDeep } from "type-fest";
import type {
	AddUploadPartCommandInput,
	ArchiveProjectCommandInput,
	AssistantObject,
	Batch,
	CancelBatchCommandInput,
	CancelFineTuningJobCommandInput,
	CancelRunCommandInput,
	CancelUploadCommandInput,
	CancelVectorStoreFileBatchCommandInput,
	CompleteUploadCommandInput,
	CreateAssistantCommandInput,
	CreateBatchCommandInput,
	CreateChatCompletionCommandInput,
	CreateChatCompletionResponse,
	CreateCompletionCommandInput,
	CreateCompletionResponse,
	CreateEmbeddingCommandInput,
	CreateEmbeddingResponse,
	CreateFileCommandInput,
	CreateFineTuningJobCommandInput,
	CreateImageCommandInput,
	CreateImageEditCommandInput,
	CreateImageVariationCommandInput,
	CreateMessageCommandInput,
	CreateModerationCommandInput,
	CreateModerationResponse,
	CreateProjectCommandInput,
	CreateProjectServiceAccountCommandInput,
	CreateProjectUserCommandInput,
	CreateRunCommandInput,
	CreateSpeechCommandInput,
	CreateThreadAndRunCommandInput,
	CreateThreadCommandInput,
	CreateTranscriptionCommandInput,
	CreateTranscriptionCommandOutput,
	CreateTranslationCommandInput,
	CreateTranslationCommandOutput,
	CreateUploadCommandInput,
	CreateVectorStoreCommandInput,
	CreateVectorStoreFileBatchCommandInput,
	CreateVectorStoreFileCommandInput,
	DeleteAssistantCommandInput,
	DeleteAssistantResponse,
	DeleteFileCommandInput,
	DeleteFileResponse,
	DeleteInviteCommandInput,
	DeleteMessageCommandInput,
	DeleteMessageResponse,
	DeleteModelCommandInput,
	DeleteModelResponse,
	DeleteProjectApiKeyCommandInput,
	DeleteProjectServiceAccountCommandInput,
	DeleteProjectUserCommandInput,
	DeleteThreadCommandInput,
	DeleteThreadResponse,
	DeleteUserCommandInput,
	DeleteVectorStoreCommandInput,
	DeleteVectorStoreFileCommandInput,
	DeleteVectorStoreFileResponse,
	DeleteVectorStoreResponse,
	DownloadFileCommandInput,
	DownloadFileCommandOutput,
	FineTuningJob,
	GetAssistantCommandInput,
	GetMessageCommandInput,
	GetRunCommandInput,
	GetRunStepCommandInput,
	GetThreadCommandInput,
	GetVectorStoreCommandInput,
	GetVectorStoreFileBatchCommandInput,
	GetVectorStoreFileCommandInput,
	ImagesResponse,
	Invite,
	InviteDeleteResponse,
	InviteListResponse,
	InviteUserCommandInput,
	ListAssistantsCommandInput,
	ListAssistantsResponse,
	ListAuditLogsCommandInput,
	ListAuditLogsResponse,
	ListBatchesCommandInput,
	ListBatchesResponse,
	ListFilesCommandInput,
	ListFilesInVectorStoreBatchCommandInput,
	ListFilesResponse,
	ListFineTuningEventsCommandInput,
	ListFineTuningJobCheckpointsCommandInput,
	ListFineTuningJobCheckpointsResponse,
	ListFineTuningJobEventsResponse,
	ListInvitesCommandInput,
	ListMessagesCommandInput,
	ListMessagesResponse,
	ListModelsCommandInput,
	ListModelsResponse,
	ListPaginatedFineTuningJobsCommandInput,
	ListPaginatedFineTuningJobsResponse,
	ListProjectApiKeysCommandInput,
	ListProjectServiceAccountsCommandInput,
	ListProjectUsersCommandInput,
	ListProjectsCommandInput,
	ListRunStepsCommandInput,
	ListRunStepsResponse,
	ListRunsCommandInput,
	ListRunsResponse,
	ListUsersCommandInput,
	ListVectorStoreFilesCommandInput,
	ListVectorStoreFilesResponse,
	ListVectorStoresCommandInput,
	ListVectorStoresResponse,
	MessageObject,
	Model,
	ModifyAssistantCommandInput,
	ModifyMessageCommandInput,
	ModifyProjectCommandInput,
	ModifyProjectUserCommandInput,
	ModifyRunCommandInput,
	ModifyThreadCommandInput,
	ModifyUserCommandInput,
	ModifyVectorStoreCommandInput,
	OpenAiFile,
	Project,
	ProjectApiKey,
	ProjectApiKeyDeleteResponse,
	ProjectApiKeyListResponse,
	ProjectListResponse,
	ProjectServiceAccount,
	ProjectServiceAccountCreateResponse,
	ProjectServiceAccountDeleteResponse,
	ProjectServiceAccountListResponse,
	ProjectUser,
	ProjectUserDeleteResponse,
	ProjectUserListResponse,
	RetrieveBatchCommandInput,
	RetrieveFileCommandInput,
	RetrieveFineTuningJobCommandInput,
	RetrieveInviteCommandInput,
	RetrieveModelCommandInput,
	RetrieveProjectApiKeyCommandInput,
	RetrieveProjectCommandInput,
	RetrieveProjectServiceAccountCommandInput,
	RetrieveProjectUserCommandInput,
	RetrieveUserCommandInput,
	RunObject,
	RunStepObject,
	SubmitToolOuputsToRunCommandInput,
	ThreadObject,
	Upload,
	UploadPart,
	User,
	UserDeleteResponse,
	UserListResponse,
	VectorStoreFileBatchObject,
	VectorStoreFileObject,
	VectorStoreObject,
} from "./types.js";

type AllInputs =
	| UndefinedOnPartialDeep<ArchiveProjectCommandInput>
	| UndefinedOnPartialDeep<CancelBatchCommandInput>
	| UndefinedOnPartialDeep<CancelFineTuningJobCommandInput>
	| UndefinedOnPartialDeep<CancelRunCommandInput>
	| UndefinedOnPartialDeep<CancelUploadCommandInput>
	| UndefinedOnPartialDeep<CancelVectorStoreFileBatchCommandInput>
	| UndefinedOnPartialDeep<CompleteUploadCommandInput>
	| UndefinedOnPartialDeep<CreateAssistantCommandInput>
	| UndefinedOnPartialDeep<CreateBatchCommandInput>
	| UndefinedOnPartialDeep<CreateChatCompletionCommandInput>
	| UndefinedOnPartialDeep<CreateCompletionCommandInput>
	| UndefinedOnPartialDeep<CreateEmbeddingCommandInput>
	| UndefinedOnPartialDeep<CreateFineTuningJobCommandInput>
	| UndefinedOnPartialDeep<CreateImageCommandInput>
	| UndefinedOnPartialDeep<CreateMessageCommandInput>
	| UndefinedOnPartialDeep<CreateModerationCommandInput>
	| UndefinedOnPartialDeep<CreateProjectCommandInput>
	| UndefinedOnPartialDeep<CreateProjectServiceAccountCommandInput>
	| UndefinedOnPartialDeep<CreateProjectUserCommandInput>
	| UndefinedOnPartialDeep<CreateRunCommandInput>
	| UndefinedOnPartialDeep<CreateSpeechCommandInput>
	| UndefinedOnPartialDeep<CreateThreadAndRunCommandInput>
	| UndefinedOnPartialDeep<CreateThreadCommandInput>
	| UndefinedOnPartialDeep<CreateUploadCommandInput>
	| UndefinedOnPartialDeep<CreateVectorStoreCommandInput>
	| UndefinedOnPartialDeep<CreateVectorStoreFileBatchCommandInput>
	| UndefinedOnPartialDeep<CreateVectorStoreFileCommandInput>
	| UndefinedOnPartialDeep<DeleteAssistantCommandInput>
	| UndefinedOnPartialDeep<DeleteFileCommandInput>
	| UndefinedOnPartialDeep<DeleteInviteCommandInput>
	| UndefinedOnPartialDeep<DeleteMessageCommandInput>
	| UndefinedOnPartialDeep<DeleteModelCommandInput>
	| UndefinedOnPartialDeep<DeleteProjectApiKeyCommandInput>
	| UndefinedOnPartialDeep<DeleteProjectServiceAccountCommandInput>
	| UndefinedOnPartialDeep<DeleteProjectUserCommandInput>
	| UndefinedOnPartialDeep<DeleteThreadCommandInput>
	| UndefinedOnPartialDeep<DeleteUserCommandInput>
	| UndefinedOnPartialDeep<DeleteVectorStoreCommandInput>
	| UndefinedOnPartialDeep<DeleteVectorStoreFileCommandInput>
	| UndefinedOnPartialDeep<DownloadFileCommandInput>
	| (UndefinedOnPartialDeep<Except<AddUploadPartCommandInput, "body">> &
			Pick<AddUploadPartCommandInput, "body">)
	| (UndefinedOnPartialDeep<Except<CreateFileCommandInput, "body">> &
			Pick<CreateFileCommandInput, "body">)
	| (UndefinedOnPartialDeep<Except<CreateImageEditCommandInput, "body">> &
			Pick<CreateImageEditCommandInput, "body">)
	| (UndefinedOnPartialDeep<Except<CreateImageVariationCommandInput, "body">> &
			Pick<CreateImageVariationCommandInput, "body">)
	| (UndefinedOnPartialDeep<Except<CreateTranscriptionCommandInput, "body">> &
			Pick<CreateTranscriptionCommandInput, "body">)
	| (UndefinedOnPartialDeep<Except<CreateTranslationCommandInput, "body">> &
			Pick<CreateTranslationCommandInput, "body">)
	| UndefinedOnPartialDeep<GetAssistantCommandInput>
	| UndefinedOnPartialDeep<GetMessageCommandInput>
	| UndefinedOnPartialDeep<GetRunCommandInput>
	| UndefinedOnPartialDeep<GetRunStepCommandInput>
	| UndefinedOnPartialDeep<GetThreadCommandInput>
	| UndefinedOnPartialDeep<GetVectorStoreCommandInput>
	| UndefinedOnPartialDeep<GetVectorStoreFileBatchCommandInput>
	| UndefinedOnPartialDeep<GetVectorStoreFileCommandInput>
	| UndefinedOnPartialDeep<InviteUserCommandInput>
	| UndefinedOnPartialDeep<ListAssistantsCommandInput>
	| UndefinedOnPartialDeep<ListAuditLogsCommandInput>
	| UndefinedOnPartialDeep<ListBatchesCommandInput>
	| UndefinedOnPartialDeep<ListFilesCommandInput>
	| UndefinedOnPartialDeep<ListFilesInVectorStoreBatchCommandInput>
	| UndefinedOnPartialDeep<ListFineTuningEventsCommandInput>
	| UndefinedOnPartialDeep<ListFineTuningJobCheckpointsCommandInput>
	| UndefinedOnPartialDeep<ListInvitesCommandInput>
	| UndefinedOnPartialDeep<ListMessagesCommandInput>
	| UndefinedOnPartialDeep<ListModelsCommandInput>
	| UndefinedOnPartialDeep<ListPaginatedFineTuningJobsCommandInput>
	| UndefinedOnPartialDeep<ListProjectApiKeysCommandInput>
	| UndefinedOnPartialDeep<ListProjectsCommandInput>
	| UndefinedOnPartialDeep<ListProjectServiceAccountsCommandInput>
	| UndefinedOnPartialDeep<ListProjectUsersCommandInput>
	| UndefinedOnPartialDeep<ListRunsCommandInput>
	| UndefinedOnPartialDeep<ListRunStepsCommandInput>
	| UndefinedOnPartialDeep<ListUsersCommandInput>
	| UndefinedOnPartialDeep<ListVectorStoreFilesCommandInput>
	| UndefinedOnPartialDeep<ListVectorStoresCommandInput>
	| UndefinedOnPartialDeep<ModifyAssistantCommandInput>
	| UndefinedOnPartialDeep<ModifyMessageCommandInput>
	| UndefinedOnPartialDeep<ModifyProjectCommandInput>
	| UndefinedOnPartialDeep<ModifyProjectUserCommandInput>
	| UndefinedOnPartialDeep<ModifyRunCommandInput>
	| UndefinedOnPartialDeep<ModifyThreadCommandInput>
	| UndefinedOnPartialDeep<ModifyUserCommandInput>
	| UndefinedOnPartialDeep<ModifyVectorStoreCommandInput>
	| UndefinedOnPartialDeep<RetrieveBatchCommandInput>
	| UndefinedOnPartialDeep<RetrieveFileCommandInput>
	| UndefinedOnPartialDeep<RetrieveFineTuningJobCommandInput>
	| UndefinedOnPartialDeep<RetrieveInviteCommandInput>
	| UndefinedOnPartialDeep<RetrieveModelCommandInput>
	| UndefinedOnPartialDeep<RetrieveProjectApiKeyCommandInput>
	| UndefinedOnPartialDeep<RetrieveProjectCommandInput>
	| UndefinedOnPartialDeep<RetrieveProjectServiceAccountCommandInput>
	| UndefinedOnPartialDeep<RetrieveProjectUserCommandInput>
	| UndefinedOnPartialDeep<RetrieveUserCommandInput>
	| UndefinedOnPartialDeep<SubmitToolOuputsToRunCommandInput>;
type AllOutputs =
	| AssistantObject
	| Batch
	| CreateChatCompletionResponse
	| CreateCompletionResponse
	| CreateEmbeddingResponse
	| CreateModerationResponse
	| CreateTranscriptionCommandOutput
	| CreateTranslationCommandOutput
	| DeleteAssistantResponse
	| DeleteFileResponse
	| DeleteMessageResponse
	| DeleteModelResponse
	| DeleteThreadResponse
	| DeleteVectorStoreFileResponse
	| DeleteVectorStoreResponse
	| DownloadFileCommandOutput
	| FineTuningJob
	| ImagesResponse
	| Invite
	| InviteDeleteResponse
	| InviteListResponse
	| ListAssistantsResponse
	| ListAuditLogsResponse
	| ListBatchesResponse
	| ListFilesResponse
	| ListFineTuningJobCheckpointsResponse
	| ListFineTuningJobEventsResponse
	| ListMessagesResponse
	| ListModelsResponse
	| ListPaginatedFineTuningJobsResponse
	| ListRunsResponse
	| ListRunStepsResponse
	| ListVectorStoreFilesResponse
	| ListVectorStoresResponse
	| MessageObject
	| Model
	| OpenAiFile
	| Project
	| ProjectApiKey
	| ProjectApiKeyDeleteResponse
	| ProjectApiKeyListResponse
	| ProjectListResponse
	| ProjectServiceAccount
	| ProjectServiceAccountCreateResponse
	| ProjectServiceAccountDeleteResponse
	| ProjectServiceAccountListResponse
	| ProjectUser
	| ProjectUserDeleteResponse
	| ProjectUserListResponse
	| RunObject
	| RunStepObject
	| ThreadObject
	| Upload
	| UploadPart
	| User
	| UserDeleteResponse
	| UserListResponse
	| VectorStoreFileBatchObject
	| VectorStoreFileObject
	| VectorStoreObject;

export class OpenAiApiRestClient extends RestServiceClient<
	AllInputs,
	AllOutputs
> {
	constructor(
		baseUrl: string | URL = new URL("https://api.openai.com/v1/"),
		config?: RestServiceClientConfig,
	) {
		super(baseUrl, config);
	}
}
