/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2025-02-02T09:59:28.164Z
 *
 */
/** eslint-disable max-classes */
import { Command, jsonStringify } from '@block65/rest-client';
import type {
  GetOperationCommandInput,
  LongRunningOperation,
  ListBillingAccountsCommandInput,
  BillingAccountList,
  CreateBillingAccountCommandInput,
  BillingAccount,
  GetBillingAccountCommandInput,
  UpdateBillingAccountCommandInput,
  GetBillingAccountPortalCommandInput,
  BillingAccountPortal,
  LinkBillingAccountCommandInput,
  ListPaymentMethodsCommandInput,
  PaymentMethods,
  CreatePaymentMethodCommandInput,
  PaymentMethodIntendedLro,
  GetPaymentMethodFromStripeCommandInput,
  PaymentMethod,
  GetPaymentMethodCommandInput,
  UpdatePaymentMethodCommandInput,
  DeletePaymentMethodCommandInput,
  PaymentMethodDeletedLro,
  ListBillingSubscriptionsCommandInput,
  BillingSubscriptions,
  CreateBillingSubscriptionCommandInput,
  BillingSubscriptionLro,
  UpdateBillingSubscriptionCommandInput,
  CancelSubscriptionCommandInput,
  UpdateBillingSubscriptionPromoCodeCommandInput,
} from './types.ts';

/**
 * GetOperationCommand
 *
 */
export class GetOperationCommand extends Command<
  GetOperationCommandInput,
  LongRunningOperation
> {
  public override method = 'get' as const;

  constructor(input: GetOperationCommandInput) {
    const { operationId } = input;
    super(`/operations/${operationId}`);
  }
}

/**
 * ListBillingAccountsCommand
 *
 */
export class ListBillingAccountsCommand extends Command<
  ListBillingAccountsCommandInput,
  BillingAccountList
> {
  public override method = 'get' as const;
}

/**
 * CreateBillingAccountCommand
 *
 */
export class CreateBillingAccountCommand extends Command<
  CreateBillingAccountCommandInput,
  BillingAccount
> {
  public override method = 'post' as const;

  constructor(input: CreateBillingAccountCommandInput) {
    const body = input;
    super(`/billing-accounts`, jsonStringify(body));
  }
}

/**
 * GetBillingAccountCommand
 *
 */
export class GetBillingAccountCommand extends Command<
  GetBillingAccountCommandInput,
  BillingAccount
> {
  public override method = 'get' as const;

  constructor(input: GetBillingAccountCommandInput) {
    const { billingAccountId } = input;
    super(`/billing-accounts/${billingAccountId}`);
  }
}

/**
 * UpdateBillingAccountCommand
 *
 */
export class UpdateBillingAccountCommand extends Command<
  UpdateBillingAccountCommandInput,
  BillingAccount
> {
  public override method = 'put' as const;

  constructor(input: UpdateBillingAccountCommandInput) {
    const { billingAccountId, ...body } = input;
    super(`/billing-accounts/${billingAccountId}`, jsonStringify(body));
  }
}

/**
 * GetBillingAccountPortalCommand
 *
 */
export class GetBillingAccountPortalCommand extends Command<
  GetBillingAccountPortalCommandInput,
  BillingAccountPortal
> {
  public override method = 'post' as const;

  constructor(input: GetBillingAccountPortalCommandInput) {
    const { billingAccountId, ...body } = input;
    super(`/billing-accounts/${billingAccountId}/portal`, jsonStringify(body));
  }
}

/**
 * LinkBillingAccountCommand
 *
 */
export class LinkBillingAccountCommand extends Command<
  LinkBillingAccountCommandInput,
  unknown
> {
  public override method = 'post' as const;

  constructor(input: LinkBillingAccountCommandInput) {
    const { billingAccountId, ...body } = input;
    super(`/billing-accounts/${billingAccountId}/link`, jsonStringify(body));
  }
}

/**
 * ListPaymentMethodsCommand
 *
 */
export class ListPaymentMethodsCommand extends Command<
  ListPaymentMethodsCommandInput,
  PaymentMethods
> {
  public override method = 'get' as const;

  constructor(input: ListPaymentMethodsCommandInput) {
    const { billingAccountId } = input;
    super(`/billing-accounts/${billingAccountId}/payment-methods`);
  }
}

/**
 * CreatePaymentMethodCommand
 *
 */
export class CreatePaymentMethodCommand extends Command<
  CreatePaymentMethodCommandInput,
  PaymentMethodIntendedLro
> {
  public override method = 'post' as const;

  constructor(input: CreatePaymentMethodCommandInput) {
    const { billingAccountId } = input;
    super(`/billing-accounts/${billingAccountId}/payment-methods`);
  }
}

/**
 * GetPaymentMethodFromStripeCommand
 *
 */
export class GetPaymentMethodFromStripeCommand extends Command<
  GetPaymentMethodFromStripeCommandInput,
  PaymentMethod
> {
  public override method = 'get' as const;

  constructor(input: GetPaymentMethodFromStripeCommandInput) {
    const { billingAccountId, stripePaymentMethodId } = input;
    super(
      `/billing-accounts/${billingAccountId}/payment-methods/stripe/${stripePaymentMethodId}`,
    );
  }
}

/**
 * GetPaymentMethodCommand
 *
 */
export class GetPaymentMethodCommand extends Command<
  GetPaymentMethodCommandInput,
  PaymentMethod
> {
  public override method = 'get' as const;

  constructor(input: GetPaymentMethodCommandInput) {
    const { billingAccountId, paymentMethodId } = input;
    super(
      `/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
    );
  }
}

/**
 * UpdatePaymentMethodCommand
 *
 */
export class UpdatePaymentMethodCommand extends Command<
  UpdatePaymentMethodCommandInput,
  undefined
> {
  public override method = 'put' as const;

  constructor(input: UpdatePaymentMethodCommandInput) {
    const { billingAccountId, paymentMethodId, ...body } = input;
    super(
      `/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
      jsonStringify(body),
    );
  }
}

/**
 * DeletePaymentMethodCommand
 *
 */
export class DeletePaymentMethodCommand extends Command<
  DeletePaymentMethodCommandInput,
  PaymentMethodDeletedLro
> {
  public override method = 'delete' as const;

  constructor(input: DeletePaymentMethodCommandInput) {
    const { billingAccountId, paymentMethodId } = input;
    super(
      `/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
    );
  }
}

/**
 * ListBillingSubscriptionsCommand
 *
 */
export class ListBillingSubscriptionsCommand extends Command<
  ListBillingSubscriptionsCommandInput,
  BillingSubscriptions
> {
  public override method = 'get' as const;

  constructor(input: ListBillingSubscriptionsCommandInput) {
    const { billingAccountId } = input;
    super(`/billing-accounts/${billingAccountId}/subscriptions`);
  }
}

/**
 * CreateBillingSubscriptionCommand
 *
 */
export class CreateBillingSubscriptionCommand extends Command<
  CreateBillingSubscriptionCommandInput,
  BillingSubscriptionLro
> {
  public override method = 'post' as const;

  constructor(input: CreateBillingSubscriptionCommandInput) {
    const { billingAccountId, ...body } = input;
    super(
      `/billing-accounts/${billingAccountId}/subscriptions`,
      jsonStringify(body),
    );
  }
}

/**
 * UpdateBillingSubscriptionCommand
 *
 */
export class UpdateBillingSubscriptionCommand extends Command<
  UpdateBillingSubscriptionCommandInput,
  undefined
> {
  public override method = 'put' as const;

  constructor(input: UpdateBillingSubscriptionCommandInput) {
    const { billingAccountId, subscriptionId, ...body } = input;
    super(
      `/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}`,
      jsonStringify(body),
    );
  }
}

/**
 * CancelSubscriptionCommand
 *
 */
export class CancelSubscriptionCommand extends Command<
  CancelSubscriptionCommandInput,
  undefined
> {
  public override method = 'delete' as const;

  constructor(input: CancelSubscriptionCommandInput) {
    const { billingAccountId, subscriptionId } = input;
    super(
      `/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}`,
    );
  }
}

/**
 * UpdateBillingSubscriptionPromoCodeCommand
 *
 */
export class UpdateBillingSubscriptionPromoCodeCommand extends Command<
  UpdateBillingSubscriptionPromoCodeCommandInput,
  BillingSubscriptionLro
> {
  public override method = 'put' as const;

  constructor(input: UpdateBillingSubscriptionPromoCodeCommandInput) {
    const { billingAccountId, subscriptionId, ...body } = input;
    super(
      `/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}/promo-code`,
      jsonStringify(body),
    );
  }
}
