import { PublicValidationError } from "@block65/rest-client";
import type { StandardSchemaV1 } from "@standard-schema/spec";
/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-09-02T06:47:29.085Z (rev 0d4a775044bc0242a271cc11ed388cd9)
 *
 */
import { validator } from "hono/validator";
import {
	cancelSubscriptionCommandParamsSchema,
	createBillingAccountCommandBodySchema,
	createBillingSubscriptionCommandBodySchema,
	createBillingSubscriptionCommandParamsSchema,
	createPaymentMethodCommandParamsSchema,
	deletePaymentMethodCommandParamsSchema,
	getBillingAccountCommandParamsSchema,
	getBillingAccountPortalCommandBodySchema,
	getBillingAccountPortalCommandParamsSchema,
	getOperationCommandParamsSchema,
	getPaymentMethodCommandParamsSchema,
	getPaymentMethodFromStripeCommandParamsSchema,
	importBillingDataCommandParamsSchema,
	linkBillingAccountCommandBodySchema,
	linkBillingAccountCommandParamsSchema,
	listBillingSubscriptionsCommandParamsSchema,
	listPaymentMethodsCommandParamsSchema,
	updateBillingAccountCommandBodySchema,
	updateBillingAccountCommandParamsSchema,
	updateBillingSubscriptionCommandBodySchema,
	updateBillingSubscriptionCommandParamsSchema,
	updateBillingSubscriptionPromoCodeCommandBodySchema,
	updateBillingSubscriptionPromoCodeCommandParamsSchema,
	updatePaymentMethodCommandBodySchema,
	updatePaymentMethodCommandParamsSchema,
} from "./valibot.js";

async function standardParse<TSchema extends StandardSchemaV1>(
	schema: TSchema,
	value: unknown,
): Promise<StandardSchemaV1.InferOutput<TSchema>> {
	const result = await schema["~standard"].validate(value);
	if (result.issues) {
		throw PublicValidationError.fromIssues(result.issues);
	}
	return result.value;
}

export const importBillingData = [
	validator("param", (value) =>
		standardParse(importBillingDataCommandParamsSchema, value),
	),
] as const;
export const getOperation = [
	validator("param", (value) =>
		standardParse(getOperationCommandParamsSchema, value),
	),
] as const;
export const listBillingAccounts = [] as const;
export const createBillingAccount = [
	validator("json", (value) =>
		standardParse(createBillingAccountCommandBodySchema, value),
	),
] as const;
export const getBillingAccount = [
	validator("param", (value) =>
		standardParse(getBillingAccountCommandParamsSchema, value),
	),
] as const;
export const updateBillingAccount = [
	validator("json", (value) =>
		standardParse(updateBillingAccountCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(updateBillingAccountCommandParamsSchema, value),
	),
] as const;
export const getBillingAccountPortal = [
	validator("json", (value) =>
		standardParse(getBillingAccountPortalCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(getBillingAccountPortalCommandParamsSchema, value),
	),
] as const;
export const linkBillingAccount = [
	validator("json", (value) =>
		standardParse(linkBillingAccountCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(linkBillingAccountCommandParamsSchema, value),
	),
] as const;
export const listPaymentMethods = [
	validator("param", (value) =>
		standardParse(listPaymentMethodsCommandParamsSchema, value),
	),
] as const;
export const createPaymentMethod = [
	validator("param", (value) =>
		standardParse(createPaymentMethodCommandParamsSchema, value),
	),
] as const;
export const getPaymentMethodFromStripe = [
	validator("param", (value) =>
		standardParse(getPaymentMethodFromStripeCommandParamsSchema, value),
	),
] as const;
export const getPaymentMethod = [
	validator("param", (value) =>
		standardParse(getPaymentMethodCommandParamsSchema, value),
	),
] as const;
export const updatePaymentMethod = [
	validator("json", (value) =>
		standardParse(updatePaymentMethodCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(updatePaymentMethodCommandParamsSchema, value),
	),
] as const;
export const deletePaymentMethod = [
	validator("param", (value) =>
		standardParse(deletePaymentMethodCommandParamsSchema, value),
	),
] as const;
export const listBillingSubscriptions = [
	validator("param", (value) =>
		standardParse(listBillingSubscriptionsCommandParamsSchema, value),
	),
] as const;
export const createBillingSubscription = [
	validator("json", (value) =>
		standardParse(createBillingSubscriptionCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(createBillingSubscriptionCommandParamsSchema, value),
	),
] as const;
export const updateBillingSubscription = [
	validator("json", (value) =>
		standardParse(updateBillingSubscriptionCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(updateBillingSubscriptionCommandParamsSchema, value),
	),
] as const;
export const cancelSubscription = [
	validator("param", (value) =>
		standardParse(cancelSubscriptionCommandParamsSchema, value),
	),
] as const;
export const updateBillingSubscriptionPromoCode = [
	validator("json", (value) =>
		standardParse(updateBillingSubscriptionPromoCodeCommandBodySchema, value),
	),
	validator("param", (value) =>
		standardParse(updateBillingSubscriptionPromoCodeCommandParamsSchema, value),
	),
] as const;
