/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-06-08T01:22:47.528Z
 *
 */
import {
	RestServiceClient,
	type RestServiceClientConfig,
} from "@block65/rest-client";
import type { Except, UndefinedOnPartialDeep } from "type-fest";
import type {
	BillingAccount,
	BillingAccountList,
	BillingAccountPortal,
	BillingSubscriptionLro,
	BillingSubscriptions,
	CancelSubscriptionCommandInput,
	CreateBillingAccountCommandInput,
	CreateBillingSubscriptionCommandInput,
	CreatePaymentMethodCommandInput,
	DeletePaymentMethodCommandInput,
	GetBillingAccountCommandInput,
	GetBillingAccountPortalCommandInput,
	GetOperationCommandInput,
	GetPaymentMethodCommandInput,
	GetPaymentMethodFromStripeCommandInput,
	ImportBillingDataCommandInput,
	LinkBillingAccountCommandInput,
	ListBillingAccountsCommandInput,
	ListBillingSubscriptionsCommandInput,
	ListPaymentMethodsCommandInput,
	LongRunningOperation,
	PaymentMethod,
	PaymentMethodDeletedLro,
	PaymentMethodIntendedLro,
	PaymentMethods,
	UpdateBillingAccountCommandInput,
	UpdateBillingSubscriptionCommandInput,
	UpdateBillingSubscriptionPromoCodeCommandInput,
	UpdatePaymentMethodCommandInput,
} from "./types.js";

export { ResponseValidationError } from "@block65/rest-client";

type AllInputs =
	| UndefinedOnPartialDeep<CancelSubscriptionCommandInput>
	| UndefinedOnPartialDeep<CreateBillingAccountCommandInput>
	| UndefinedOnPartialDeep<CreateBillingSubscriptionCommandInput>
	| UndefinedOnPartialDeep<CreatePaymentMethodCommandInput>
	| UndefinedOnPartialDeep<DeletePaymentMethodCommandInput>
	| (UndefinedOnPartialDeep<Except<ImportBillingDataCommandInput, "body">> &
			Pick<ImportBillingDataCommandInput, "body">)
	| UndefinedOnPartialDeep<GetBillingAccountCommandInput>
	| UndefinedOnPartialDeep<GetBillingAccountPortalCommandInput>
	| UndefinedOnPartialDeep<GetOperationCommandInput>
	| UndefinedOnPartialDeep<GetPaymentMethodCommandInput>
	| UndefinedOnPartialDeep<GetPaymentMethodFromStripeCommandInput>
	| UndefinedOnPartialDeep<LinkBillingAccountCommandInput>
	| UndefinedOnPartialDeep<ListBillingAccountsCommandInput>
	| UndefinedOnPartialDeep<ListBillingSubscriptionsCommandInput>
	| UndefinedOnPartialDeep<ListPaymentMethodsCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingAccountCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingSubscriptionCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingSubscriptionPromoCodeCommandInput>
	| UndefinedOnPartialDeep<UpdatePaymentMethodCommandInput>;
type AllOutputs =
	| BillingAccount
	| BillingAccountList
	| BillingAccountPortal
	| BillingSubscriptionLro
	| BillingSubscriptions
	| LongRunningOperation
	| PaymentMethod
	| PaymentMethodDeletedLro
	| PaymentMethodIntendedLro
	| PaymentMethods
	| undefined;

export class BillingServiceRestApiRestClient extends RestServiceClient<
	AllInputs,
	AllOutputs
> {
	constructor(
		baseUrl: string | URL = new URL("https://api.example.com/"),
		config?: RestServiceClientConfig,
	) {
		super(baseUrl, config);
	}
}
