/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2024-10-13T01:58:17.798Z
 *
 */
import {
  RestServiceClient,
  type RestServiceClientConfig,
} from '@block65/rest-client';
import type {
  BillingAccount,
  BillingAccountList,
  BillingAccountPortal,
  BillingSubscriptionLro,
  BillingSubscriptions,
  CancelSubscriptionCommandInput,
  CreateBillingAccountCommandInput,
  CreateBillingSubscriptionCommandInput,
  CreatePaymentMethodCommandInput,
  DeletePaymentMethodCommandInput,
  GetBillingAccountCommandInput,
  GetBillingAccountPortalCommandInput,
  GetOperationCommandInput,
  GetPaymentMethodCommandInput,
  GetPaymentMethodFromStripeCommandInput,
  LinkBillingAccountCommandInput,
  ListBillingAccountsCommandInput,
  ListBillingSubscriptionsCommandInput,
  ListPaymentMethodsCommandInput,
  LongRunningOperation,
  PaymentMethod,
  PaymentMethodDeletedLro,
  PaymentMethodIntendedLro,
  PaymentMethods,
  UpdateBillingAccountCommandInput,
  UpdateBillingSubscriptionCommandInput,
  UpdateBillingSubscriptionPromoCodeCommandInput,
  UpdatePaymentMethodCommandInput,
} from './types.js';

type AllInputs =
  | CancelSubscriptionCommandInput
  | CreateBillingAccountCommandInput
  | CreateBillingSubscriptionCommandInput
  | CreatePaymentMethodCommandInput
  | DeletePaymentMethodCommandInput
  | GetBillingAccountCommandInput
  | GetBillingAccountPortalCommandInput
  | GetOperationCommandInput
  | GetPaymentMethodCommandInput
  | GetPaymentMethodFromStripeCommandInput
  | LinkBillingAccountCommandInput
  | ListBillingAccountsCommandInput
  | ListBillingSubscriptionsCommandInput
  | ListPaymentMethodsCommandInput
  | UpdateBillingAccountCommandInput
  | UpdateBillingSubscriptionCommandInput
  | UpdateBillingSubscriptionPromoCodeCommandInput
  | UpdatePaymentMethodCommandInput;
type AllOutputs =
  | BillingAccount
  | BillingAccountList
  | BillingAccountPortal
  | BillingSubscriptionLro
  | BillingSubscriptions
  | LongRunningOperation
  | PaymentMethod
  | PaymentMethodDeletedLro
  | PaymentMethodIntendedLro
  | PaymentMethods
  | undefined;

export class BillingServiceRestApiRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    baseUrl: string | URL = new URL('https://api.example.com/'),
    config?: RestServiceClientConfig,
  ) {
    super(baseUrl, config);
  }
}
