import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { oas31 } from "openapi3-ts";
import {
	type CodegenOptions,
	processOpenApiDocument,
} from "./process-document.ts";

// `@generated` marks the file for review tools and the block65 comment rules
const BANNER = `/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */`;

// A JSON import is typed `any`, so the document is checked before it is used
function isOpenApiDocument(value: unknown): value is oas31.OpenAPIObject {
	return (
		typeof value === "object" &&
		value !== null &&
		"openapi" in value &&
		typeof value.openapi === "string"
	);
}

// Records emitter output so a file reformatted on disk still compares equal
const MANIFEST = ".openapi-codegen-manifest.json";

async function readManifest(manifestPath: string) {
	const text = await readFile(manifestPath, "utf8").catch(() => {});

	if (text === undefined) {
		return {};
	}

	try {
		const parsed: unknown = JSON.parse(text);

		if (typeof parsed !== "object" || parsed === null) {
			return {};
		}

		// a hand-edited manifest degrades to a rewrite of every file, the same
		// as an absent one, so each entry is kept when it holds a revision
		return Object.fromEntries(
			Object.entries(parsed).filter(
				(entry): entry is [string, string] => typeof entry[1] === "string",
			),
		);
	} catch {
		return {};
	}
}

// Holds the emitter revision under a key that no file name can take
const GENERATOR_KEY = "#generator";

// Forces an update when an older emitter wrote the manifest
async function generatorRevision() {
	const lib = import.meta.dirname;
	const root = path.join(lib, "..");
	const entries = await readdir(lib);
	const sources = entries
		.filter((name) => name.endsWith(".ts"))
		.toSorted()
		.map((name) => path.join(lib, name));

	sources.push(path.join(lib, "..", "bin", "index.ts"));

	// keyed by the path inside the package, so a second checkout and CI agree
	// on the revision
	const files = await Promise.all(
		sources.map(async (source) => ({
			name: path.relative(root, source),
			contents: await readFile(source),
		})),
	);

	const hash = createHash("sha256");

	for (const file of files) {
		hash.update(file.name);
		hash.update(file.contents);
	}

	return hash.digest("hex").slice(0, 32);
}

export async function build(
	inputFile: string,
	outputDir: string,
	tags?: string[],
	options?: CodegenOptions,
) {
	const imported: unknown = await import(inputFile, {
		with: { type: "json" },
	});

	const apischema =
		typeof imported === "object" && imported !== null && "default" in imported
			? imported.default
			: undefined;

	if (!isOpenApiDocument(apischema)) {
		throw new Error(
			`${inputFile} has no OpenAPI document as its default export`,
		);
	}

	const {
		commandsFile,
		commandsValidatedFile,
		typesFile,
		mainFile,
		valibotFile,
		honoFile,
		enumsFile,
	} = await processOpenApiDocument(outputDir, apischema, tags, options);

	const files = [
		commandsFile,
		typesFile,
		mainFile,
		valibotFile,
		honoFile,
		...(commandsValidatedFile.getStatements().length > 0
			? [commandsValidatedFile]
			: []),
		...(enumsFile.getStatements().length > 0 ? [enumsFile] : []),
	];

	await mkdir(outputDir, { recursive: true });

	const manifestPath = path.join(outputDir, MANIFEST);
	const stored = await readManifest(manifestPath);
	const generator = await generatorRevision();
	const previous = stored[GENERATOR_KEY] === generator ? stored : {};
	const revisions = await Promise.all(
		files.map(async (file) => {
			try {
				file.formatText();
			} catch (error) {
				console.warn(error);
			}

			// the blank line detaches the banner from the first import, which
			// oxfmt would otherwise move with that import when it sorts them
			const contents = `${BANNER}\n\n${file.getFullText()}`;
			const name = file.getBaseName();
			const rev = createHash("sha256")
				.update(contents)
				.digest("hex")
				.slice(0, 32);

			const present = await readFile(file.getFilePath(), "utf8")
				.then(() => true)
				.catch(() => false);

			if (previous[name] !== rev || !present) {
				await writeFile(file.getFilePath(), contents);
			}

			return { name, rev };
		}),
	);

	const next = {
		[GENERATOR_KEY]: generator,
		...Object.fromEntries(revisions.map(({ name, rev }) => [name, rev])),
	};

	await writeFile(manifestPath, `${JSON.stringify(next, undefined, "\t")}\n`);
}
