import { writeFile } from "node:fs/promises";
import type { oas31 } from "openapi3-ts";
import { processOpenApiDocument } from "./process-document.ts";

export async function build(
	inputFile: string,
	outputDir: string,
	tags?: string[],
) {
	const apischema = (await import(inputFile, {
		with: { type: "json" },
	})) as { default: oas31.OpenAPIObject };

	const banner = `
  /**
   * This file was auto generated by @block65/openapi-codegen
   *
   * WARN: Do not edit directly.
   *
   * Generated on ${new Date().toISOString()}
   *
  */`.trim();

	const { commandsFile, typesFile, mainFile, valibotFile, honoValibotFile } =
		await processOpenApiDocument(outputDir, apischema.default, tags);

	const files = [
		commandsFile,
		typesFile,
		mainFile,
		valibotFile,
		honoValibotFile,
	];

	commandsFile.insertStatements(0, "/** eslint-disable max-classes */");

	// eslint-disable-next-line no-restricted-syntax
	for await (const file of files) {
		try {
			file.insertStatements(0, banner);
			file.formatText();

			await file.save();

			await writeFile(file.getFilePath(), file.getFullText());
		} catch (err) {
			console.warn(err);
			await writeFile(file.getFilePath(), file.getFullText());
		}
	}
}
