import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import type { oas31 } from "openapi3-ts";
import {
	type CodegenOptions,
	processOpenApiDocument,
} from "./process-document.ts";

export async function build(
	inputFile: string,
	outputDir: string,
	tags?: string[],
	options?: CodegenOptions,
) {
	const apischema = (await import(inputFile, {
		with: { type: "json" },
	})) as { default: oas31.OpenAPIObject };

	const banner = (rev: string) =>
		`
  /**
   * This file was auto generated by @block65/openapi-codegen
   *
   * WARN: Do not edit directly.
   *
   * Generated on ${new Date().toISOString()} (rev ${rev})
   *
  */`.trim();

	const {
		commandsFile,
		commandsValidatedFile,
		typesFile,
		mainFile,
		valibotFile,
		honoFile,
		enumsFile,
	} = await processOpenApiDocument(outputDir, apischema.default, tags, options);

	const files = [
		commandsFile,
		typesFile,
		mainFile,
		valibotFile,
		honoFile,
		...(commandsValidatedFile.getStatements().length > 0
			? [commandsValidatedFile]
			: []),
		...(enumsFile.getStatements().length > 0 ? [enumsFile] : []),
	];

	commandsFile.insertStatements(0, "/** eslint-disable max-classes */");
	commandsValidatedFile.insertStatements(
		0,
		"/** eslint-disable max-classes */",
	);

	// eslint-disable-next-line no-restricted-syntax
	for await (const file of files) {
		// The existing file has usually been reformatted (oxfmt etc.), so its
		// bytes never match the raw emitter output. Instead of comparing text,
		// each file's banner carries a hash of the raw output that produced it:
		// when the fresh output hashes to the stamp already in the file, the
		// content is unchanged and the file (and its date) is left untouched.
		const rev = createHash("sha256")
			.update(file.getFullText())
			.digest("hex")
			.slice(0, 32);

		const existing = await readFile(file.getFilePath(), "utf8").catch(
			() => undefined,
		);

		if (existing?.includes(`(rev ${rev})`)) {
			continue;
		}

		try {
			file.insertStatements(0, banner(rev));
			file.formatText();
		} catch (err) {
			console.warn(err);
		}

		await writeFile(file.getFilePath(), file.getFullText());
	}
}
