/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class ContainerListCommand extends commands.ContainerListCommand {
	public override readonly responseSchema =
		schemas.containerListCommandResponseSchema;
}

export class ContainerCreateCommand extends commands.ContainerCreateCommand {
	public override readonly responseSchema =
		schemas.containerCreateCommandResponseSchema;
}

export class ContainerInspectCommand extends commands.ContainerInspectCommand {
	public override readonly responseSchema =
		schemas.containerInspectCommandResponseSchema;
}

export class ContainerTopCommand extends commands.ContainerTopCommand {
	public override readonly responseSchema =
		schemas.containerTopCommandResponseSchema;
}

export class ContainerChangesCommand extends commands.ContainerChangesCommand {
	public override readonly responseSchema =
		schemas.containerChangesCommandResponseSchema;
}

export class ContainerStatsCommand extends commands.ContainerStatsCommand {
	public override readonly responseSchema =
		schemas.containerStatsCommandResponseSchema;
}

export class ContainerUpdateCommand extends commands.ContainerUpdateCommand {
	public override readonly responseSchema =
		schemas.containerUpdateCommandResponseSchema;
}

export class ContainerWaitCommand extends commands.ContainerWaitCommand {
	public override readonly responseSchema =
		schemas.containerWaitCommandResponseSchema;
}

export class ContainerPruneCommand extends commands.ContainerPruneCommand {
	public override readonly responseSchema =
		schemas.containerPruneCommandResponseSchema;
}

export class ImageListCommand extends commands.ImageListCommand {
	public override readonly responseSchema =
		schemas.imageListCommandResponseSchema;
}

export class BuildPruneCommand extends commands.BuildPruneCommand {
	public override readonly responseSchema =
		schemas.buildPruneCommandResponseSchema;
}

export class ImageInspectCommand extends commands.ImageInspectCommand {
	public override readonly responseSchema =
		schemas.imageInspectCommandResponseSchema;
}

export class ImageHistoryCommand extends commands.ImageHistoryCommand {
	public override readonly responseSchema =
		schemas.imageHistoryCommandResponseSchema;
}

export class ImageDeleteCommand extends commands.ImageDeleteCommand {
	public override readonly responseSchema =
		schemas.imageDeleteCommandResponseSchema;
}

export class ImageSearchCommand extends commands.ImageSearchCommand {
	public override readonly responseSchema =
		schemas.imageSearchCommandResponseSchema;
}

export class ImagePruneCommand extends commands.ImagePruneCommand {
	public override readonly responseSchema =
		schemas.imagePruneCommandResponseSchema;
}

export class SystemAuthCommand extends commands.SystemAuthCommand {
	public override readonly responseSchema =
		schemas.systemAuthCommandResponseSchema;
}

export class SystemInfoCommand extends commands.SystemInfoCommand {
	public override readonly responseSchema =
		schemas.systemInfoCommandResponseSchema;
}

export class SystemVersionCommand extends commands.SystemVersionCommand {
	public override readonly responseSchema =
		schemas.systemVersionCommandResponseSchema;
}

export class ImageCommitCommand extends commands.ImageCommitCommand {
	public override readonly responseSchema =
		schemas.imageCommitCommandResponseSchema;
}

export class SystemEventsCommand extends commands.SystemEventsCommand {
	public override readonly responseSchema =
		schemas.systemEventsCommandResponseSchema;
}

export class SystemDataUsageCommand extends commands.SystemDataUsageCommand {
	public override readonly responseSchema =
		schemas.systemDataUsageCommandResponseSchema;
}

export class ContainerExecCommand extends commands.ContainerExecCommand {
	public override readonly responseSchema =
		schemas.containerExecCommandResponseSchema;
}

export class ExecInspectCommand extends commands.ExecInspectCommand {
	public override readonly responseSchema =
		schemas.execInspectCommandResponseSchema;
}

export class VolumeListCommand extends commands.VolumeListCommand {
	public override readonly responseSchema =
		schemas.volumeListCommandResponseSchema;
}

export class VolumeCreateCommand extends commands.VolumeCreateCommand {
	public override readonly responseSchema =
		schemas.volumeCreateCommandResponseSchema;
}

export class VolumeInspectCommand extends commands.VolumeInspectCommand {
	public override readonly responseSchema =
		schemas.volumeInspectCommandResponseSchema;
}

export class VolumePruneCommand extends commands.VolumePruneCommand {
	public override readonly responseSchema =
		schemas.volumePruneCommandResponseSchema;
}

export class NetworkListCommand extends commands.NetworkListCommand {
	public override readonly responseSchema =
		schemas.networkListCommandResponseSchema;
}

export class NetworkInspectCommand extends commands.NetworkInspectCommand {
	public override readonly responseSchema =
		schemas.networkInspectCommandResponseSchema;
}

export class NetworkCreateCommand extends commands.NetworkCreateCommand {
	public override readonly responseSchema =
		schemas.networkCreateCommandResponseSchema;
}

export class NetworkPruneCommand extends commands.NetworkPruneCommand {
	public override readonly responseSchema =
		schemas.networkPruneCommandResponseSchema;
}

export class PluginListCommand extends commands.PluginListCommand {
	public override readonly responseSchema =
		schemas.pluginListCommandResponseSchema;
}

export class GetPluginPrivilegesCommand
	extends commands.GetPluginPrivilegesCommand
{
	public override readonly responseSchema =
		schemas.getPluginPrivilegesCommandResponseSchema;
}

export class PluginInspectCommand extends commands.PluginInspectCommand {
	public override readonly responseSchema =
		schemas.pluginInspectCommandResponseSchema;
}

export class PluginDeleteCommand extends commands.PluginDeleteCommand {
	public override readonly responseSchema =
		schemas.pluginDeleteCommandResponseSchema;
}

export class NodeListCommand extends commands.NodeListCommand {
	public override readonly responseSchema =
		schemas.nodeListCommandResponseSchema;
}

export class NodeInspectCommand extends commands.NodeInspectCommand {
	public override readonly responseSchema =
		schemas.nodeInspectCommandResponseSchema;
}

export class SwarmInspectCommand extends commands.SwarmInspectCommand {
	public override readonly responseSchema =
		schemas.swarmInspectCommandResponseSchema;
}

export class SwarmInitCommand extends commands.SwarmInitCommand {
	public override readonly responseSchema =
		schemas.swarmInitCommandResponseSchema;
}

export class SwarmUnlockkeyCommand extends commands.SwarmUnlockkeyCommand {
	public override readonly responseSchema =
		schemas.swarmUnlockkeyCommandResponseSchema;
}

export class ServiceListCommand extends commands.ServiceListCommand {
	public override readonly responseSchema =
		schemas.serviceListCommandResponseSchema;
}

export class ServiceCreateCommand extends commands.ServiceCreateCommand {
	public override readonly responseSchema =
		schemas.serviceCreateCommandResponseSchema;
}

export class ServiceInspectCommand extends commands.ServiceInspectCommand {
	public override readonly responseSchema =
		schemas.serviceInspectCommandResponseSchema;
}

export class ServiceUpdateCommand extends commands.ServiceUpdateCommand {
	public override readonly responseSchema =
		schemas.serviceUpdateCommandResponseSchema;
}

export class TaskListCommand extends commands.TaskListCommand {
	public override readonly responseSchema =
		schemas.taskListCommandResponseSchema;
}

export class TaskInspectCommand extends commands.TaskInspectCommand {
	public override readonly responseSchema =
		schemas.taskInspectCommandResponseSchema;
}

export class SecretListCommand extends commands.SecretListCommand {
	public override readonly responseSchema =
		schemas.secretListCommandResponseSchema;
}

export class SecretCreateCommand extends commands.SecretCreateCommand {
	public override readonly responseSchema =
		schemas.secretCreateCommandResponseSchema;
}

export class SecretInspectCommand extends commands.SecretInspectCommand {
	public override readonly responseSchema =
		schemas.secretInspectCommandResponseSchema;
}

export class ConfigListCommand extends commands.ConfigListCommand {
	public override readonly responseSchema =
		schemas.configListCommandResponseSchema;
}

export class ConfigCreateCommand extends commands.ConfigCreateCommand {
	public override readonly responseSchema =
		schemas.configCreateCommandResponseSchema;
}

export class ConfigInspectCommand extends commands.ConfigInspectCommand {
	public override readonly responseSchema =
		schemas.configInspectCommandResponseSchema;
}

export class DistributionInspectCommand
	extends commands.DistributionInspectCommand
{
	public override readonly responseSchema =
		schemas.distributionInspectCommandResponseSchema;
}

export {
	ConfigDeleteCommand,
	ConfigUpdateCommand,
	ContainerArchiveCommand,
	ContainerArchiveInfoCommand,
	ContainerAttachCommand,
	ContainerAttachWebsocketCommand,
	ContainerDeleteCommand,
	ContainerExportCommand,
	ContainerKillCommand,
	ContainerLogsCommand,
	ContainerPauseCommand,
	ContainerRenameCommand,
	ContainerResizeCommand,
	ContainerRestartCommand,
	ContainerStartCommand,
	ContainerStopCommand,
	ContainerUnpauseCommand,
	ExecResizeCommand,
	ExecStartCommand,
	ImageBuildCommand,
	ImageCreateCommand,
	ImageGetAllCommand,
	ImageGetCommand,
	ImageLoadCommand,
	ImagePushCommand,
	ImageTagCommand,
	NetworkConnectCommand,
	NetworkDeleteCommand,
	NetworkDisconnectCommand,
	NodeDeleteCommand,
	NodeUpdateCommand,
	PluginCreateCommand,
	PluginDisableCommand,
	PluginEnableCommand,
	PluginPullCommand,
	PluginPushCommand,
	PluginSetCommand,
	PluginUpgradeCommand,
	PutContainerArchiveCommand,
	SecretDeleteCommand,
	SecretUpdateCommand,
	ServiceDeleteCommand,
	ServiceLogsCommand,
	SessionCommand,
	SwarmJoinCommand,
	SwarmLeaveCommand,
	SwarmUnlockCommand,
	SwarmUpdateCommand,
	SystemPingCommand,
	SystemPingHeadCommand,
	TaskLogsCommand,
	VolumeDeleteCommand,
	VolumeUpdateCommand,
} from "./commands.js";
