/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-09-02T06:50:52.317Z (rev 829fd9f0a511b204e1eed4924527927b)
 *
 */
/**
 * Kind of change
 *
 * Can be one of:
 *
 * - `0`: Modified ("C")
 * - `1`: Added ("A")
 * - `2`: Deleted ("D")
 */
export const changeType = [0, 1, 2] as const;
/** NodeState represents the state of a node. */
export const nodeState = ["unknown", "down", "ready", "disconnected"] as const;
/** Reachability represents the reachability of a node. */
export const reachability = ["unknown", "unreachable", "reachable"] as const;
export const taskState = [
	"new",
	"allocated",
	"pending",
	"assigned",
	"accepted",
	"preparing",
	"ready",
	"starting",
	"running",
	"complete",
	"shutdown",
	"failed",
	"rejected",
	"remove",
	"orphaned",
] as const;
/** Current local status of this node. */
export const localNodeState = [
	"",
	"inactive",
	"pending",
	"active",
	"error",
	"locked",
] as const;
