/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import { PublicValidationError } from "@block65/rest-client";
import { sValidator } from "@hono/standard-validator";
import type { ValidationTargets } from "hono";
import {
	buildPruneCommandQuerySchema,
	configCreateCommandBodySchema,
	configDeleteCommandParamsSchema,
	configInspectCommandParamsSchema,
	configListCommandQuerySchema,
	configUpdateCommandBodySchema,
	configUpdateCommandParamsSchema,
	configUpdateCommandQuerySchema,
	containerArchiveCommandParamsSchema,
	containerArchiveCommandQuerySchema,
	containerArchiveInfoCommandParamsSchema,
	containerArchiveInfoCommandQuerySchema,
	containerAttachCommandParamsSchema,
	containerAttachCommandQuerySchema,
	containerAttachWebsocketCommandParamsSchema,
	containerAttachWebsocketCommandQuerySchema,
	containerChangesCommandParamsSchema,
	containerCreateCommandBodySchema,
	containerCreateCommandQuerySchema,
	containerDeleteCommandParamsSchema,
	containerDeleteCommandQuerySchema,
	containerExecCommandBodySchema,
	containerExecCommandParamsSchema,
	containerExportCommandParamsSchema,
	containerInspectCommandParamsSchema,
	containerInspectCommandQuerySchema,
	containerKillCommandParamsSchema,
	containerKillCommandQuerySchema,
	containerListCommandQuerySchema,
	containerLogsCommandParamsSchema,
	containerLogsCommandQuerySchema,
	containerPauseCommandParamsSchema,
	containerPruneCommandQuerySchema,
	containerRenameCommandParamsSchema,
	containerRenameCommandQuerySchema,
	containerResizeCommandParamsSchema,
	containerResizeCommandQuerySchema,
	containerRestartCommandParamsSchema,
	containerRestartCommandQuerySchema,
	containerStartCommandParamsSchema,
	containerStartCommandQuerySchema,
	containerStatsCommandParamsSchema,
	containerStatsCommandQuerySchema,
	containerStopCommandParamsSchema,
	containerStopCommandQuerySchema,
	containerTopCommandParamsSchema,
	containerTopCommandQuerySchema,
	containerUnpauseCommandParamsSchema,
	containerUpdateCommandBodySchema,
	containerUpdateCommandParamsSchema,
	containerWaitCommandParamsSchema,
	containerWaitCommandQuerySchema,
	distributionInspectCommandParamsSchema,
	execInspectCommandParamsSchema,
	execResizeCommandParamsSchema,
	execResizeCommandQuerySchema,
	execStartCommandBodySchema,
	execStartCommandParamsSchema,
	getPluginPrivilegesCommandQuerySchema,
	imageBuildCommandQuerySchema,
	imageCommitCommandBodySchema,
	imageCommitCommandQuerySchema,
	imageCreateCommandQuerySchema,
	imageDeleteCommandParamsSchema,
	imageDeleteCommandQuerySchema,
	imageGetAllCommandQuerySchema,
	imageGetCommandParamsSchema,
	imageHistoryCommandParamsSchema,
	imageInspectCommandParamsSchema,
	imageListCommandQuerySchema,
	imageLoadCommandQuerySchema,
	imagePruneCommandQuerySchema,
	imagePushCommandParamsSchema,
	imagePushCommandQuerySchema,
	imageSearchCommandQuerySchema,
	imageTagCommandParamsSchema,
	imageTagCommandQuerySchema,
	networkConnectCommandBodySchema,
	networkConnectCommandParamsSchema,
	networkCreateCommandBodySchema,
	networkDeleteCommandParamsSchema,
	networkDisconnectCommandBodySchema,
	networkDisconnectCommandParamsSchema,
	networkInspectCommandParamsSchema,
	networkInspectCommandQuerySchema,
	networkListCommandQuerySchema,
	networkPruneCommandQuerySchema,
	nodeDeleteCommandParamsSchema,
	nodeDeleteCommandQuerySchema,
	nodeInspectCommandParamsSchema,
	nodeListCommandQuerySchema,
	nodeUpdateCommandBodySchema,
	nodeUpdateCommandParamsSchema,
	nodeUpdateCommandQuerySchema,
	pluginCreateCommandQuerySchema,
	pluginDeleteCommandParamsSchema,
	pluginDeleteCommandQuerySchema,
	pluginDisableCommandParamsSchema,
	pluginDisableCommandQuerySchema,
	pluginEnableCommandParamsSchema,
	pluginEnableCommandQuerySchema,
	pluginInspectCommandParamsSchema,
	pluginListCommandQuerySchema,
	pluginPullCommandBodySchema,
	pluginPullCommandQuerySchema,
	pluginPushCommandParamsSchema,
	pluginSetCommandBodySchema,
	pluginSetCommandParamsSchema,
	pluginUpgradeCommandBodySchema,
	pluginUpgradeCommandParamsSchema,
	pluginUpgradeCommandQuerySchema,
	putContainerArchiveCommandParamsSchema,
	putContainerArchiveCommandQuerySchema,
	secretCreateCommandBodySchema,
	secretDeleteCommandParamsSchema,
	secretInspectCommandParamsSchema,
	secretListCommandQuerySchema,
	secretUpdateCommandBodySchema,
	secretUpdateCommandParamsSchema,
	secretUpdateCommandQuerySchema,
	serviceCreateCommandBodySchema,
	serviceDeleteCommandParamsSchema,
	serviceInspectCommandParamsSchema,
	serviceInspectCommandQuerySchema,
	serviceListCommandQuerySchema,
	serviceLogsCommandParamsSchema,
	serviceLogsCommandQuerySchema,
	serviceUpdateCommandBodySchema,
	serviceUpdateCommandParamsSchema,
	serviceUpdateCommandQuerySchema,
	swarmInitCommandBodySchema,
	swarmJoinCommandBodySchema,
	swarmLeaveCommandQuerySchema,
	swarmUnlockCommandBodySchema,
	swarmUpdateCommandBodySchema,
	swarmUpdateCommandQuerySchema,
	systemAuthCommandBodySchema,
	systemDataUsageCommandQuerySchema,
	systemEventsCommandQuerySchema,
	taskInspectCommandParamsSchema,
	taskListCommandQuerySchema,
	taskLogsCommandParamsSchema,
	taskLogsCommandQuerySchema,
	volumeCreateCommandBodySchema,
	volumeDeleteCommandParamsSchema,
	volumeDeleteCommandQuerySchema,
	volumeInspectCommandParamsSchema,
	volumeListCommandQuerySchema,
	volumePruneCommandQuerySchema,
	volumeUpdateCommandBodySchema,
	volumeUpdateCommandParamsSchema,
	volumeUpdateCommandQuerySchema,
} from "./valibot.js";

type StandardSchema = Parameters<typeof sValidator>[1];

// The query arrives here as Hono parsed it, and nothing below decodes
// it. A lone value for a repeated-key array stays a string, comma,
// space and pipe joined values stay joined, and a deepObject key stays
// bracketed, so each of those fails validation. A caller sending them
// decodes the query before this middleware or replaces it, reading the
// style and explode from the query spec each operation exports below.
function validate<
	TSchema extends StandardSchema,
	TTarget extends keyof ValidationTargets,
>(target: TTarget, schema: TSchema) {
	return sValidator(target, schema, (result) => {
		if (!result.success) {
			throw PublicValidationError.fromIssues(result.error);
		}
	});
}

export const containerList = [
	validate("query", containerListCommandQuerySchema),
] as const;
export const containerCreate = [
	validate("json", containerCreateCommandBodySchema),
	validate("query", containerCreateCommandQuerySchema),
] as const;
export const containerInspect = [
	validate("param", containerInspectCommandParamsSchema),
	validate("query", containerInspectCommandQuerySchema),
] as const;
export const containerTop = [
	validate("param", containerTopCommandParamsSchema),
	validate("query", containerTopCommandQuerySchema),
] as const;
export const containerLogs = [
	validate("param", containerLogsCommandParamsSchema),
	validate("query", containerLogsCommandQuerySchema),
] as const;
export const containerChanges = [
	validate("param", containerChangesCommandParamsSchema),
] as const;
export const containerExport = [
	validate("param", containerExportCommandParamsSchema),
] as const;
export const containerStats = [
	validate("param", containerStatsCommandParamsSchema),
	validate("query", containerStatsCommandQuerySchema),
] as const;
export const containerResize = [
	validate("param", containerResizeCommandParamsSchema),
	validate("query", containerResizeCommandQuerySchema),
] as const;
export const containerStart = [
	validate("param", containerStartCommandParamsSchema),
	validate("query", containerStartCommandQuerySchema),
] as const;
export const containerStop = [
	validate("param", containerStopCommandParamsSchema),
	validate("query", containerStopCommandQuerySchema),
] as const;
export const containerRestart = [
	validate("param", containerRestartCommandParamsSchema),
	validate("query", containerRestartCommandQuerySchema),
] as const;
export const containerKill = [
	validate("param", containerKillCommandParamsSchema),
	validate("query", containerKillCommandQuerySchema),
] as const;
export const containerUpdate = [
	validate("json", containerUpdateCommandBodySchema),
	validate("param", containerUpdateCommandParamsSchema),
] as const;
export const containerRename = [
	validate("param", containerRenameCommandParamsSchema),
	validate("query", containerRenameCommandQuerySchema),
] as const;
export const containerPause = [
	validate("param", containerPauseCommandParamsSchema),
] as const;
export const containerUnpause = [
	validate("param", containerUnpauseCommandParamsSchema),
] as const;
export const containerAttach = [
	validate("param", containerAttachCommandParamsSchema),
	validate("query", containerAttachCommandQuerySchema),
] as const;
export const containerAttachWebsocket = [
	validate("param", containerAttachWebsocketCommandParamsSchema),
	validate("query", containerAttachWebsocketCommandQuerySchema),
] as const;
export const containerWait = [
	validate("param", containerWaitCommandParamsSchema),
	validate("query", containerWaitCommandQuerySchema),
] as const;
export const containerDelete = [
	validate("param", containerDeleteCommandParamsSchema),
	validate("query", containerDeleteCommandQuerySchema),
] as const;
export const containerArchive = [
	validate("param", containerArchiveCommandParamsSchema),
	validate("query", containerArchiveCommandQuerySchema),
] as const;
export const putContainerArchive = [
	validate("param", putContainerArchiveCommandParamsSchema),
	validate("query", putContainerArchiveCommandQuerySchema),
] as const;
export const containerArchiveInfo = [
	validate("param", containerArchiveInfoCommandParamsSchema),
	validate("query", containerArchiveInfoCommandQuerySchema),
] as const;
export const containerPrune = [
	validate("query", containerPruneCommandQuerySchema),
] as const;
export const imageList = [
	validate("query", imageListCommandQuerySchema),
] as const;
export const imageBuild = [
	validate("query", imageBuildCommandQuerySchema),
] as const;
export const buildPrune = [
	validate("query", buildPruneCommandQuerySchema),
] as const;
export const imageCreateQueryParams = [
	{ name: "changes", type: "array", style: "form", explode: false },
] as const;
export const imageCreate = [
	validate("query", imageCreateCommandQuerySchema),
] as const;
export const imageInspect = [
	validate("param", imageInspectCommandParamsSchema),
] as const;
export const imageHistory = [
	validate("param", imageHistoryCommandParamsSchema),
] as const;
export const imagePush = [
	validate("param", imagePushCommandParamsSchema),
	validate("query", imagePushCommandQuerySchema),
] as const;
export const imageTag = [
	validate("param", imageTagCommandParamsSchema),
	validate("query", imageTagCommandQuerySchema),
] as const;
export const imageDelete = [
	validate("param", imageDeleteCommandParamsSchema),
	validate("query", imageDeleteCommandQuerySchema),
] as const;
export const imageSearch = [
	validate("query", imageSearchCommandQuerySchema),
] as const;
export const imagePrune = [
	validate("query", imagePruneCommandQuerySchema),
] as const;
export const systemAuth = [
	validate("json", systemAuthCommandBodySchema),
] as const;
export const systemInfo = [] as const;
export const systemVersion = [] as const;
export const systemPing = [] as const;
export const systemPingHead = [] as const;
export const imageCommit = [
	validate("json", imageCommitCommandBodySchema),
	validate("query", imageCommitCommandQuerySchema),
] as const;
export const systemEvents = [
	validate("query", systemEventsCommandQuerySchema),
] as const;
export const systemDataUsageQueryParams = [
	{ name: "type", type: "array", style: "form", explode: true },
] as const;
export const systemDataUsage = [
	validate("query", systemDataUsageCommandQuerySchema),
] as const;
export const imageGet = [
	validate("param", imageGetCommandParamsSchema),
] as const;
export const imageGetAllQueryParams = [
	{ name: "names", type: "array", style: "form", explode: false },
] as const;
export const imageGetAll = [
	validate("query", imageGetAllCommandQuerySchema),
] as const;
export const imageLoad = [
	validate("query", imageLoadCommandQuerySchema),
] as const;
export const containerExec = [
	validate("json", containerExecCommandBodySchema),
	validate("param", containerExecCommandParamsSchema),
] as const;
export const execStart = [
	validate("json", execStartCommandBodySchema),
	validate("param", execStartCommandParamsSchema),
] as const;
export const execResize = [
	validate("param", execResizeCommandParamsSchema),
	validate("query", execResizeCommandQuerySchema),
] as const;
export const execInspect = [
	validate("param", execInspectCommandParamsSchema),
] as const;
export const volumeList = [
	validate("query", volumeListCommandQuerySchema),
] as const;
export const volumeCreate = [
	validate("json", volumeCreateCommandBodySchema),
] as const;
export const volumeInspect = [
	validate("param", volumeInspectCommandParamsSchema),
] as const;
export const volumeUpdate = [
	validate("json", volumeUpdateCommandBodySchema),
	validate("param", volumeUpdateCommandParamsSchema),
	validate("query", volumeUpdateCommandQuerySchema),
] as const;
export const volumeDelete = [
	validate("param", volumeDeleteCommandParamsSchema),
	validate("query", volumeDeleteCommandQuerySchema),
] as const;
export const volumePrune = [
	validate("query", volumePruneCommandQuerySchema),
] as const;
export const networkList = [
	validate("query", networkListCommandQuerySchema),
] as const;
export const networkInspect = [
	validate("param", networkInspectCommandParamsSchema),
	validate("query", networkInspectCommandQuerySchema),
] as const;
export const networkDelete = [
	validate("param", networkDeleteCommandParamsSchema),
] as const;
export const networkCreate = [
	validate("json", networkCreateCommandBodySchema),
] as const;
export const networkConnect = [
	validate("json", networkConnectCommandBodySchema),
	validate("param", networkConnectCommandParamsSchema),
] as const;
export const networkDisconnect = [
	validate("json", networkDisconnectCommandBodySchema),
	validate("param", networkDisconnectCommandParamsSchema),
] as const;
export const networkPrune = [
	validate("query", networkPruneCommandQuerySchema),
] as const;
export const pluginList = [
	validate("query", pluginListCommandQuerySchema),
] as const;
export const getPluginPrivileges = [
	validate("query", getPluginPrivilegesCommandQuerySchema),
] as const;
export const pluginPull = [
	validate("json", pluginPullCommandBodySchema),
	validate("query", pluginPullCommandQuerySchema),
] as const;
export const pluginInspect = [
	validate("param", pluginInspectCommandParamsSchema),
] as const;
export const pluginDelete = [
	validate("param", pluginDeleteCommandParamsSchema),
	validate("query", pluginDeleteCommandQuerySchema),
] as const;
export const pluginEnable = [
	validate("param", pluginEnableCommandParamsSchema),
	validate("query", pluginEnableCommandQuerySchema),
] as const;
export const pluginDisable = [
	validate("param", pluginDisableCommandParamsSchema),
	validate("query", pluginDisableCommandQuerySchema),
] as const;
export const pluginUpgrade = [
	validate("json", pluginUpgradeCommandBodySchema),
	validate("param", pluginUpgradeCommandParamsSchema),
	validate("query", pluginUpgradeCommandQuerySchema),
] as const;
export const pluginCreate = [
	validate("query", pluginCreateCommandQuerySchema),
] as const;
export const pluginPush = [
	validate("param", pluginPushCommandParamsSchema),
] as const;
export const pluginSet = [
	validate("json", pluginSetCommandBodySchema),
	validate("param", pluginSetCommandParamsSchema),
] as const;
export const nodeList = [
	validate("query", nodeListCommandQuerySchema),
] as const;
export const nodeInspect = [
	validate("param", nodeInspectCommandParamsSchema),
] as const;
export const nodeDelete = [
	validate("param", nodeDeleteCommandParamsSchema),
	validate("query", nodeDeleteCommandQuerySchema),
] as const;
export const nodeUpdate = [
	validate("json", nodeUpdateCommandBodySchema),
	validate("param", nodeUpdateCommandParamsSchema),
	validate("query", nodeUpdateCommandQuerySchema),
] as const;
export const swarmInspect = [] as const;
export const swarmInit = [
	validate("json", swarmInitCommandBodySchema),
] as const;
export const swarmJoin = [
	validate("json", swarmJoinCommandBodySchema),
] as const;
export const swarmLeave = [
	validate("query", swarmLeaveCommandQuerySchema),
] as const;
export const swarmUpdate = [
	validate("json", swarmUpdateCommandBodySchema),
	validate("query", swarmUpdateCommandQuerySchema),
] as const;
export const swarmUnlockkey = [] as const;
export const swarmUnlock = [
	validate("json", swarmUnlockCommandBodySchema),
] as const;
export const serviceList = [
	validate("query", serviceListCommandQuerySchema),
] as const;
export const serviceCreate = [
	validate("json", serviceCreateCommandBodySchema),
] as const;
export const serviceInspect = [
	validate("param", serviceInspectCommandParamsSchema),
	validate("query", serviceInspectCommandQuerySchema),
] as const;
export const serviceDelete = [
	validate("param", serviceDeleteCommandParamsSchema),
] as const;
export const serviceUpdate = [
	validate("json", serviceUpdateCommandBodySchema),
	validate("param", serviceUpdateCommandParamsSchema),
	validate("query", serviceUpdateCommandQuerySchema),
] as const;
export const serviceLogs = [
	validate("param", serviceLogsCommandParamsSchema),
	validate("query", serviceLogsCommandQuerySchema),
] as const;
export const taskList = [
	validate("query", taskListCommandQuerySchema),
] as const;
export const taskInspect = [
	validate("param", taskInspectCommandParamsSchema),
] as const;
export const taskLogs = [
	validate("param", taskLogsCommandParamsSchema),
	validate("query", taskLogsCommandQuerySchema),
] as const;
export const secretList = [
	validate("query", secretListCommandQuerySchema),
] as const;
export const secretCreate = [
	validate("json", secretCreateCommandBodySchema),
] as const;
export const secretInspect = [
	validate("param", secretInspectCommandParamsSchema),
] as const;
export const secretDelete = [
	validate("param", secretDeleteCommandParamsSchema),
] as const;
export const secretUpdate = [
	validate("json", secretUpdateCommandBodySchema),
	validate("param", secretUpdateCommandParamsSchema),
	validate("query", secretUpdateCommandQuerySchema),
] as const;
export const configList = [
	validate("query", configListCommandQuerySchema),
] as const;
export const configCreate = [
	validate("json", configCreateCommandBodySchema),
] as const;
export const configInspect = [
	validate("param", configInspectCommandParamsSchema),
] as const;
export const configDelete = [
	validate("param", configDeleteCommandParamsSchema),
] as const;
export const configUpdate = [
	validate("json", configUpdateCommandBodySchema),
	validate("param", configUpdateCommandParamsSchema),
	validate("query", configUpdateCommandQuerySchema),
] as const;
export const distributionInspect = [
	validate("param", distributionInspectCommandParamsSchema),
] as const;
export const session = [] as const;
