import { PublicValibotHonoError } from "@block65/rest-client";
/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-02T06:45:34.878Z
 *
 */
import { validator } from "hono/validator";
import * as v from "valibot";
import {
	exactBuildPruneCommandQuerySchema,
	exactConfigCreateCommandBodySchema,
	exactConfigDeleteCommandParamsSchema,
	exactConfigInspectCommandParamsSchema,
	exactConfigListCommandQuerySchema,
	exactConfigUpdateCommandBodySchema,
	exactConfigUpdateCommandParamsSchema,
	exactConfigUpdateCommandQuerySchema,
	exactContainerArchiveCommandParamsSchema,
	exactContainerArchiveCommandQuerySchema,
	exactContainerArchiveInfoCommandParamsSchema,
	exactContainerArchiveInfoCommandQuerySchema,
	exactContainerAttachCommandParamsSchema,
	exactContainerAttachCommandQuerySchema,
	exactContainerAttachWebsocketCommandParamsSchema,
	exactContainerAttachWebsocketCommandQuerySchema,
	exactContainerChangesCommandParamsSchema,
	exactContainerCreateCommandBodySchema,
	exactContainerCreateCommandQuerySchema,
	exactContainerDeleteCommandParamsSchema,
	exactContainerDeleteCommandQuerySchema,
	exactContainerExecCommandBodySchema,
	exactContainerExecCommandParamsSchema,
	exactContainerExportCommandParamsSchema,
	exactContainerInspectCommandParamsSchema,
	exactContainerInspectCommandQuerySchema,
	exactContainerKillCommandParamsSchema,
	exactContainerKillCommandQuerySchema,
	exactContainerListCommandQuerySchema,
	exactContainerLogsCommandParamsSchema,
	exactContainerLogsCommandQuerySchema,
	exactContainerPauseCommandParamsSchema,
	exactContainerPruneCommandQuerySchema,
	exactContainerRenameCommandParamsSchema,
	exactContainerRenameCommandQuerySchema,
	exactContainerResizeCommandParamsSchema,
	exactContainerResizeCommandQuerySchema,
	exactContainerRestartCommandParamsSchema,
	exactContainerRestartCommandQuerySchema,
	exactContainerStartCommandParamsSchema,
	exactContainerStartCommandQuerySchema,
	exactContainerStatsCommandParamsSchema,
	exactContainerStatsCommandQuerySchema,
	exactContainerStopCommandParamsSchema,
	exactContainerStopCommandQuerySchema,
	exactContainerTopCommandParamsSchema,
	exactContainerTopCommandQuerySchema,
	exactContainerUnpauseCommandParamsSchema,
	exactContainerUpdateCommandBodySchema,
	exactContainerUpdateCommandParamsSchema,
	exactContainerWaitCommandParamsSchema,
	exactContainerWaitCommandQuerySchema,
	exactDistributionInspectCommandParamsSchema,
	exactExecInspectCommandParamsSchema,
	exactExecResizeCommandParamsSchema,
	exactExecResizeCommandQuerySchema,
	exactExecStartCommandBodySchema,
	exactExecStartCommandParamsSchema,
	exactGetPluginPrivilegesCommandQuerySchema,
	exactImageBuildCommandQuerySchema,
	exactImageCommitCommandBodySchema,
	exactImageCommitCommandQuerySchema,
	exactImageCreateCommandQuerySchema,
	exactImageDeleteCommandParamsSchema,
	exactImageDeleteCommandQuerySchema,
	exactImageGetAllCommandQuerySchema,
	exactImageGetCommandParamsSchema,
	exactImageHistoryCommandParamsSchema,
	exactImageInspectCommandParamsSchema,
	exactImageListCommandQuerySchema,
	exactImageLoadCommandQuerySchema,
	exactImagePruneCommandQuerySchema,
	exactImagePushCommandParamsSchema,
	exactImagePushCommandQuerySchema,
	exactImageSearchCommandQuerySchema,
	exactImageTagCommandParamsSchema,
	exactImageTagCommandQuerySchema,
	exactNetworkConnectCommandBodySchema,
	exactNetworkConnectCommandParamsSchema,
	exactNetworkCreateCommandBodySchema,
	exactNetworkDeleteCommandParamsSchema,
	exactNetworkDisconnectCommandBodySchema,
	exactNetworkDisconnectCommandParamsSchema,
	exactNetworkInspectCommandParamsSchema,
	exactNetworkInspectCommandQuerySchema,
	exactNetworkListCommandQuerySchema,
	exactNetworkPruneCommandQuerySchema,
	exactNodeDeleteCommandParamsSchema,
	exactNodeDeleteCommandQuerySchema,
	exactNodeInspectCommandParamsSchema,
	exactNodeListCommandQuerySchema,
	exactNodeUpdateCommandBodySchema,
	exactNodeUpdateCommandParamsSchema,
	exactNodeUpdateCommandQuerySchema,
	exactPluginCreateCommandQuerySchema,
	exactPluginDeleteCommandParamsSchema,
	exactPluginDeleteCommandQuerySchema,
	exactPluginDisableCommandParamsSchema,
	exactPluginDisableCommandQuerySchema,
	exactPluginEnableCommandParamsSchema,
	exactPluginEnableCommandQuerySchema,
	exactPluginInspectCommandParamsSchema,
	exactPluginListCommandQuerySchema,
	exactPluginPullCommandBodySchema,
	exactPluginPullCommandQuerySchema,
	exactPluginPushCommandParamsSchema,
	exactPluginSetCommandBodySchema,
	exactPluginSetCommandParamsSchema,
	exactPluginUpgradeCommandBodySchema,
	exactPluginUpgradeCommandParamsSchema,
	exactPluginUpgradeCommandQuerySchema,
	exactPutContainerArchiveCommandParamsSchema,
	exactPutContainerArchiveCommandQuerySchema,
	exactSecretCreateCommandBodySchema,
	exactSecretDeleteCommandParamsSchema,
	exactSecretInspectCommandParamsSchema,
	exactSecretListCommandQuerySchema,
	exactSecretUpdateCommandBodySchema,
	exactSecretUpdateCommandParamsSchema,
	exactSecretUpdateCommandQuerySchema,
	exactServiceCreateCommandBodySchema,
	exactServiceDeleteCommandParamsSchema,
	exactServiceInspectCommandParamsSchema,
	exactServiceInspectCommandQuerySchema,
	exactServiceListCommandQuerySchema,
	exactServiceLogsCommandParamsSchema,
	exactServiceLogsCommandQuerySchema,
	exactServiceUpdateCommandBodySchema,
	exactServiceUpdateCommandParamsSchema,
	exactServiceUpdateCommandQuerySchema,
	exactSwarmInitCommandBodySchema,
	exactSwarmJoinCommandBodySchema,
	exactSwarmLeaveCommandQuerySchema,
	exactSwarmUnlockCommandBodySchema,
	exactSwarmUpdateCommandBodySchema,
	exactSwarmUpdateCommandQuerySchema,
	exactSystemAuthCommandBodySchema,
	exactSystemDataUsageCommandQuerySchema,
	exactSystemEventsCommandQuerySchema,
	exactTaskInspectCommandParamsSchema,
	exactTaskListCommandQuerySchema,
	exactTaskLogsCommandParamsSchema,
	exactTaskLogsCommandQuerySchema,
	exactVolumeCreateCommandBodySchema,
	exactVolumeDeleteCommandParamsSchema,
	exactVolumeDeleteCommandQuerySchema,
	exactVolumeInspectCommandParamsSchema,
	exactVolumeListCommandQuerySchema,
	exactVolumePruneCommandQuerySchema,
	exactVolumeUpdateCommandBodySchema,
	exactVolumeUpdateCommandParamsSchema,
	exactVolumeUpdateCommandQuerySchema,
} from "./valibot.js";

function toPublicValibotHonoError(err: unknown): never {
	if (err instanceof v.ValiError) {
		throw PublicValibotHonoError.from(err);
	}
	throw err;
}

export const containerList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactContainerCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerCreateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerInspectCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerTop = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerTopCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerTopCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerLogs = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerLogsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerLogsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerChanges = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerChangesCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerExport = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerExportCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerStats = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerStatsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerStatsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerResize = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerResizeCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerResizeCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerStart = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerStartCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerStartCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerStop = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerStopCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerStopCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerRestart = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerRestartCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerRestartCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerKill = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerKillCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerKillCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactContainerUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerRename = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerRenameCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerRenameCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerPause = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerPauseCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerUnpause = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerUnpauseCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerAttach = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerAttachCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerAttachCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerAttachWebsocket = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerAttachWebsocketCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerAttachWebsocketCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerWait = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerWaitCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerWaitCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerDeleteCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerArchive = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerArchiveCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerArchiveCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const putContainerArchive = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPutContainerArchiveCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPutContainerArchiveCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerArchiveInfo = [
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerArchiveInfoCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerArchiveInfoCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerPrune = [
	validator("query", (value) => {
		return v
			.parseAsync(exactContainerPruneCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageBuild = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageBuildCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const buildPrune = [
	validator("query", (value) => {
		return v
			.parseAsync(exactBuildPruneCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageCreate = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageCreateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImageInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageHistory = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImageHistoryCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imagePush = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImagePushCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactImagePushCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageTag = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImageTagCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactImageTagCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImageDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactImageDeleteCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageSearch = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageSearchCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imagePrune = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImagePruneCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const systemAuth = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSystemAuthCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const systemInfo = [] as const;
export const systemVersion = [] as const;
export const systemPing = [] as const;
export const systemPingHead = [] as const;
export const imageCommit = [
	validator("json", (value) => {
		return v
			.parseAsync(exactImageCommitCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactImageCommitCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const systemEvents = [
	validator("query", (value) => {
		return v
			.parseAsync(exactSystemEventsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const systemDataUsage = [
	validator("query", (value) => {
		return v
			.parseAsync(exactSystemDataUsageCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageGet = [
	validator("param", (value) => {
		return v
			.parseAsync(exactImageGetCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageGetAll = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageGetAllCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const imageLoad = [
	validator("query", (value) => {
		return v
			.parseAsync(exactImageLoadCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const containerExec = [
	validator("json", (value) => {
		return v
			.parseAsync(exactContainerExecCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactContainerExecCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const execStart = [
	validator("json", (value) => {
		return v
			.parseAsync(exactExecStartCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactExecStartCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const execResize = [
	validator("param", (value) => {
		return v
			.parseAsync(exactExecResizeCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactExecResizeCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const execInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactExecInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumeList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactVolumeListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumeCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactVolumeCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumeInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactVolumeInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumeUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactVolumeUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactVolumeUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactVolumeUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumeDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactVolumeDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactVolumeDeleteCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const volumePrune = [
	validator("query", (value) => {
		return v
			.parseAsync(exactVolumePruneCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactNetworkListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactNetworkInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactNetworkInspectCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactNetworkDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactNetworkCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkConnect = [
	validator("json", (value) => {
		return v
			.parseAsync(exactNetworkConnectCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactNetworkConnectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkDisconnect = [
	validator("json", (value) => {
		return v
			.parseAsync(exactNetworkDisconnectCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactNetworkDisconnectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const networkPrune = [
	validator("query", (value) => {
		return v
			.parseAsync(exactNetworkPruneCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const getPluginPrivileges = [
	validator("query", (value) => {
		return v
			.parseAsync(exactGetPluginPrivilegesCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginPull = [
	validator("json", (value) => {
		return v
			.parseAsync(exactPluginPullCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginPullCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginDeleteCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginEnable = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginEnableCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginEnableCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginDisable = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginDisableCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginDisableCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginUpgrade = [
	validator("json", (value) => {
		return v
			.parseAsync(exactPluginUpgradeCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginUpgradeCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginUpgradeCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginCreate = [
	validator("query", (value) => {
		return v
			.parseAsync(exactPluginCreateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginPush = [
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginPushCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const pluginSet = [
	validator("json", (value) => {
		return v
			.parseAsync(exactPluginSetCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactPluginSetCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const nodeList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactNodeListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const nodeInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactNodeInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const nodeDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactNodeDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactNodeDeleteCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const nodeUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactNodeUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactNodeUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactNodeUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const swarmInspect = [] as const;
export const swarmInit = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSwarmInitCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const swarmJoin = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSwarmJoinCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const swarmLeave = [
	validator("query", (value) => {
		return v
			.parseAsync(exactSwarmLeaveCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const swarmUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSwarmUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactSwarmUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const swarmUnlockkey = [] as const;
export const swarmUnlock = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSwarmUnlockCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactServiceListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactServiceCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactServiceInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactServiceInspectCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactServiceDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactServiceUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactServiceUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactServiceUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const serviceLogs = [
	validator("param", (value) => {
		return v
			.parseAsync(exactServiceLogsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactServiceLogsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const taskList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactTaskListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const taskInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactTaskInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const taskLogs = [
	validator("param", (value) => {
		return v
			.parseAsync(exactTaskLogsCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactTaskLogsCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const secretList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactSecretListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const secretCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSecretCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const secretInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactSecretInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const secretDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactSecretDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const secretUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactSecretUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactSecretUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactSecretUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const configList = [
	validator("query", (value) => {
		return v
			.parseAsync(exactConfigListCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const configCreate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactConfigCreateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const configInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactConfigInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const configDelete = [
	validator("param", (value) => {
		return v
			.parseAsync(exactConfigDeleteCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const configUpdate = [
	validator("json", (value) => {
		return v
			.parseAsync(exactConfigUpdateCommandBodySchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("param", (value) => {
		return v
			.parseAsync(exactConfigUpdateCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
	validator("query", (value) => {
		return v
			.parseAsync(exactConfigUpdateCommandQuerySchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const distributionInspect = [
	validator("param", (value) => {
		return v
			.parseAsync(exactDistributionInspectCommandParamsSchema, value)
			.catch(toPublicValibotHonoError);
	}),
] as const;
export const session = [] as const;
