/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-01-09T08:35:53.827Z
 *
 */
import { validator } from "hono/validator";
import * as v from "valibot";
import {
	buildPruneCommandQuerySchema,
	configCreateCommandBodySchema,
	configDeleteCommandParamsSchema,
	configInspectCommandParamsSchema,
	configListCommandQuerySchema,
	configUpdateCommandBodySchema,
	configUpdateCommandParamsSchema,
	configUpdateCommandQuerySchema,
	containerArchiveCommandParamsSchema,
	containerArchiveCommandQuerySchema,
	containerArchiveInfoCommandParamsSchema,
	containerArchiveInfoCommandQuerySchema,
	containerAttachCommandParamsSchema,
	containerAttachCommandQuerySchema,
	containerAttachWebsocketCommandParamsSchema,
	containerAttachWebsocketCommandQuerySchema,
	containerChangesCommandParamsSchema,
	containerCreateCommandBodySchema,
	containerCreateCommandQuerySchema,
	containerDeleteCommandParamsSchema,
	containerDeleteCommandQuerySchema,
	containerExecCommandBodySchema,
	containerExecCommandParamsSchema,
	containerExportCommandParamsSchema,
	containerInspectCommandParamsSchema,
	containerInspectCommandQuerySchema,
	containerKillCommandParamsSchema,
	containerKillCommandQuerySchema,
	containerListCommandQuerySchema,
	containerLogsCommandParamsSchema,
	containerLogsCommandQuerySchema,
	containerPauseCommandParamsSchema,
	containerPruneCommandQuerySchema,
	containerRenameCommandParamsSchema,
	containerRenameCommandQuerySchema,
	containerResizeCommandParamsSchema,
	containerResizeCommandQuerySchema,
	containerRestartCommandParamsSchema,
	containerRestartCommandQuerySchema,
	containerStartCommandParamsSchema,
	containerStartCommandQuerySchema,
	containerStatsCommandParamsSchema,
	containerStatsCommandQuerySchema,
	containerStopCommandParamsSchema,
	containerStopCommandQuerySchema,
	containerTopCommandParamsSchema,
	containerTopCommandQuerySchema,
	containerUnpauseCommandParamsSchema,
	containerUpdateCommandBodySchema,
	containerUpdateCommandParamsSchema,
	containerWaitCommandParamsSchema,
	containerWaitCommandQuerySchema,
	distributionInspectCommandParamsSchema,
	execInspectCommandParamsSchema,
	execResizeCommandParamsSchema,
	execResizeCommandQuerySchema,
	execStartCommandBodySchema,
	execStartCommandParamsSchema,
	getPluginPrivilegesCommandQuerySchema,
	imageBuildCommandQuerySchema,
	imageCommitCommandBodySchema,
	imageCommitCommandQuerySchema,
	imageCreateCommandQuerySchema,
	imageDeleteCommandParamsSchema,
	imageDeleteCommandQuerySchema,
	imageGetAllCommandQuerySchema,
	imageGetCommandParamsSchema,
	imageHistoryCommandParamsSchema,
	imageInspectCommandParamsSchema,
	imageListCommandQuerySchema,
	imageLoadCommandQuerySchema,
	imagePruneCommandQuerySchema,
	imagePushCommandParamsSchema,
	imagePushCommandQuerySchema,
	imageSearchCommandQuerySchema,
	imageTagCommandParamsSchema,
	imageTagCommandQuerySchema,
	networkConnectCommandBodySchema,
	networkConnectCommandParamsSchema,
	networkCreateCommandBodySchema,
	networkDeleteCommandParamsSchema,
	networkDisconnectCommandBodySchema,
	networkDisconnectCommandParamsSchema,
	networkInspectCommandParamsSchema,
	networkInspectCommandQuerySchema,
	networkListCommandQuerySchema,
	networkPruneCommandQuerySchema,
	nodeDeleteCommandParamsSchema,
	nodeDeleteCommandQuerySchema,
	nodeInspectCommandParamsSchema,
	nodeListCommandQuerySchema,
	nodeUpdateCommandBodySchema,
	nodeUpdateCommandParamsSchema,
	nodeUpdateCommandQuerySchema,
	pluginCreateCommandQuerySchema,
	pluginDeleteCommandParamsSchema,
	pluginDeleteCommandQuerySchema,
	pluginDisableCommandParamsSchema,
	pluginDisableCommandQuerySchema,
	pluginEnableCommandParamsSchema,
	pluginEnableCommandQuerySchema,
	pluginInspectCommandParamsSchema,
	pluginListCommandQuerySchema,
	pluginPullCommandBodySchema,
	pluginPullCommandQuerySchema,
	pluginPushCommandParamsSchema,
	pluginSetCommandBodySchema,
	pluginSetCommandParamsSchema,
	pluginUpgradeCommandBodySchema,
	pluginUpgradeCommandParamsSchema,
	pluginUpgradeCommandQuerySchema,
	putContainerArchiveCommandParamsSchema,
	putContainerArchiveCommandQuerySchema,
	secretCreateCommandBodySchema,
	secretDeleteCommandParamsSchema,
	secretInspectCommandParamsSchema,
	secretListCommandQuerySchema,
	secretUpdateCommandBodySchema,
	secretUpdateCommandParamsSchema,
	secretUpdateCommandQuerySchema,
	serviceCreateCommandBodySchema,
	serviceDeleteCommandParamsSchema,
	serviceInspectCommandParamsSchema,
	serviceInspectCommandQuerySchema,
	serviceListCommandQuerySchema,
	serviceLogsCommandParamsSchema,
	serviceLogsCommandQuerySchema,
	serviceUpdateCommandBodySchema,
	serviceUpdateCommandParamsSchema,
	serviceUpdateCommandQuerySchema,
	swarmInitCommandBodySchema,
	swarmJoinCommandBodySchema,
	swarmLeaveCommandQuerySchema,
	swarmUnlockCommandBodySchema,
	swarmUpdateCommandBodySchema,
	swarmUpdateCommandQuerySchema,
	systemAuthCommandBodySchema,
	systemDataUsageCommandQuerySchema,
	systemEventsCommandQuerySchema,
	taskInspectCommandParamsSchema,
	taskListCommandQuerySchema,
	taskLogsCommandParamsSchema,
	taskLogsCommandQuerySchema,
	volumeCreateCommandBodySchema,
	volumeDeleteCommandParamsSchema,
	volumeDeleteCommandQuerySchema,
	volumeInspectCommandParamsSchema,
	volumeListCommandQuerySchema,
	volumePruneCommandQuerySchema,
	volumeUpdateCommandBodySchema,
	volumeUpdateCommandParamsSchema,
	volumeUpdateCommandQuerySchema,
} from "./valibot.js";

export const ContainerList = [
	validator("query", (value) => {
		return v.parse(containerListCommandQuerySchema, value);
	}),
] as const;
export const ContainerCreate = [
	validator("json", (value) => {
		return v.parse(containerCreateCommandBodySchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerCreateCommandQuerySchema, value);
	}),
] as const;
export const ContainerInspect = [
	validator("param", (value) => {
		return v.parse(containerInspectCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerInspectCommandQuerySchema, value);
	}),
] as const;
export const ContainerTop = [
	validator("param", (value) => {
		return v.parse(containerTopCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerTopCommandQuerySchema, value);
	}),
] as const;
export const ContainerLogs = [
	validator("param", (value) => {
		return v.parse(containerLogsCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerLogsCommandQuerySchema, value);
	}),
] as const;
export const ContainerChanges = [
	validator("param", (value) => {
		return v.parse(containerChangesCommandParamsSchema, value);
	}),
] as const;
export const ContainerExport = [
	validator("param", (value) => {
		return v.parse(containerExportCommandParamsSchema, value);
	}),
] as const;
export const ContainerStats = [
	validator("param", (value) => {
		return v.parse(containerStatsCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerStatsCommandQuerySchema, value);
	}),
] as const;
export const ContainerResize = [
	validator("param", (value) => {
		return v.parse(containerResizeCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerResizeCommandQuerySchema, value);
	}),
] as const;
export const ContainerStart = [
	validator("param", (value) => {
		return v.parse(containerStartCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerStartCommandQuerySchema, value);
	}),
] as const;
export const ContainerStop = [
	validator("param", (value) => {
		return v.parse(containerStopCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerStopCommandQuerySchema, value);
	}),
] as const;
export const ContainerRestart = [
	validator("param", (value) => {
		return v.parse(containerRestartCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerRestartCommandQuerySchema, value);
	}),
] as const;
export const ContainerKill = [
	validator("param", (value) => {
		return v.parse(containerKillCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerKillCommandQuerySchema, value);
	}),
] as const;
export const ContainerUpdate = [
	validator("json", (value) => {
		return v.parse(containerUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(containerUpdateCommandParamsSchema, value);
	}),
] as const;
export const ContainerRename = [
	validator("param", (value) => {
		return v.parse(containerRenameCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerRenameCommandQuerySchema, value);
	}),
] as const;
export const ContainerPause = [
	validator("param", (value) => {
		return v.parse(containerPauseCommandParamsSchema, value);
	}),
] as const;
export const ContainerUnpause = [
	validator("param", (value) => {
		return v.parse(containerUnpauseCommandParamsSchema, value);
	}),
] as const;
export const ContainerAttach = [
	validator("param", (value) => {
		return v.parse(containerAttachCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerAttachCommandQuerySchema, value);
	}),
] as const;
export const ContainerAttachWebsocket = [
	validator("param", (value) => {
		return v.parse(containerAttachWebsocketCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerAttachWebsocketCommandQuerySchema, value);
	}),
] as const;
export const ContainerWait = [
	validator("param", (value) => {
		return v.parse(containerWaitCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerWaitCommandQuerySchema, value);
	}),
] as const;
export const ContainerDelete = [
	validator("param", (value) => {
		return v.parse(containerDeleteCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerDeleteCommandQuerySchema, value);
	}),
] as const;
export const ContainerArchive = [
	validator("param", (value) => {
		return v.parse(containerArchiveCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerArchiveCommandQuerySchema, value);
	}),
] as const;
export const PutContainerArchive = [
	validator("param", (value) => {
		return v.parse(putContainerArchiveCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(putContainerArchiveCommandQuerySchema, value);
	}),
] as const;
export const ContainerArchiveInfo = [
	validator("param", (value) => {
		return v.parse(containerArchiveInfoCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(containerArchiveInfoCommandQuerySchema, value);
	}),
] as const;
export const ContainerPrune = [
	validator("query", (value) => {
		return v.parse(containerPruneCommandQuerySchema, value);
	}),
] as const;
export const ImageList = [
	validator("query", (value) => {
		return v.parse(imageListCommandQuerySchema, value);
	}),
] as const;
export const ImageBuild = [
	validator("query", (value) => {
		return v.parse(imageBuildCommandQuerySchema, value);
	}),
] as const;
export const BuildPrune = [
	validator("query", (value) => {
		return v.parse(buildPruneCommandQuerySchema, value);
	}),
] as const;
export const ImageCreate = [
	validator("query", (value) => {
		return v.parse(imageCreateCommandQuerySchema, value);
	}),
] as const;
export const ImageInspect = [
	validator("param", (value) => {
		return v.parse(imageInspectCommandParamsSchema, value);
	}),
] as const;
export const ImageHistory = [
	validator("param", (value) => {
		return v.parse(imageHistoryCommandParamsSchema, value);
	}),
] as const;
export const ImagePush = [
	validator("param", (value) => {
		return v.parse(imagePushCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(imagePushCommandQuerySchema, value);
	}),
] as const;
export const ImageTag = [
	validator("param", (value) => {
		return v.parse(imageTagCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(imageTagCommandQuerySchema, value);
	}),
] as const;
export const ImageDelete = [
	validator("param", (value) => {
		return v.parse(imageDeleteCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(imageDeleteCommandQuerySchema, value);
	}),
] as const;
export const ImageSearch = [
	validator("query", (value) => {
		return v.parse(imageSearchCommandQuerySchema, value);
	}),
] as const;
export const ImagePrune = [
	validator("query", (value) => {
		return v.parse(imagePruneCommandQuerySchema, value);
	}),
] as const;
export const SystemAuth = [
	validator("json", (value) => {
		return v.parse(systemAuthCommandBodySchema, value);
	}),
] as const;
export const SystemInfo = [] as const;
export const SystemVersion = [] as const;
export const SystemPing = [] as const;
export const SystemPingHead = [] as const;
export const ImageCommit = [
	validator("json", (value) => {
		return v.parse(imageCommitCommandBodySchema, value);
	}),
	validator("query", (value) => {
		return v.parse(imageCommitCommandQuerySchema, value);
	}),
] as const;
export const SystemEvents = [
	validator("query", (value) => {
		return v.parse(systemEventsCommandQuerySchema, value);
	}),
] as const;
export const SystemDataUsage = [
	validator("query", (value) => {
		return v.parse(systemDataUsageCommandQuerySchema, value);
	}),
] as const;
export const ImageGet = [
	validator("param", (value) => {
		return v.parse(imageGetCommandParamsSchema, value);
	}),
] as const;
export const ImageGetAll = [
	validator("query", (value) => {
		return v.parse(imageGetAllCommandQuerySchema, value);
	}),
] as const;
export const ImageLoad = [
	validator("query", (value) => {
		return v.parse(imageLoadCommandQuerySchema, value);
	}),
] as const;
export const ContainerExec = [
	validator("json", (value) => {
		return v.parse(containerExecCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(containerExecCommandParamsSchema, value);
	}),
] as const;
export const ExecStart = [
	validator("json", (value) => {
		return v.parse(execStartCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(execStartCommandParamsSchema, value);
	}),
] as const;
export const ExecResize = [
	validator("param", (value) => {
		return v.parse(execResizeCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(execResizeCommandQuerySchema, value);
	}),
] as const;
export const ExecInspect = [
	validator("param", (value) => {
		return v.parse(execInspectCommandParamsSchema, value);
	}),
] as const;
export const VolumeList = [
	validator("query", (value) => {
		return v.parse(volumeListCommandQuerySchema, value);
	}),
] as const;
export const VolumeCreate = [
	validator("json", (value) => {
		return v.parse(volumeCreateCommandBodySchema, value);
	}),
] as const;
export const VolumeInspect = [
	validator("param", (value) => {
		return v.parse(volumeInspectCommandParamsSchema, value);
	}),
] as const;
export const VolumeUpdate = [
	validator("json", (value) => {
		return v.parse(volumeUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(volumeUpdateCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(volumeUpdateCommandQuerySchema, value);
	}),
] as const;
export const VolumeDelete = [
	validator("param", (value) => {
		return v.parse(volumeDeleteCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(volumeDeleteCommandQuerySchema, value);
	}),
] as const;
export const VolumePrune = [
	validator("query", (value) => {
		return v.parse(volumePruneCommandQuerySchema, value);
	}),
] as const;
export const NetworkList = [
	validator("query", (value) => {
		return v.parse(networkListCommandQuerySchema, value);
	}),
] as const;
export const NetworkInspect = [
	validator("param", (value) => {
		return v.parse(networkInspectCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(networkInspectCommandQuerySchema, value);
	}),
] as const;
export const NetworkDelete = [
	validator("param", (value) => {
		return v.parse(networkDeleteCommandParamsSchema, value);
	}),
] as const;
export const NetworkCreate = [
	validator("json", (value) => {
		return v.parse(networkCreateCommandBodySchema, value);
	}),
] as const;
export const NetworkConnect = [
	validator("json", (value) => {
		return v.parse(networkConnectCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(networkConnectCommandParamsSchema, value);
	}),
] as const;
export const NetworkDisconnect = [
	validator("json", (value) => {
		return v.parse(networkDisconnectCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(networkDisconnectCommandParamsSchema, value);
	}),
] as const;
export const NetworkPrune = [
	validator("query", (value) => {
		return v.parse(networkPruneCommandQuerySchema, value);
	}),
] as const;
export const PluginList = [
	validator("query", (value) => {
		return v.parse(pluginListCommandQuerySchema, value);
	}),
] as const;
export const GetPluginPrivileges = [
	validator("query", (value) => {
		return v.parse(getPluginPrivilegesCommandQuerySchema, value);
	}),
] as const;
export const PluginPull = [
	validator("json", (value) => {
		return v.parse(pluginPullCommandBodySchema, value);
	}),
	validator("query", (value) => {
		return v.parse(pluginPullCommandQuerySchema, value);
	}),
] as const;
export const PluginInspect = [
	validator("param", (value) => {
		return v.parse(pluginInspectCommandParamsSchema, value);
	}),
] as const;
export const PluginDelete = [
	validator("param", (value) => {
		return v.parse(pluginDeleteCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(pluginDeleteCommandQuerySchema, value);
	}),
] as const;
export const PluginEnable = [
	validator("param", (value) => {
		return v.parse(pluginEnableCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(pluginEnableCommandQuerySchema, value);
	}),
] as const;
export const PluginDisable = [
	validator("param", (value) => {
		return v.parse(pluginDisableCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(pluginDisableCommandQuerySchema, value);
	}),
] as const;
export const PluginUpgrade = [
	validator("json", (value) => {
		return v.parse(pluginUpgradeCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(pluginUpgradeCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(pluginUpgradeCommandQuerySchema, value);
	}),
] as const;
export const PluginCreate = [
	validator("query", (value) => {
		return v.parse(pluginCreateCommandQuerySchema, value);
	}),
] as const;
export const PluginPush = [
	validator("param", (value) => {
		return v.parse(pluginPushCommandParamsSchema, value);
	}),
] as const;
export const PluginSet = [
	validator("json", (value) => {
		return v.parse(pluginSetCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(pluginSetCommandParamsSchema, value);
	}),
] as const;
export const NodeList = [
	validator("query", (value) => {
		return v.parse(nodeListCommandQuerySchema, value);
	}),
] as const;
export const NodeInspect = [
	validator("param", (value) => {
		return v.parse(nodeInspectCommandParamsSchema, value);
	}),
] as const;
export const NodeDelete = [
	validator("param", (value) => {
		return v.parse(nodeDeleteCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(nodeDeleteCommandQuerySchema, value);
	}),
] as const;
export const NodeUpdate = [
	validator("json", (value) => {
		return v.parse(nodeUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(nodeUpdateCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(nodeUpdateCommandQuerySchema, value);
	}),
] as const;
export const SwarmInspect = [] as const;
export const SwarmInit = [
	validator("json", (value) => {
		return v.parse(swarmInitCommandBodySchema, value);
	}),
] as const;
export const SwarmJoin = [
	validator("json", (value) => {
		return v.parse(swarmJoinCommandBodySchema, value);
	}),
] as const;
export const SwarmLeave = [
	validator("query", (value) => {
		return v.parse(swarmLeaveCommandQuerySchema, value);
	}),
] as const;
export const SwarmUpdate = [
	validator("json", (value) => {
		return v.parse(swarmUpdateCommandBodySchema, value);
	}),
	validator("query", (value) => {
		return v.parse(swarmUpdateCommandQuerySchema, value);
	}),
] as const;
export const SwarmUnlockkey = [] as const;
export const SwarmUnlock = [
	validator("json", (value) => {
		return v.parse(swarmUnlockCommandBodySchema, value);
	}),
] as const;
export const ServiceList = [
	validator("query", (value) => {
		return v.parse(serviceListCommandQuerySchema, value);
	}),
] as const;
export const ServiceCreate = [
	validator("json", (value) => {
		return v.parse(serviceCreateCommandBodySchema, value);
	}),
] as const;
export const ServiceInspect = [
	validator("param", (value) => {
		return v.parse(serviceInspectCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(serviceInspectCommandQuerySchema, value);
	}),
] as const;
export const ServiceDelete = [
	validator("param", (value) => {
		return v.parse(serviceDeleteCommandParamsSchema, value);
	}),
] as const;
export const ServiceUpdate = [
	validator("json", (value) => {
		return v.parse(serviceUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(serviceUpdateCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(serviceUpdateCommandQuerySchema, value);
	}),
] as const;
export const ServiceLogs = [
	validator("param", (value) => {
		return v.parse(serviceLogsCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(serviceLogsCommandQuerySchema, value);
	}),
] as const;
export const TaskList = [
	validator("query", (value) => {
		return v.parse(taskListCommandQuerySchema, value);
	}),
] as const;
export const TaskInspect = [
	validator("param", (value) => {
		return v.parse(taskInspectCommandParamsSchema, value);
	}),
] as const;
export const TaskLogs = [
	validator("param", (value) => {
		return v.parse(taskLogsCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(taskLogsCommandQuerySchema, value);
	}),
] as const;
export const SecretList = [
	validator("query", (value) => {
		return v.parse(secretListCommandQuerySchema, value);
	}),
] as const;
export const SecretCreate = [
	validator("json", (value) => {
		return v.parse(secretCreateCommandBodySchema, value);
	}),
] as const;
export const SecretInspect = [
	validator("param", (value) => {
		return v.parse(secretInspectCommandParamsSchema, value);
	}),
] as const;
export const SecretDelete = [
	validator("param", (value) => {
		return v.parse(secretDeleteCommandParamsSchema, value);
	}),
] as const;
export const SecretUpdate = [
	validator("json", (value) => {
		return v.parse(secretUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(secretUpdateCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(secretUpdateCommandQuerySchema, value);
	}),
] as const;
export const ConfigList = [
	validator("query", (value) => {
		return v.parse(configListCommandQuerySchema, value);
	}),
] as const;
export const ConfigCreate = [
	validator("json", (value) => {
		return v.parse(configCreateCommandBodySchema, value);
	}),
] as const;
export const ConfigInspect = [
	validator("param", (value) => {
		return v.parse(configInspectCommandParamsSchema, value);
	}),
] as const;
export const ConfigDelete = [
	validator("param", (value) => {
		return v.parse(configDeleteCommandParamsSchema, value);
	}),
] as const;
export const ConfigUpdate = [
	validator("json", (value) => {
		return v.parse(configUpdateCommandBodySchema, value);
	}),
	validator("param", (value) => {
		return v.parse(configUpdateCommandParamsSchema, value);
	}),
	validator("query", (value) => {
		return v.parse(configUpdateCommandQuerySchema, value);
	}),
] as const;
export const DistributionInspect = [
	validator("param", (value) => {
		return v.parse(distributionInspectCommandParamsSchema, value);
	}),
] as const;
export const Session = [] as const;
