/**
 * This file was auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2026-05-02T06:45:34.878Z
 *
 */
import {
	RestServiceClient,
	type RestServiceClientConfig,
} from "@block65/rest-client";
import type {
	BuildPruneCommandInput,
	BuildPruneCommandOutput,
	ConfigCreateCommandInput,
	ConfigCreateCommandOutput,
	ConfigDeleteCommandInput,
	ConfigInspectCommandInput,
	ConfigInspectCommandOutput,
	ConfigListCommandInput,
	ConfigListCommandOutput,
	ConfigUpdateCommandInput,
	ContainerArchiveCommandInput,
	ContainerArchiveInfoCommandInput,
	ContainerAttachCommandInput,
	ContainerAttachWebsocketCommandInput,
	ContainerChangesCommandInput,
	ContainerChangesCommandOutput,
	ContainerCreateCommandInput,
	ContainerCreateCommandOutput,
	ContainerDeleteCommandInput,
	ContainerExecCommandInput,
	ContainerExecCommandOutput,
	ContainerExportCommandInput,
	ContainerInspectCommandInput,
	ContainerInspectCommandOutput,
	ContainerKillCommandInput,
	ContainerListCommandInput,
	ContainerListCommandOutput,
	ContainerLogsCommandInput,
	ContainerPauseCommandInput,
	ContainerPruneCommandInput,
	ContainerPruneCommandOutput,
	ContainerRenameCommandInput,
	ContainerResizeCommandInput,
	ContainerRestartCommandInput,
	ContainerStartCommandInput,
	ContainerStatsCommandInput,
	ContainerStatsCommandOutput,
	ContainerStopCommandInput,
	ContainerTopCommandInput,
	ContainerTopCommandOutput,
	ContainerUnpauseCommandInput,
	ContainerUpdateCommandInput,
	ContainerUpdateCommandOutput,
	ContainerWaitCommandInput,
	ContainerWaitCommandOutput,
	DistributionInspectCommandInput,
	DistributionInspectCommandOutput,
	ExecInspectCommandInput,
	ExecInspectCommandOutput,
	ExecResizeCommandInput,
	ExecStartCommandInput,
	GetPluginPrivilegesCommandInput,
	GetPluginPrivilegesCommandOutput,
	ImageBuildCommandInput,
	ImageCommitCommandInput,
	ImageCommitCommandOutput,
	ImageCreateCommandInput,
	ImageDeleteCommandInput,
	ImageDeleteCommandOutput,
	ImageGetAllCommandInput,
	ImageGetCommandInput,
	ImageHistoryCommandInput,
	ImageHistoryCommandOutput,
	ImageInspectCommandInput,
	ImageInspectCommandOutput,
	ImageListCommandInput,
	ImageListCommandOutput,
	ImageLoadCommandInput,
	ImagePruneCommandInput,
	ImagePruneCommandOutput,
	ImagePushCommandInput,
	ImageSearchCommandInput,
	ImageSearchCommandOutput,
	ImageTagCommandInput,
	NetworkConnectCommandInput,
	NetworkCreateCommandInput,
	NetworkCreateCommandOutput,
	NetworkDeleteCommandInput,
	NetworkDisconnectCommandInput,
	NetworkInspectCommandInput,
	NetworkInspectCommandOutput,
	NetworkListCommandInput,
	NetworkListCommandOutput,
	NetworkPruneCommandInput,
	NetworkPruneCommandOutput,
	NodeDeleteCommandInput,
	NodeInspectCommandInput,
	NodeInspectCommandOutput,
	NodeListCommandInput,
	NodeListCommandOutput,
	NodeUpdateCommandInput,
	PluginCreateCommandInput,
	PluginDeleteCommandInput,
	PluginDeleteCommandOutput,
	PluginDisableCommandInput,
	PluginEnableCommandInput,
	PluginInspectCommandInput,
	PluginInspectCommandOutput,
	PluginListCommandInput,
	PluginListCommandOutput,
	PluginPullCommandInput,
	PluginPushCommandInput,
	PluginSetCommandInput,
	PluginUpgradeCommandInput,
	PutContainerArchiveCommandInput,
	SecretCreateCommandInput,
	SecretCreateCommandOutput,
	SecretDeleteCommandInput,
	SecretInspectCommandInput,
	SecretInspectCommandOutput,
	SecretListCommandInput,
	SecretListCommandOutput,
	SecretUpdateCommandInput,
	ServiceCreateCommandInput,
	ServiceCreateCommandOutput,
	ServiceDeleteCommandInput,
	ServiceInspectCommandInput,
	ServiceInspectCommandOutput,
	ServiceListCommandInput,
	ServiceListCommandOutput,
	ServiceLogsCommandInput,
	ServiceUpdateCommandInput,
	ServiceUpdateCommandOutput,
	SessionCommandInput,
	SwarmInitCommandInput,
	SwarmInitCommandOutput,
	SwarmInspectCommandInput,
	SwarmInspectCommandOutput,
	SwarmJoinCommandInput,
	SwarmLeaveCommandInput,
	SwarmUnlockCommandInput,
	SwarmUnlockkeyCommandInput,
	SwarmUnlockkeyCommandOutput,
	SwarmUpdateCommandInput,
	SystemAuthCommandInput,
	SystemAuthCommandOutput,
	SystemDataUsageCommandInput,
	SystemDataUsageCommandOutput,
	SystemEventsCommandInput,
	SystemEventsCommandOutput,
	SystemInfoCommandInput,
	SystemInfoCommandOutput,
	SystemPingCommandInput,
	SystemPingHeadCommandInput,
	SystemVersionCommandInput,
	SystemVersionCommandOutput,
	TaskInspectCommandInput,
	TaskInspectCommandOutput,
	TaskListCommandInput,
	TaskListCommandOutput,
	TaskLogsCommandInput,
	VolumeCreateCommandInput,
	VolumeCreateCommandOutput,
	VolumeDeleteCommandInput,
	VolumeInspectCommandInput,
	VolumeInspectCommandOutput,
	VolumeListCommandInput,
	VolumeListCommandOutput,
	VolumePruneCommandInput,
	VolumePruneCommandOutput,
	VolumeUpdateCommandInput,
} from "./types.js";

type AllInputs =
	| BuildPruneCommandInput
	| ConfigCreateCommandInput
	| ConfigDeleteCommandInput
	| ConfigInspectCommandInput
	| ConfigListCommandInput
	| ConfigUpdateCommandInput
	| ContainerArchiveCommandInput
	| ContainerArchiveInfoCommandInput
	| ContainerAttachCommandInput
	| ContainerAttachWebsocketCommandInput
	| ContainerChangesCommandInput
	| ContainerCreateCommandInput
	| ContainerDeleteCommandInput
	| ContainerExecCommandInput
	| ContainerExportCommandInput
	| ContainerInspectCommandInput
	| ContainerKillCommandInput
	| ContainerListCommandInput
	| ContainerLogsCommandInput
	| ContainerPauseCommandInput
	| ContainerPruneCommandInput
	| ContainerRenameCommandInput
	| ContainerResizeCommandInput
	| ContainerRestartCommandInput
	| ContainerStartCommandInput
	| ContainerStatsCommandInput
	| ContainerStopCommandInput
	| ContainerTopCommandInput
	| ContainerUnpauseCommandInput
	| ContainerUpdateCommandInput
	| ContainerWaitCommandInput
	| DistributionInspectCommandInput
	| ExecInspectCommandInput
	| ExecResizeCommandInput
	| ExecStartCommandInput
	| GetPluginPrivilegesCommandInput
	| ImageBuildCommandInput
	| ImageCommitCommandInput
	| ImageCreateCommandInput
	| ImageDeleteCommandInput
	| ImageGetAllCommandInput
	| ImageGetCommandInput
	| ImageHistoryCommandInput
	| ImageInspectCommandInput
	| ImageListCommandInput
	| ImageLoadCommandInput
	| ImagePruneCommandInput
	| ImagePushCommandInput
	| ImageSearchCommandInput
	| ImageTagCommandInput
	| NetworkConnectCommandInput
	| NetworkCreateCommandInput
	| NetworkDeleteCommandInput
	| NetworkDisconnectCommandInput
	| NetworkInspectCommandInput
	| NetworkListCommandInput
	| NetworkPruneCommandInput
	| NodeDeleteCommandInput
	| NodeInspectCommandInput
	| NodeListCommandInput
	| NodeUpdateCommandInput
	| PluginCreateCommandInput
	| PluginDeleteCommandInput
	| PluginDisableCommandInput
	| PluginEnableCommandInput
	| PluginInspectCommandInput
	| PluginListCommandInput
	| PluginPullCommandInput
	| PluginPushCommandInput
	| PluginSetCommandInput
	| PluginUpgradeCommandInput
	| PutContainerArchiveCommandInput
	| SecretCreateCommandInput
	| SecretDeleteCommandInput
	| SecretInspectCommandInput
	| SecretListCommandInput
	| SecretUpdateCommandInput
	| ServiceCreateCommandInput
	| ServiceDeleteCommandInput
	| ServiceInspectCommandInput
	| ServiceListCommandInput
	| ServiceLogsCommandInput
	| ServiceUpdateCommandInput
	| SessionCommandInput
	| SwarmInitCommandInput
	| SwarmInspectCommandInput
	| SwarmJoinCommandInput
	| SwarmLeaveCommandInput
	| SwarmUnlockCommandInput
	| SwarmUnlockkeyCommandInput
	| SwarmUpdateCommandInput
	| SystemAuthCommandInput
	| SystemDataUsageCommandInput
	| SystemEventsCommandInput
	| SystemInfoCommandInput
	| SystemPingCommandInput
	| SystemPingHeadCommandInput
	| SystemVersionCommandInput
	| TaskInspectCommandInput
	| TaskListCommandInput
	| TaskLogsCommandInput
	| VolumeCreateCommandInput
	| VolumeDeleteCommandInput
	| VolumeInspectCommandInput
	| VolumeListCommandInput
	| VolumePruneCommandInput
	| VolumeUpdateCommandInput;
type AllOutputs =
	| BuildPruneCommandOutput
	| ConfigCreateCommandOutput
	| ConfigInspectCommandOutput
	| ConfigListCommandOutput
	| ContainerChangesCommandOutput
	| ContainerCreateCommandOutput
	| ContainerExecCommandOutput
	| ContainerInspectCommandOutput
	| ContainerListCommandOutput
	| ContainerPruneCommandOutput
	| ContainerStatsCommandOutput
	| ContainerTopCommandOutput
	| ContainerUpdateCommandOutput
	| ContainerWaitCommandOutput
	| DistributionInspectCommandOutput
	| ExecInspectCommandOutput
	| GetPluginPrivilegesCommandOutput
	| ImageCommitCommandOutput
	| ImageDeleteCommandOutput
	| ImageHistoryCommandOutput
	| ImageInspectCommandOutput
	| ImageListCommandOutput
	| ImagePruneCommandOutput
	| ImageSearchCommandOutput
	| NetworkCreateCommandOutput
	| NetworkInspectCommandOutput
	| NetworkListCommandOutput
	| NetworkPruneCommandOutput
	| NodeInspectCommandOutput
	| NodeListCommandOutput
	| PluginDeleteCommandOutput
	| PluginInspectCommandOutput
	| PluginListCommandOutput
	| SecretCreateCommandOutput
	| SecretInspectCommandOutput
	| SecretListCommandOutput
	| ServiceCreateCommandOutput
	| ServiceInspectCommandOutput
	| ServiceListCommandOutput
	| ServiceUpdateCommandOutput
	| SwarmInitCommandOutput
	| SwarmInspectCommandOutput
	| SwarmUnlockkeyCommandOutput
	| SystemAuthCommandOutput
	| SystemDataUsageCommandOutput
	| SystemEventsCommandOutput
	| SystemInfoCommandOutput
	| SystemVersionCommandOutput
	| TaskInspectCommandOutput
	| TaskListCommandOutput
	| undefined
	| VolumeCreateCommandOutput
	| VolumeInspectCommandOutput
	| VolumeListCommandOutput
	| VolumePruneCommandOutput;

export class DockerEngineApiRestClient extends RestServiceClient<
	AllInputs,
	AllOutputs
> {
	constructor(
		baseUrl: string | URL = new URL("http://docker.local:2375/v1.43/"),
		config?: RestServiceClientConfig,
	) {
		super(baseUrl, config);
	}
}
